### ISSUE TITLE
How to distinguish multiple clients

### ISSUE THREAD

**Issue by Rasterer** [capnproto/capnproto#1000]
I'm new to capnproto. In my case, I have many clients connecting to one server. How can I distinguish between these clients? It looks like VatId is the unique identifier of each network participant. But I don't find VatId access interface in TwoPartyServer/TwoPartyClient. Am I missing something?
I think this is a quite common requirement. Is there any convenient method to do this?

**Comment by kentonv** [comment]
Distinguish for what purpose? Do you need to extract connection metadata like IP address, or do you just want to be able to tell when two calls are from the same client? In the latter case, you can have each client start by calling a method that returns an object specific to that client, and then all further calls use that object, like:

    interface Service {
      startSession @0 () -> (session :Session);
    }

    interface Session {
      # all methods here
    }

So each time `startSession()` is called, you construct and return an object for use by that particular client. All calls to that session object then come from that client. When the client disconnects, the session object will be destroyed.

**Comment by kentonv** [comment]
Taking this further, say you want users to authenticate with a username and password. You could do something like:

```capnp
interface Service {
  login @0 (username :Text, password :Text) -> (session :AuthenticatedSession);
}

interface AuthenticatedSession {
  # all methods here
}
```

This is secure: only the client that called `login()` can access the `session` object it returns, so once you've verified the credentials, you can assume all calls to the session object are from that user without requiring the credentials to be sent again.

**Comment by kentonv** [comment]
Meanwhile, if you need to extract metadata from the connection -- e.g. the client's IP address -- then things are slightly more complicated. This is where `TwoPartyServer`'s `accept()` method comes in handy -- it lets you pass an already-open stream. So you can write your own code to listen for connections and then call `getpeername()` on them before you pass them into `TwoPartyServer`.

Though, in this case, you probably also want to construct a unique bootstrap capability for each connecting client -- so that it knows the metadata that you extracted. To do that, you might not want to use `TwoPartyServer` at all, but instead use `TwoPartyClient`. The capnp protocol is actually symmetric -- the only real difference between `TwoPartyClient` and `TwoPartyServer` is that `TwoPartyServer` expects to handle multiple connections. You can instead construct a new `TwoPartyClient` for each connection you receive, using a different bootstrap object. (Make sure to pass `capnp::rpc::twoparty::Side::SERVER` for the `side` argument to the constructor.)

Note that `VatId` only really matters if you're using a multi-party `VatNetwork`, not two-party. The idea behind a multi-party network is that you could, say, have two clients, and instruct one to form a direct connection to the other to talk to it. This part of Cap'n Proto isn't totally done yet, though, so you can probably ignore it for now.

I think at least one of my comments here should answer your questions, so I'll close this issue.
