### ISSUE TITLE
"StringPtr must be NUL-terminated." exception in call to capnp Builder::setTextField

### ISSUE THREAD

**Issue by TheSeven** [capnproto/capnproto#1030]
Upon closer inspection of the crash site, it appears like this comment doesn't hold true:
https://github.com/capnproto/capnproto/blob/b656e5968bae4f2895050b764c6e51b2d64bf31f/c%2B%2B/src/capnp/layout.c%2B%2B#L1613
...and the constructor of `capnp::Text::Builder` requires the NUL terminator to already be present:
https://github.com/capnproto/capnproto/blob/b656e5968bae4f2895050b764c6e51b2d64bf31f/c%2B%2B/src/capnp/blob.h#L116

However, this code doesn't appear to have been touched in 7 years, and I can't quite believe that nobody would have ran into this in the meantime.
So either I'm missing something, or the buffer just happens to contain zeros almost all the time, just not in my application...

**Comment by kentonv** [comment]
Hi @TheSeven,

> So either I'm missing something, or the buffer just happens to contain zeros almost all the time, just not in my application...

Not "just happens" -- this is an explicit requirement:

https://github.com/capnproto/capnproto/blob/3f0fee61c65475c8debfdf8c01f96c2f7e7eeb14/c++/src/capnp/message.h#L193-L202

https://github.com/capnproto/capnproto/blob/3f0fee61c65475c8debfdf8c01f96c2f7e7eeb14/c++/src/capnp/message.h#L394-L401

I guess probably you are passing a non-zero-initialized scratch buffer to `MallocMessageBuilder`'s constructor. The constructor actually checks the first 8 bytes of the buffer and throws if they aren't zero, but it doesn't check the whole buffer because that would take too long. So if the buffer coincidentally starts with zero, you can evade the check, and then you get confusing errors, data corruption, and maybe even subtle private data leaks later on -- ouch. :(

The comment you mention looks like it may have been written in the very early days, before allocators were required to zero-initialize, and then was never updated.

**Comment by TheSeven** [comment]
Looks like the cause was an out of bounds set call on a ListBuilder, which was in turn caused by the index variable being accidentally overridden by a nested scope.
The comments that you refer to above were too far from the call site to get noticed. E.g. `capnp::_::WireHelpers::allocate` has a big comment, but doesn't mention that it returns zero-initialized memory. It's also not obvious from its contents, because the memory is pre-zeroed. That sent me down the wrong route here...

Anyway, I think the issue that should be fixed here is that outdated comment.
