### ISSUE TITLE
Incremental writes

### ISSUE THREAD

**Issue by Timmmm** [capnproto/capnproto#1040]
I'm having a little trouble understanding if Capnp supports incremental writes. I mean, suppose I have some enormous (100GB say) file to write, is it possible to write it a bit at a time, so I don't have to store the whole lot in memory at once? From my reading of the encoding spec (which could really do with some examples!) it seems like it should be possible because you can write lots of small objects to disk, and then write the object/array that contains them later and use pointers to those small objects.

But I can't find anything about this anywhere in the code or docs. There's no `FileMessageBuilder` or `MmapMessageBuilder`. Is it possible with the current API, and if not, is it possible with the current file format but a new API?

**Comment by kentonv** [comment]
Hi Tim,

I think the right way to do this would be with mmap. There is currently no built-in `MmapMessageBuilder`, but you could write one without changing anything in capnp itself.

You might need to change the format of the segment table, since you probably don't know upfront how many segments you'll need, so you won't know how much space to leave at the beginning of the file to store the table. Maybe you could store it at the end of the file instead, or interleaved. You will then need a custom MessageReader to read this, of course, but that's probably relatively easy compared to writing the builder.

**Comment by kentonv** [comment]
(Closing because I don't think I'd add this myself to Cap'n Proto without a clear use case in mind, but I'm happy to consider PRs if someone else comes up with a solution that works for them and wants to contribute it back to the core library.)
