### ISSUE TITLE
Question: can we add struct fields based on values in other fields?

### ISSUE THREAD

**Issue by nelson-liu** [capnproto/capnproto#1043]
To slightly modify an example from the tutorial:

```
struct Shape {
  area @0 :Float64;
  shapetype @1: Text:

  union {
    circle :group {
      radius @1 :Float64;
    }
    rectangle :group {
      width @2 :Float64;
      height @3 :Float64;
    }
  }
}
```

In the above, to access the radius of a circle message , you'd use `shape.circle.radius`. Would it be possible to write the Schema such that if the value of `shapetype` is `circle`, `shape` has a member `radius` that you can access at `shape.radius`? Sorry if this is entirely impossible and a stupid question!

**Comment by kentonv** [comment]
Hi Nelson,

I'm not sure I understand the question.

Are you saying that you want the union to be discriminated based on the value of `shapetype`, rather than using a 16-bit union tag as normal? So, e.g., if `shapetype == "circle"` then we decide that the `circle` union member is active, without having to store a separate 16-bit tag value?

There isn't any way to do that, no. What you're describing is more generally known as "dependent types" and has been the subject of a lot of programming language research, but it gets pretty complicated. It would certainly be pretty cool to support, but this isn't likely something we'll implement anytime soon due to the sheer complexity.

**Comment by nelson-liu** [comment]
> Are you saying that you want the union to be discriminated based on the value of shapetype, rather than using a 16-bit union tag as normal? So, e.g., if shapetype == "circle" then we decide that the circle union member is active, without having to store a separate 16-bit tag value?

Yup, this is what I was asking about. Thanks for the quick response!

> There isn't any way to do that, no. What you're describing is more generally known as "dependent types" and has been the subject of a lot of programming language research, but it gets pretty complicated. It would certainly be pretty cool to support, but this isn't likely something we'll implement anytime soon due to the sheer complexity.

Great, thanks for the pointer—"dependent types" is indeed what i was looking for 😅
