### ISSUE TITLE
Use capnproto with fifo

### ISSUE THREAD

**Issue by marek-piirikivi** [capnproto/capnproto#1052]
I have set up connection between 2 independent processes where one process sends capnproto messages to other.
I am opening fifo on the other end with O_RDONLY which means that it will block this open call until something opens fifo for writing. This works all fine.
Because of this blocking nature of how fifos get opened, I would prefer to open fifo with additional O_NONBLOCK flag. This does not play well with capnproto.

Are there some guidelines how one would go about using capnproto with fifo?

**Comment by kentonv** [comment]
I don't understand. What does Cap'n Proto have to do with how you open the file? What problem are you running into specifically?

**Comment by marek-piirikivi** [comment]
Cap'n Proto throws on EWOULDBLOCK when I have opened fifo with O_NONBLOCK when there isn't anything to read. A preferred way would be to simply ignore or report gracefully back that there isn't anything to read/parse. This comes when I call tryReadBuffers on stream wrapper.

The question is whether there is a way to get similar behavior of what I just described. Maybe I need to use different kind of stream object or use custom buffer?

**Comment by kentonv** [comment]
What is `tryReadBuffers`? This identifier doesn't seem to appear anywhere in this repository AFAICT.

What exact Cap'n Proto API are you calling which is throwing?

**Comment by marek-piirikivi** [comment]
Hello, I made a typo in name. It should have been tryGetReadBuffer. I'll share snippet:

```
// Prepare stream
int file = open("my_fifo", O_RDONLY | O_NONBLOCK);
kj::FdInputStream stream{file};
kj::BufferedInputStreamWrapper buffered_stream{stream};
// Loop - at this point, file may or may not have anything to read
while (true)
{
    if (buffered_stream.tryGetReadBuffer() != nullptr)
    {
	capnp::PackedMessageReader reader{buffered_stream};
	const auto msg{reader.getRoot<messages::MyMessage>()};
	const auto mval{msg.getMyValue()};
        // And then I do some amazing things with mval
    }
}
```
I get thrown when other end is not present (or reconnects).

**Comment by kentonv** [comment]
OK, thanks for clarifying.

There is fundamentally no way Cap'n Proto's blocking I/O APIs can work correctly on a non-blocking socket. You suggested:

> A preferred way would be to simply ignore or report gracefully back that there isn't anything to read/parse.

This doesn't work, because it's possible the stream will read some bytes and _then_ receive `EWOULDBLOCK`. Cap'n Proto would then be stuck with a half-read message. If it returned to the app saying "there's nothing to read", then the bytes that were already read would be lost, and the next attempt to read would start reading mid-message and would end up with a corrupted result.

There are a few designs you can use in your code to solve this situation:

1. Turn off `O_NONBLOCK` after opening the file (e.g. using `fcntl(fd, F_SETFL, 0)`). You can use `poll()` or similar mechanisms in your own code to determine whether data is available to read from the pipe before you attempt to read a message. Note that if only a partial message is available on the pipe, then you may still end up blocking as Cap'n Proto waits for the remainder of the message. However, assuming the sender always sends a full message, you won't block for long.

2. Read bytes into your own buffer using any non-blocking-friendly I/O mechanism you like, and then use `capnp::expectedSizeInWordsFromPrefix()` to determine if you have a complete message. (Note that this only works with unpacked I/O, and I notice you seem to be using packed. However, if you are passing messages between processes on the same machine, then I'd strongly recommend switching to unpacked format anyway. Packed format is designed for use on bandwidth-constrained networks. When communicating between processes on the same machine, Packed format will perform strictly worse than unpacked.)

3. Use KJ's non-blocking I/O framework. KJ features an entire event loop infrastructure designed specifically to handle non-blocking I/O. See `kj/async.h`, `kj/async-io.h`, and `capnp/serialize-async.h`. However, this approach requires adopting KJ as your event loop which may be problematic if you are already using some other event loop.
