### ISSUE TITLE
How can capnproto support utf-8 characters as field name and struct name?

### ISSUE THREAD

**Issue by yes7rose** [capnproto/capnproto#1067]
Some

```capnp
struct Person {
  name @0 :Text; 
  birthdate @3 :Date;
}
```
To

```capnp
struct 人 {
  姓名 @0 :Text; 
  生日 @3 :Date;
}
```

What can I do to support it？

**Comment by kentonv** [comment]
At present, Cap'n Proto only allows ASCII characters in identifiers.

I'm not necessarily opposed to changing that, but it is complicated.

Deciding what characters to allow and how to handle them can be very involved. Take a look at [Rust's effort](https://github.com/rust-lang/rust/issues/55467) for an example of how complicated this can be. Unfortunately, the core maintainers of Cap'n Proto just don't have time to work on this, but if someone wants to volunteer I'm happy to review.

The problem is actually even more complicated for Cap'n Proto, because code generators need to figure out how to render these identifiers in each target language. Not all languages support Unicode identifiers, and those that do may have varying rules and varying idioms. Code generators today already struggle a bit with re-rendering field names from camelCase to snake_case and such -- dealing with Unicode will be 10x harder.

But again, if someone had a good proposal for how to do this and wants to put in the work, I'm totally happy to entertain it.
