### ISSUE TITLE
Surprising treatment of generics in 'capnp convert'

### ISSUE THREAD

**Issue by sconybeare** [capnproto/capnproto#1075]
Consider the following schema:
```capnp
# schema.capnp
@0xdb9001ded518f437;
struct GenericWrapper(T) {
  tag @0 :UInt64;
  body @1 :T;
}
struct Inner @0xf0967ddb6eb83ead {
  x @0 :Text;
}
using Foo = GenericWrapper(Inner);

const myConst :Foo = (tag = 0xf0967ddb6eb83ead, body = (x = "some text"));
```

It seems like the `capnp convert` command treats `Foo` equivalently to `GenericWrapper(AnyPointer)`, which leads to the following surprising errors when converting:

```
$ capnp eval schema.capnp myConst | capnp convert text:binary schema.capnp Foo
*** Uncaught exception ***
capnp/serialize-text.c++:38: failed: kj::str(message, " (", startByte, ":", endByte, ").") = Type mismatch; expected AnyPointer. (39:56).
```

```
$ capnp eval schema.capnp myConst -b | capnp convert binary:json schema.capnp Foo
*** Uncaught exception ***
capnp/compat/json.c++:359: failed: don't know how to JSON-encode AnyPointer; please register a JsonCodec::Handler for this
```

There's also this non-error, which still discards information in a surprising way.
```
$ capnp eval schema.capnp myConst -b | capnp convert binary:text schema.capnp Foo
( tag = 17336182197018181293,
  body = <opaque pointer> )
```

**Comment by kentonv** [comment]
I did a little digging on this and, indeed, it is broken. The basic problem is that `capnp convert` interprets the type name passed on the command line by splitting it on `.` and then calling `Compiler::lookup()` for each identifier in the chain. `lookup()` is defined as:

https://github.com/capnproto/capnproto/blob/a6848badf513461f5f70b2938722f39d2e6a63ca/c++/src/capnp/compiler/compiler.h#L86-L89

Since this function purely identifies types by type ID, it can only understand their generic form, not branded forms (in which one or more type parameters have been bound). It's unclear if this is by design. A comment in the implementation suggests this function wasn't intended to be able to follow aliases, in which case it would never be able to reach a branded type anyway. But by accident, it does manage to follow aliases, and we probably should preserve that.

For `capnp eval` and other CLI tools, it probably makes sense to replace `lookup()` with a completely different interface that evaluates an arbitrary type expression within the scope of a file. This way, you could actually specify generic type parameters directly on the command line, and not have to define aliases.

There is one other place where `lookup()` is used: inside `schema-parser.c++`. Here, it is implementing the `SchemaParser::getNested(name)` interface, which is typically used by e.g. the Python bindings to traverse the type tree. This use case is _not_ well served by a new interface that evaluates arbitrary type expressions; it really does need to interpret one segment of the type path at a time. So it seems like we need some other solution here. Probably we need to extend `Compiler` with a more general way to traverse the declaration tree.

This looks like it needs some refactoring to do right, and this is very brain-bendy code. I'd like to fix this before 1.0 but not sure exactly how soon I'll get to it.
