### ISSUE TITLE
CAPNP_ALLOW_UNALIGNED not working

### ISSUE THREAD

**Issue by blackliner** [capnproto/capnproto#1150]
How should the flag `CAPNP_ALLOW_UNALIGNED` end up [HERE](https://github.com/capnproto/capnproto/blob/8392fb6a8ef54132424a2ea6e7d0df8d17715336/c%2B%2B/src/capnp/arena.c%2B%2B#L75) ?

I tried passing it to to the `cmake .. -DCAPNP_ALLOW_UNALIGNED=ON/True/true/TRUE/1/whatever`, but I do not see any part of cmake that uses it to create a flag, similar to how [CAPNP_LITE](https://github.com/capnproto/capnproto/blob/8392fb6a8ef54132424a2ea6e7d0df8d17715336/c%2B%2B/CMakeLists.txt#L37-L42) is handled.

**Comment by kentonv** [comment]
Hi @blackliner,

This flag is obsolete and we should remove it. Unfortunately, it turns out unaligned reads and undefined behavior in C++. If you use unaligned reads/writes in C++, your program may crash or subtly corrupt data. This is true even on x86/x64. Some x86 instructions (especially SIMD) require alignment, and the compiler can and will use those instructions in optimizations. Also, the compiler can assume the lower bits of a pointer are zero and can optimize arithmetic in a way that discards them.

See #977 where we removed most support for unaligned access. I forgot about the `CAPNP_ALLOW_UNALIGNED` preprocessor flag at that time; it should be removed too.

Unfortunately, if your data is not aligned, you will have to copy it into an aligned buffer.

**Comment by blackliner** [comment]
Thanks, yes I read all the warning messages on the console 🙂 
The point is, we are currently using 0.7.0 with unaligned messages and want to upgrade 0.8.0 without having to modify all code. So we are already using the unsafe mode, which is why it should not make any difference, right?

**Comment by kentonv** [comment]
Ah yes, sorry, I forgot that all that explanation was part of the error message.

I don't personally know how cmake works, but with autotools you would do `./configure CXXFLAGS='-O2 -DCAPNP_ALLOW_UNALIGNED'`. I guess you have to figure out the equivalent way to define extra compiler flags for cmake?

Maybe @harrishancock knows.

**Comment by blackliner** [comment]
This is a howto add definitions in CMake https://stackoverflow.com/questions/7900661/how-to-read-a-cmake-variable-in-c-source-code

But as I said in my OP, you already do that for `CAPNP_LITE`: https://github.com/capnproto/capnproto/blob/8392fb6a8ef54132424a2ea6e7d0df8d17715336/c%2B%2B/CMakeLists.txt#L37-L42 (via a CMake template file)

**Comment by harrishancock** [comment]
You should be able to set it on the command line with something like this:
```
cmake <other stuff> -DCMAKE_CXX_FLAGS=-DCAPNP_ALLOW_UNALIGNED
```
I think setting it via the CXXFLAGS environment variable would also work (`CXXFLAGS=-DCAPNP_ALLOW_UNALIGNED cmake <other stuff>`), but it's been a while since I tried that.
