### ISSUE TITLE
Generate .so files from CMake AND make build without test_capnpc_middleman

### ISSUE THREAD

**Issue by sarenameas** [capnproto/capnproto#1156]
For version 0.7.0 what commands do I pass to cmake to generate .so files instead of .a files?

A second question, I am compiling this library in my Yocto project, so it is targeted to a different architecture than the native curent build one. How can I invoke make without ./capnp: line 117: trying to execute a binary that is not the same the architecture as the current build environment? Basically I just want to build the shared objects without the capnp script being invoked in this target:  *test_capnpc_middleman*.

**Comment by kentonv** [comment]
Hi @sarenameas,

Please note the autotools build is the official and recommended build system for Cap'n Proto. The cmake build is maintained unofficially by contributors outside the core project.

The autotools build will produce shared libraries by default. The autotools build also supports cross-compiling by passing the `--with-external-capnp` flag to `./configure` -- this will cause the rules that invoke `capnp` to use the version installed on the host, rather than the one built in-tree.

We don't know how to make cmake build shared libraries, or how to use it for cross compiling. You will probably have to dig into it and figure it out yourself. If changes are needed to the cmake files to make it work, we're happy to accept a PR.

**Comment by harrishancock** [comment]
`cmake <other flags> -DBUILD_SHARED_LIBS=ON` is the standard way to do this. I just tested, and it still works (at least, it produces .so files, and tests pass).

However, you might want to read this warning from the past before distributing any such artifacts: https://github.com/capnproto/capnproto/pull/314#issuecomment-210684584:

> ... a binary linked with CMake-produced shared libraries won't run on a system with automake-produced shared libraries (IIRC)

**Comment by sarenameas** [comment]
Thank you
