### ISSUE TITLE
Serialization of KJ::HashMap

### ISSUE THREAD

**Issue by wjc404** [capnproto/capnproto#1160]
Is there an efficient way to serialize kj::HashMap? I can't find Reader or Builder method for this type. Thanks.

**Comment by kentonv** [comment]
No, kj::HashMap is not designed to be serialized.

Note that KJ is just a C++ toolkit library. It doesn't know anything about serialization. Cap'n Proto's C++ implementation is built on KJ, and they share the same git repo, because they were developed together. But serialization is strictly the domain of Cap'n Proto and not KJ. At present, Cap'n Proto does not have any built-in support for serializing maps.
