### ISSUE TITLE
Is send() guaranteed to send the request regardless of the returned promise?

### ISSUE THREAD

**Issue by zhehangd** [capnproto/capnproto#1218]
Say I have three interfaces

```capnp
interface Listener {
  receiveEvent @0 (event: Event) -> ()
}

interface Controller {
  logOut @0 () -> ()
}

interface Authorization {
  logIn @0 (listener: Listener) -> (control: Controller)
}
```
So an Authorization client may log in to a server with its own Listener interface.
Server returns a controller interface to the client to support logout and other actions, and will keep sending events to the client via the listener.

So I would write 
```c++
kj::Promise<void> AuthorizationImpl::login(LoginContext ctx) {
  
  auto viewer = ctx.getParams().getViewer()
  AddUser(viewer);

  auto results = ctx.getResults();
  results.setTerminal(GetTerminalClient());
  
  // Do here and other places, many times
  auto request = viewer.receiveEventRequest();
  SetEvent(request);
  request.send();

  return kj::READY_NOW;
}
```

Here in `request.send()` I didn't take and wait for the returned promise, since
1. I don't need any return value.
2. I don't want to block the execution.

By writing so I got an `Ignoring return value of function declared with 'warn_unused_result' attribute` warning. 

Does that mean I should always catch and wait the returned promise in order to have the request sent,
or mean the request will be sent **anyway** but I should still wait for the promise to be fulfilled (maybe just for handling error)?

If this is a must-do I suppose I could add it to a `kj::TaskSet` to avoid blocking.

Besides this I got a few other small questions and would be grateful if they are answered too.
2. Is this the expected way to realize a bidirectional communication like an online game?
3. If the sizes of events are pretty small, does it make sense to accumulate the events and send in batch? 
4. Does the client receive events in the same order as they are sent (the order of the send() calls)?
 
BTW, I used to use gRPC and now I am amazed by capnp's object-oriented style.
It is pity that capnp does not get enough attention as it deserves.

**Comment by kentonv** [comment]
If you destroy the returned promise, the request is canceled. If it hasn't been sent already, it won't be sent at all. If it has been sent, then a cancellation request will be sent.

In a distributed system, there is really no such thing as a reliable one-way message. If you send a message but ignore the result -- including ignoring errors -- then there's no way to know if the message was really delivered and processed by the recipient. Hence, Cap'n Proto strongly discourages people from ignoring results.

That said, your specific use case might fall under Cap'n Proto's streaming feature. See: https://capnproto.org/news/2020-04-23-capnproto-0.8.html

That is, you could define `Listener` like so:

```capnp
interface Listener {
  receiveEvent @0 (event: Event) -> stream;
  end @1 ();
}
```

When you call `send()` on a streaming method, then throwing away the returned promise does _not_ cancel the call. In fact, the returned promise doesn't represent the result of the call at all -- it's only a promise that resolves as soon as it's a good time to make a new call. This provides backpressure, so that you can stop yourself from sending more messages than the connection bandwidth can handle.

When using streaming, though, it is important that _after_ all streaming calls, you make at least one non-streaming call on the same object. Above, I defined `end()` for this purpose. The `end()` call checks for errors; if any previous stream call was not actually delivered or processed by the remote end, then `end()` will fail.

-------

A separate, somewhat-related tip regarding `Controller`: Instead of declaring a `logout()` method which the client must explicitly call, consider automatically logging out the client when `Controller`'s destructor is invoked. This will happen as soon as the client drops its reference to the controller, or when the client disconnects. This way, the client doesn't have to bother calling `logout()`, and there's no possibility that the logout will be missed by accident. You could argue that this is a kind of one-way message, but it is "reliable" in that the message gets delivered automatically if anything goes wrong.

-------

> Is this the expected way to realize a bidirectional communication like an online game?

That's a very open question as there are lots of possible designs depending on the details of the communication you want to achieve. But basically, yes.

> If the sizes of events are pretty small, does it make sense to accumulate the events and send in batch?

There's not any overwhelming reason to do so, but it could make sense. There's always some constant overhead involved in making any call, so reducing the number of calls reduces that overhead. You'll have to benchmark your particular system to see if the difference is meaningful.

> Does the client receive events in the same order as they are sent (the order of the send() calls)?

Yes it does! Specifically, calls are delivered in order, but they don't block each other. So if a method implementation performs some asynchronous tasks (using promises), the next call could be delivered before the first one finishes. But, initial delivery will be in order, if they came from the same sender. This guarantee is called E-order, as it was first formalized in the E programming language.

**Comment by zhehangd** [comment]
Thanks for the explanations! It's very helpful.
I have one more question about the destruction of `Controller`.
Does the "disconnection" includes a `Controller` being quite for too long (meanwhile client still receives events from the corresponding `Listener`)?

I know in gRPC if a client makes a call that takes a few minutes to complete, the client can freeze forever even after the server finishes the call. The solution is to ping the server regularly to keep the connection alive. I wonder if I need to do the same for capnp when I make a call that takes a long time to return or when I use an interface only occasionally.

**Comment by kentonv** [comment]
> Does the "disconnection" includes a Controller being quite for too long (meanwhile client still receives events from the corresponding Listener)?

It means a network disconnect. These two capabilities will be sharing the same network connection, so a disconnect would break both at the same time.

> I know in gRPC if a client makes a call that takes a few minutes to complete, the client can freeze forever even after the server finishes the call. The solution is to ping the server regularly to keep the connection alive. I wonder if I need to do the same for capnp when I make a call that takes a long time to return or when I use an interface only occasionally.

If you aren't sending any traffic on the network connection at all, then it can indeed suffer this fate, as this is a general problem with TCP. However, it would simultaneously affect all capabilities on the connection.

When doing Cap'n Proto over TCP, you will want to have some mechanism for forcefully aborting connections that have timed out, so that they don't hang forever. One way could be to set the socket options so that the OS does it automatically, another way might be to inject your own layer over `kj::AsyncIoStream` and `kj::Network` that does some sort of timeout logic. Nothing in particular is built into Cap'n Proto for this at present, as it's [a pretty hairy subject](https://blog.cloudflare.com/when-tcp-sockets-refuse-to-die/).

And yes, I do also recommend that if you're not already sending regular traffic over the connection, then you introduce some sort of `ping()` method that you can call periodically to keep the connection live.

**Comment by zhehangd** [comment]
Awesome. It is now pretty clear to me.
Thanks again for the help!　(๑•̀ㅂ•́)و✧
