### ISSUE TITLE
Unused data tables generated in CAPNP_LITE mode?

### ISSUE THREAD

**Issue by nyanpasu64** [capnproto/capnproto#1223]
Possibly related to #634.

I'm running Cap'n Proto 0.8.0 with the compiler supplied by Arch Linux. Its C++ code generator produces static `AlignedData` variables in the .c++ file named `b_hex...` which are never read in CAPNP_LITE mode, except to define a non-static pointer named `bp_hex...` which is neither read nor exposed in the header file (whether CAPNP_LITE is defined or not). Am I correct that these data tables aren't used in lite mode, and could they be moved into the `#if !CAPNP_LITE` block to ifdef them out in CAPNP_LITE mode?

I'm not actually sure how much space these tables take up, and whether it's a significant space savings. But I think it's worth it to avoid generating dead code that gets compiled anyway.

**Comment by kentonv** [comment]
They are actually exposed via [schema-lite.h](https://github.com/capnproto/capnproto/blob/master/c++/src/capnp/schema-lite.h).

Going back to [the original lite mode commit message](https://github.com/capnproto/capnproto/commit/c772a70096b31061051b39e180ea807f82f6e024), I apparently wrote:

> - Schemas are actually still available in lite mode, though only in their raw (Cap'n Proto structure) form. Only the schema API (which wraps the raw schemas in a more convenient interface) and reflection API (which offers a convenient way to use the schemas) are unavailable.

So this does appear to be intentional, though it's so long ago I don't remember my exact reasoning.

Lite mode in Cap'n Proto was not actually created to minimize code footprint, but rather to create a subset of capnp that could be compiled using MSVC of the time. MSVC has improved since then and is now able to compile all of capnp, so lite mode is sort of obsolete now.

If you are looking for a way to minimize your code footprint, I recommend telling the compiler to drop unused symbols. You can do this by passing `-ffunction-sections -fdata-sections` to the compiler (to tell it to emit each symbol as a separate section), then pass `-Wl,--gc-sections` to the linker. This should be pretty effective at removing capnp's schema and dynamic API -- as long as you don't actually use them anywhere (e.g. you do not ever try to stringify a struct).
