### ISSUE TITLE
kj::HttpService: provide an easy way to add extra headers to all requests.

### ISSUE THREAD

**Issue by zenhack** [capnproto/capnproto#1260]
Context: https://github.com/sandstorm-io/sandstorm/issues/3517

It would be useful to be able to add additional headers to all responses from an HttpService. Right now there's no obvious (to me) simple way to do this via the kj http interfaces. One possible interface for this would be a function like:

```c++
Own<HttpService> withExtraHeaders(Own<HttpService>&& service, const HttpHeaders& headers);
```

Thoughts?

**Comment by zenhack** [comment]
(Vaguely related observation: skmming the implementation it seems like the use of `const HttpHeaders&` is the source of a lot of excess copying that could likely be avoided by accepting arguments by move).

**Comment by kentonv** [comment]
`HttpHeaders` is allowed to point into buffers it doesn't own -- such as the original buffer used to read the headers out of the socket, or by using `cloneShallow()`. That wouldn't work well for headers passed by move, since the lifetimes would become extremely unclear, and so then we'd end up having to copy all the strings so that the `HttpHeaders` object could own them all. So, as it turns out, passing by const reference actually helps avoid copies here, though it's definitely unintuitive.

It should be straightforward to implement an HttpService wrapper that injects headers on responses. The implementation of `Response::send()` would `cloneShallow()` the headers, then use the `set()` overload that takes a `StringPtr`. I think the whole thing should involve only one memory allocation in the common case (to allocate a new header array). So I think this is probably not worth baking into the HttpServer implementation.

FWIW this is a pretty common pattern in e.g. the Cloudflare Workers codebase.

**Comment by kentonv** [comment]
Oh, I suppose you are in fact suggesting we implement exactly this HttpService wrapper, but make it part of the library so that it is reusable.

The thing is, I think a lot of cases are slightly different, like one case might just always add the same headers, while other cases need to set a header somewhat dynamically. So I'm not sure the specific utility you propose would actually be widely used. Meanwhile, it's not too hard for the app to write such a wrapper that does exactly what they want. So I think probably the code you want for this use case should just live in Sandstorm, though I'm open to being proven wrong in the future if we see this exact thing come up repeatedly.

**Comment by zenhack** [comment]
Closing.
