### ISSUE TITLE
Can't add custom args/options to work with my compiler

### ISSUE THREAD

**Issue by robthemonster** [capnproto/capnproto#1291]
Hi!
     I am trying to use the CapnProto C++ libraries to write my own compiler (similar to how https://github.com/capnproto/capnproto-java works). As part of this compiler, I would like to require an argument. It seems like the MainBuilder class has APIs to support this usecase, but I can't seem to figure out how it is supposed to work.

```
 kj::MainFunc getMain()
    {
        kj::MainBuilder builder(context, "CapnProto compiler");
        builder.expectArg( "configFilepath", KJ_BIND_METHOD(*this, setConfigFilePath))
            .callAfterParsing(KJ_BIND_METHOD(*this, run));
        return builder.build();
    }

    kj::MainBuilder::Validity setConfigFilePath(kj::StringPtr configFilePath)
    {
        this->configFilePath = configFilePath;
        return true;
    }
```
So far I have been hardcoding the config file path, and the compiler works fine. Adding this `expectArg` call yields this error

```
> capnp compile --output=language file1.capnp file2.capnp
capnpc-language: missing argument configFilePath
```

This is expected, but when I try to provide the configFilePath

```
> capnp compile --output=language file1.capnp file2.capnp path/to/file.config
path/to/file.config:37:1 error: Parse error
```
To some degree this error makes sense; It's trying to parse the file as a capnp schema file. However, supplying the arg _before_ the list of capnp files doesn't work either. 

I also tried .addOptionWithValue, but then I just get "unrecognized option" when I try to supply it.

It seems like these API calls aren't doing anything; The options and arguments to `capnp compile` have already been set here https://github.com/capnproto/capnproto/blob/master/c%2B%2B/src/capnp/compiler/capnp.c%2B%2B#L297-L314. Is there any way for me to add new options/args that I can supply on the command line when I invoke my compiler?

**Comment by kentonv** [comment]
The problem here is that the `capnp` binary does not support passing any options down from its own command line to your plugin's command line.

I think your options for solving this include:
* Use an environment variable instead.
* Embed configuration directly into the `.capnp` files using annotations.
* Create a small wrapper -- a shell script, perhaps -- around your plugin binary, which adds the appropriate flags, and have capnp invoke that. (Each project using the plugin could supply its own wrapper to apply its own configuration.)
* Propose a syntax for specifying flags to `capnp compile` that should be passed on to the underlying code generator plugin. We'll want to study the use case a bit to make sure it is really needed. Then you'd need to submit a PR to implement it.

**Comment by robthemonster** [comment]
Thanks! I'll think on the syntax and use cases.

> Create a small wrapper -- a shell script, perhaps -- around your plugin binary, which adds the appropriate flags, and have capnp invoke that. (Each project using the plugin could supply its own wrapper to apply its own configuration.)

When you say "have the script add appropriate flags", do you mean via env variable?

**Comment by kentonv** [comment]
I mean that you can write a shell script like:

```
#! /bin/sh
exec my-plugin --some-extra-flag "$@"
```

And then you can tell `capnp compile` to use that shell script as the plugin.

```
capnp compile -o./my-plugin-wrapper.sh myschema.capnp
```

No environment variables needed.

**Comment by robthemonster** [comment]
Got it; Thanks for your help. Feel free to close this as I think the workaround are sufficient. If I can come up with usecases/syntax I'll open an explicit feature request.

**Comment by kentonv** [comment]
Great, glad that works.
