### ISSUE TITLE
0.9.0: GNU autotools and cmake are producing different libraries

### ISSUE THREAD

**Issue by kloczek** [capnproto/capnproto#1324]
GNU tooling produes lib<foo>-0.9.0.so and cmake lib<foo>.so.0.9.0.
capnproto 0.8.0 with GNU autotools have been building  lib<foo>.so.0.8.0 do looks like sometning is wrong in 0.9.0.

**Comment by kentonv** [comment]
The autotools build has always produced `libcapnp-0.x.y.so`. This is intentional because we do not provide ABI compatibility between releases. This happens because of the use of [libtool's `-release` flag](https://www.gnu.org/software/libtool/manual/html_node/Release-numbers.html), which dates all the way back to 451223a36d92ed6ac8b18663e2199a5b78a0bcfc which is where dynamic linking was first enabled.

Here's the current use of the flag:

https://github.com/capnproto/capnproto/blob/37967181192212c7586337d569f359556da7b37f/c%2B%2B/Makefile.am#L336

The cmake build is not officially supported. It appears the cmake build incorrectly builds `libcapnp.so.0.x.y`, and similarly sets the soname to this value. This at least seems to mean that different versions will have different sonames, which I believe works around the ABI compatibility issue. However, it is not consistent with the autotools build, which uses `libcapnp-0.x.y.so` as the soname. This is a bug in the cmake build.

Neither of these builds has changed behavior since 0.8.0. I've verified that they both do exactly the same thing in 0.9.0 as they did in 0.8.0.

I've opened #1327 for the specific soname issue.
