### ISSUE TITLE
MSVC: data corruption when returning string

### ISSUE THREAD

**Issue by tiagogehring** [capnproto/capnproto#1333]
When I compile my code with MSVC (v19.29 in x64 mode) and return a string from my server to the client the data gets corrupted (but the application doesn't crash). The code works as expected when compiled in Linux.

Server:

```c++
kj::Promise<void> getString(GetStringContext context) override 
{
     context.getResults().setString("Pink Floyd");
     return kj::READY_NOW;
}
```

Client:

```c++
auto request = myobj.getStringRequest();
auto response = request.send().wait(waitScope).getString();
std::cout << "Response: " << response.cStr(); 
```

// output: "Response: ¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦¦"

**Comment by kentonv** [comment]
The problem is this line:

```
auto response = request.send().wait(waitScope).getString();
```

You need to change it to:

```
auto responseObject = request.send().wait(waitScope);
auto response = repsonseObject.getString();
```

The problem is that `getString()` returns a pointer that points into the responses backing buffer. But, since you didn't store the response object anymore, it gets destroyed at the end of the line of code. So on the next line, the string is pointing to free'd memory, and therefore may be corrupted. This is true on all platforms, including Linux.

**Comment by tiagogehring** [comment]
Thank you, Kenton. And sorry for opening an issue for something that was just a misunderstanding from my part. It works fine now.
