### ISSUE TITLE
[ FAIL ] kj/async-io-test.c++:307: legacy test: AsyncIo/AncillaryMessageHandler (854 μs)

### ISSUE THREAD

**Issue by vt-alt** [capnproto/capnproto#1349]
When building capnproto v0.9.1 for the package for ALT Linux we got such `make check` error:
```
[ TEST ] kj/async-io-test.c++:307: legacy test: AsyncIo/AncillaryMessageHandler
kj/async-io-test.c++:364: failed: expected serverHandlerCalled
stack: 55b5b64c4bfd 55b5b627b2f9 7fcd39c0950d 7fcd39bbc4d9 7fcd39c09a7c 7fcd39c0a2b1 7fcd39bdea4d 7fcd39bbc4d
9 7fcd39bd7f91 7fcd39c087b0 7fcd39708e2c 55b5b60ba0c9
[ FAIL ] kj/async-io-test.c++:307: legacy test: AsyncIo/AncillaryMessageHandler (854 μs)
...
907 test(s) passed 
1 test(s) failed 
FAIL: capnp-test
Randomly testing backwards-compatibility scenarios with seed: 1633094793
PASS: capnp-evolution-test
PASS: src/capnp/compiler/capnp-test.sh
===========================================
1 of 3 tests failed
```
Please ask if you need any additional info.

**Comment by kentonv** [comment]
That's odd. What kernel version?

**Comment by vt-alt** [comment]
Tested on 4.9.56.

**Comment by kentonv** [comment]
I'm not sure what to say here. Seems like your kernel is behaving unusually. You can safely ignore the test failure as this particular functionality isn't really used by Cap'n Proto itself.

**Comment by kentonv** [comment]
Sorry, the stack trace probably doesn't help me (even if I could decode it). This probably needs to be debugged directly on a system exhibiting the problem.

Do you have the ability to float patches on your packages? If so I'd suggest adding `#if 0` around this test case. Otherwise, I'd accept a PR which adds something like `#if KJ_SKIP_CMSG_HANDLER_TEST` around that test, and then you can add that to your cflags when you build...

**Comment by vt-alt** [comment]
Thanks for explanations!
