### ISSUE TITLE
Cross build fails

### ISSUE THREAD

**Issue by buffstop** [capnproto/capnproto#1384]
I am trying to cross build capnproto for ARM64 to build a fat lib for macOS (x86_64 and "Apple Silicon") using this script on an Intel mac, using Xcode command line tools (a common pattern we are using successfully for tons of libs):

```
HOST="aarch64-apple-darwin"
ARCH="arm64"
PREFIX=~/somwhere/
# Note: Yes, PREFIX dir exists
SDK="macosx"
SDK_PATH=`xcrun -sdk ${SDK} --show-sdk-path`

export LDFLAGS="-arch ${ARCH}"
export CC="$(xcrun --sdk ${SDK} -f clang) -arch ${ARCH} -isysroot ${SDK_PATH}"
export CXX="$(xcrun --sdk ${SDK} -f clang++) -arch ${ARCH} -isysroot ${SDK_PATH}"

autoreconf -i
./configure --host=${HOST} --prefix=${PREFIX} --enable-static=yes --enable-shared=no
make clean
make -j6
make install
```
This fails in the end with this error: 

```
 make: *** [test_capnpc_middleman] Error 126

./capnp: Bad CPU type in executable
```
The archives / libs build so far are arm64 corretly:

```
$lipo -info tmp/capnproto/c++/.libs/*.a

Non-fat file: tmp/capnproto/c++/.libs/libcapnp-json.a is architecture: arm64

Non-fat file: tmp/capnproto/c++/.libs/libcapnp.a is architecture: arm64

Non-fat file: tmp/capnproto/c++/.libs/libcapnpc.a is architecture: arm64

Non-fat file: tmp/capnproto/c++/.libs/libkj.a is architecture: arm64
```
How I understand the error "Bad CPU type in executable", something build for x86_64 is used.

Can I somehow suppress making tests like `test_capnpc_middleman`?

**Comment by kentonv** [comment]
The build is attempting to use the `capnp` binary that it just compiled in order to generate some capnp code. It sounds like you are cross-compiling to a target architecture which the host doesn't support, hence the binary can't be executed.

The right way to handle this is to install `capnp` on the host system first, then use the `--with-external-capnp` option to `configure`. It will then use the host's binary rather than the self-built one. (You can use binaries that aren't actually installed by specifying their locations using the `CAPNP` and `CAPNPC_CXX` environment variables, to specify the paths of the `capnp` and `capnpc-c++` binaries, respectively.)

**Comment by buffstop** [comment]
Thank you. Totally makes sense.
