### ISSUE TITLE
Why do Type IDs have the top bit set?

### ISSUE THREAD

**Issue by englercj** [capnproto/capnproto#1392]
The documentation mentions that Type IDs always have the MSB set. I see in the code where this is set, but I don't see it checked very often except to give an error when it is not set.

What is the intention of having this invariant for IDs?

**Comment by kentonv** [comment]
This is just to make sure you can't accidentally use a small integer as a type ID, and make it significantly less likely that someone will use a non-random type ID.

Since the `@` symbol is used both to specify type IDs (on type declarations) and to specify field numbers, it's not hard to imagine someone mixing them up and, say, trying to specify `@2` on a nested type declaration. We want that to be an error, rather than causing the type to receive a type ID of 2.

It's also nice that printing a valid type ID in hex always results in exactly 16 digits -- no need to worry about padding with zeros.

**Comment by englercj** [comment]
That makes perfect sense, thanks for taking the time to explain the reasoning here.
