### ISSUE TITLE
window-sanity.h still appears inccorect

### ISSUE THREAD

**Issue by dhoke4tdb** [capnproto/capnproto#1421]
does not define ERROR at all if not previously seen, but code will still try to reference the win32::ERROR entity.
(https://github.com/capnproto/capnproto/blob/55a368beb987abf9eeb9b3843e9c5423ad37ab29/c%2B%2B/src/kj/windows-sanity.h#L52-L56)

Perhaps applying a patch similar to following would be an improvement:
```
diff --git a/c++/src/kj/windows-sanity.h b/c++/src/kj/windows-sanity.h
index 894ec1d7..f18b39e6 100644
--- a/c++/src/kj/windows-sanity.h
+++ b/c++/src/kj/windows-sanity.h
@@ -49,9 +49,13 @@
 #pragma once
 
 namespace win32 {
+#ifdef ERROR  // This could be absent if e.g. NOGDI was used.
   const auto ERROR_ = ERROR;
 #undef ERROR
   const auto ERROR = ERROR_;
+#else //if macro def missing, we still need to define the symbol.
+  const auto ERROR = 0;
+#endif
 
   typedef VOID VOID_;
 #undef VOID
```

**Comment by kentonv** [comment]
No, this is as intended. In order to use `ERROR`, you have to include the win32 header that defines it.

There are three possibilities:

1. You include the win32 header before including KJ headers. In this case we need to convert the macro into a constant so that the KJ headers parse correctly.
2. You include the win32 header _after_ including the KJ headers. In this case we don't need to do anything as the KJ headers have already parsed.
3. You don't include the win32 header at all. In this case, `ERROR` should remain undefined, since the header wasn't included.

Note that code should not be referencing `win32::ERROR` directly. The idea here is that we use `using namespace win32` so that `ERROR` becomes visible in the global scope (unless it would conflict with some other declaration, in which case we don't want to mess with that). Applications should still reference just `ERROR`.

**Comment by dhoke4tdb** [comment]
You seem to be making the assumption that we have control over the inclusion of windows.h, but this is not the case.

Please consider the following, relative to your enumerated options...

1) We don't include windows.h.  Library code we are using does (curl).
2) Irrelevant, we don't include windows.h, see (1).
3) We -don't- include windows.h in our code, see (1).

And, it is not our code, but kj/windows-sanity.h itself, that is referencing the win32::ERROR, via the 
using win32::ERROR;
when 'ERROR' was not defined when windows.h (as is apparently the case with curl's use of it.)

When the #else portion of the patch above is inactive (commented out the direct def of ERROR in #else branch), 
the version of visual studio 2019 I used complains:
```
D:\dev\tiledb\gh.tdb.pristine.20220127.git\bld.rwdi.vs19.F\externals\install\include\kj/windows-sanity.h(65): error C2039: 'ERROR': is not a member of 'win32'
D:\dev\tiledb\gh.tdb.pristine.20220127.git\bld.rwdi.vs19.F\externals\install\include\kj/windows-sanity.h(51): note: see declaration of 'win32'
D:\dev\tiledb\gh.tdb.pristine.20220127.git\bld.rwdi.vs19.F\externals\install\include\kj/windows-sanity.h(65): error C2873: 'ERROR': symbol cannot be used in a using-declaration
```

**Comment by kentonv** [comment]
Hi @dhoke4tdb,

It appears the bug you are reporting is that `windows-sanity.h` itself references `win32::ERROR` on line 63, when it says `using win32::ERROR;`. That is indeed a bug, that line also needs to be conditional on whether ERROR was defined.

Sorry, the way you reported the bug was not very clear as it din't mention that the erroneous code referencing `win32::ERROR` was in the same file.
