### ISSUE TITLE
Instructions to build benchmarks

### ISSUE THREAD

**Issue by rileylyman** [capnproto/capnproto#1457]
Are there any instructions anywhere on how to build/run benchmarks? If not, can someone briefly explain what I need to do?

**Comment by kentonv** [comment]
To be honest, I don't think I've touched these since 2013.

They were originally built using [ekam](https://github.com/capnproto/ekam). Once upon a time I had Ekam working well to build not just Cap'n Proto but also Protobuf at the same time. It should still build Cap'n Proto well, but the ability to build Protobuf has likely rotted. Your best bet would be to create a new Makefile for them, probably.

**Comment by mbehm** [comment]
I'm glad about your honesty, I'd also be glad if I wasn't mislead by statements like "In fact, in benchmarks, Cap’n Proto is INFINITY TIMES faster than Protocol Buffers." to search for said benchmarks, only to find out the last time you've done any sort of actual benchmarking on the project is a decade ago.

**Comment by rileylyman** [comment]
> I'm glad about your honesty, I'd also be glad if I wasn't mislead by statements like "In fact, in benchmarks, Cap’n Proto is INFINITY TIMES faster than Protocol Buffers." to search for said benchmarks, only to find out the last time you've done any sort of actual benchmarking on the project is a decade ago.

Either you're joking, or you need to think harder about what that quotation means.

**Comment by kentonv** [comment]
@mbehm I have to agree with @rileylyman, it sounds like the whole thing went right over your head. :shrug:
