### ISSUE TITLE
Unimplemented: getcontext(context): Function not implemented

### ISSUE THREAD

**Issue by JonasVautherin** [capnproto/capnproto#1464]
I realized in https://github.com/capnproto/capnproto/pull/1460 that one of the manylinux CI tests fails with [the following error](https://github.com/capnproto/capnproto/runs/6564241356?check_suite_focus=true):

```
[ TEST ] kj/async-test.c++:1066: cancel a fiber
kj/async.c++:1366: unimplemented: getcontext(context): Function not implemented
```

However, [the test for `makecontext`](https://github.com/capnproto/capnproto/runs/6564241356?check_suite_focus=true#step:4:253) seems to find it:

```
checking for library containing makecontext... none required
```

Just to be sure, I tried to replace `makecontext` with `getcontext` [here](https://github.com/JonasVautherin/capnproto/runs/6564083277?check_suite_focus=true#step:4:253), and it fails with the same errors.

Any idea why it works for all the other tests (including another manylinux dockcross image) and not for this one, given that autoconf apparently finds `makecontext`/`getcontext` in glibc?

Just trying to fix the CI test :innocent:.

**Comment by kentonv** [comment]
It seems like this platform has a libc that implements `getcontext()` such that it always fails with `ENOSYS`, despite the fact that `getcontext()` is not a system call and the man page lists no possible errors. Ugh.

In order to detect this problem in the configure script, we'd have to actually try calling the function to see if it works. But when cross-compiling, that may not be possible. What a pain.

Maybe the test itself can try calling getcontext() and, if it fails like this, can skip running the tests.
