### ISSUE TITLE
Cap'n Proto in Windows Kernel space

### ISSUE THREAD

**Issue by old-pigeon** [capnproto/capnproto#1472]
Do you think that Cap'n Proto would compile for Windows kernel drivers?

There are some limitations, i. e. not using exceptions. Is there anything inside Cap'n Proto speaking against this? I only plan to use the message packing stuff, so no communication/server stuff.

**Comment by kentonv** [comment]
I don't have any experience with Windows kernel drivers so I can't speak directly to that.

Cap'n Proto is designed to be possible to compile and use with exceptions disabled. However, this configuration isn't well-tested on MSVC; our CI tests only test `-fno-exceptions` on Linux and Mac. So, there may be some minor issues that need to be resolved to make it work, but it should be possible.

Note that no-exceptions mode can be awkward. You will want to familiarize yourself with `kj::ExceptionCallback`, which can be used to control what happens when an exception would normally be thrown.

See also: [The style guide on KJ exceptions](https://github.com/capnproto/capnproto/blob/master/style-guide.md#exceptions), especially [Allowing -fno-exceptions](https://github.com/capnproto/capnproto/blob/master/style-guide.md#allowing--fno-exceptions), as well as [the tour of KJ exceptions](https://github.com/capnproto/capnproto/blob/master/kjdoc/tour.md#debugging-and-observability).

**Comment by old-pigeon** [comment]
Thanks for the answer!

I meanwhile found out that Cap'n Proto relies on RTTI. I didn't experiment with that in drivers but I guess from a quick research that RTTI is not available in kernel space; at least not without major hurdles.

So I guess this experiment is over before it began.

Sad, but I get that it's totally a non-goal to have support for drivers.

Keep up the good work - I love Cap'n Proto no matter what <3

**Comment by kentonv** [comment]
@old-pigeon Cap'n Proto uses RTTI when available, but can be built without it and should work fine. We have CI tests that verify every combination of `-fno-exceptions` and `-fno-rtti` works.

It does require a compiler that supports `dynamic_cast<void*>` even when RTTI is disabled. GCC and Clang support this; I don't know about MSVC.

**Comment by old-pigeon** [comment]
Thanks for the info! Then I misunderstood that requirement.

**Comment by old-pigeon** [comment]
I'll probably will test around with this and let you/the community about the results.
