### ISSUE TITLE
CAPNP_LITE and MallocMessageBuilder

### ISSUE THREAD

**Issue by mrsteyk** [capnproto/capnproto#1519]
It is impossible to build capnproto in `CAPNP_LITE` mode and use library normally (through `MallocMessageBuilder`), even code which inits root and sets a field requires `kj::systemPreciseMonotonicClock`, which is not built if `kj` detects `CAPNP_LITE`.

Compiler&Linker: MSVC version 2022

error goes something along the lines:
```
undefined external symbol "class kj::MonotonicClock const & __cdecl kj::systemPreciseMonotonicClock(void)" (?systemPreciseMonotonicClock@kj@@YAAEBVMonotonicClock@1@XZ) in "public: void __cdecl kj::_::Mutex::wait(class kj::_::Mutex::Predicate &,class kj::Maybe<class kj::Quantity<__int64,class kj::_::NanosecondLabel> >,class kj::NoopSourceLocation)" (?wait@Mutex@_@kj@@QEAAXAEAVPredicate@123@V?$Maybe@V?$Quantity@_JVNanosecondLabel@_@kj@@@kj@@@3@VNoopSourceLocation@3@@Z).
```

**Comment by kentonv** [comment]
Hi @mrsteyk,

Lite mode is obsolete and is no longer tested. Probably the flag should just be removed. Lite mode was originally introduced as a narrow subset of the codebase which was possible to compile using MSVC. Since then, MSVC has fixed a lot of bugs and for 5+ years now has been able to compile the whole codebase, so lite mode is no longer ended.

If you're trying to reduce your binary footprint, I recommend configuring your linker to automatically drop symbols that aren't referenced from anywhere. On most Unix compilers this can be done using `--gc-sections`; I do not know if MSVC has a similar option.
