### ISSUE TITLE
Apple Silicon on pycapnp PR

### ISSUE THREAD

**Issue by madhavajay** [capnproto/capnproto#1532]
Hi, sorry to be cross posting, but I was wondering if I can get this PR merged in the sub project for Python:
https://github.com/capnproto/pycapnp/pull/296

It passes all the tests and a I fixed the broken windows CI etc so it should be good to go.

**Comment by kentonv** [comment]
Hi @madhavajay,

The C++ implementation and Python implementation are maintained by different people. @haata currently maintains pycapnp so he's the right person to review this. (I am not sure why he hasn't responded yet, sorry.)

**Comment by madhavajay** [comment]
@kentonv no worries, its merged now. Also, while i'm here, do you have any reason to think that dynamically generating the capnp files in memory rather than loading them from a file would lead to any additional security concerns:
https://github.com/capnproto/pycapnp/issues/291

We could generate them as a build step from our python code but if we don't need to why not just load them straight in? Is there some scenario where defining arbitrarily nested capnp with the right bytes could allow some kind of attack?

**Comment by kentonv** [comment]
Hi @madhavajay,

There's theoretically no fundamental problem with generating these files in-memory and then parsing them (without writing to disk first). The C++ library has APIs to support this and the Python wrappers could be extended to expose those APIs.

However, when programmatically generating schemas, you may find it's much easier and cleaner to generate compiled schemas in `schema.capnp` format. This way you don't have to hackily paste text together; you're instead building a structured schema. This will also perform better because you are not generating text just to have it be parsed again -- you're constructing schemas directly in the compiled format.

The C++ class `SchemaLoader` is designed to load schemas in `schema.capnp` format for dynamic use, and is specifically designed with the intent that you can safely load schemas you don't trust. In contrast, the `.capnp` language parser is not really designed with malicious input in mind -- I'm not aware of any specific security issues, but I would never recommend counting on code to be secure if it wasn't designed with security in mind.

I am not sure if `SchemaLoader` is directly exposed to be usable from Python, but in principle it should be possible to expose. The Python implementation is already based on dynamically loading schemas under the hood (as opposed to generating code as C++ apps usually would).

(I'm closing this issue since there's no action item but happy to answer more questions.)
