### ISSUE TITLE
How to handle interrupts in `KJ_SYSCALL`

### ISSUE THREAD

**Issue by LasseBlaauwbroek** [capnproto/capnproto#1542]
`KJ_SYSCALL` is set up to retry on `EINTR`, which for example happens when `SIGINT` is received. This makes it quite tricky to handle such events. Commonly, signal handlers are only used to set some kind of marker that the event has occurred and then return to back normal execution. There the marker is examined and a course of action is determined (either retrying or breaking). `KJ_SYSCALL` seems to make this workflow impossible. To my knowledge, an inifinte retry-loop on `EINTR` is somewhat of an [anti-pattern](https://stackoverflow.com/a/59795677/11510700).

This particularly becomes a problem when using the Capn'proto library from Python. There, C-level signal handlers do exactly what is described above: Set a flag, wait until the next bytecode execution and only then the Python-level handler is executed (in particular, it waits until any C code finishes execution). (https://docs.python.org/3/library/signal.html#execution-of-python-signal-handlers) This makes it impossible to stop execution gracefully when capnp is blocked on a syscall.

What is the recommended solution to this?

**Comment by kentonv** [comment]
Fundamentally, you can't rely on EINTR this way unless you also have a mechanism to avoid starting the syscall if the interrupt is delivered prematurely. Otherwise, if the signal is delivered just before the syscall starts, the syscall will start anyway and will not be interrupted -- a race condition.

Most syscalls do not provide any mechanism to atomically unblock a signal upon starting a syscall, with `pselect`, `ppoll`, `epoll_pwait`, etc. being the rare exceptions.

Sometimes you can do a trick where if you know you need to interrupt a syscall that is going to operate on a particular file descriptor, you can have the signal handler replace the file descriptor with something that will induce a failure. In that case, if the signal was delivered before the syscall started, then the syscall will still error. In fact, this mechanism will even work to interrupt a syscall that is retried on EINTR, since the retry will fail due to the bad FD. (I actually maintain code which uses this trick!) Of course, this only really works if there's a specific syscall, on a specific FD, that you're trying to interrupt, so it's rarely a useful technique.

Another way to avoid the race condition is to call `setjmp()` just before the syscall, and `longjmp()` out of the signal handler if the signal is raised. This way you can unmask the signal and invoke the syscall without worrying about atomicity -- if the signal arrives before the syscall starts, you still end up jumping back to the `setjmp()` point. (I also actually maintain code that does this! In fact, it's how KJ emulates `ppoll()` on systems that may not have it!) But this approach is probably too slow and cumbersome to apply to every syscall.

A less-hacky alternative way to handle this is to do everything in async mode. When using KJ's async I/O, KJ does not perform any blocking syscalls in the first place, so there is no need to interrupt them. It also lets you wait on signals as part of the regular event loop. So you could wait on `SIGINT` and do whatever you want when it is received.

However, when it comes to handling ctrl+c, that's probably not satisfying, since it relies on control actually returning to the event loop. If the program is stuck in an infinite `for()` loop, the signal won't ever be delivered. You really want ctrl+c to interrupt the program reliably no matter what it is doing.

Unfortunately the reality here is that there is simply no way to have a recoverable ctrl+c. ctrl+c must exit the process. It can dump some debug info or something first, but any attempt to convert ctrl+c into a catchable exception will be unreliable. Python is trying to do something impossible, and in practice its KeyboradInterrupt handling has gotten in my way much more often than it has helped me. I think it's a misfeature. Not that that helps, obviously Python isn't going to change this any time soon.

With all that said, I am unsure whether always looping on EINTR is the right choice, but [the Linux man pages](https://man7.org/linux/man-pages/man7/signal.7.html) make the subject sound a lot murkier than what your stack overflow link suggests. This is the kind of stuff that makes me want to write my own syscall wrappers and ditch libc...

**Comment by kentonv** [comment]
FWIW I think the practical answer here is: Python extensions utilizing KJ should always run in async mode, and should set up a mechanism to break out of the event loop if a SIGINT is received.

**Comment by LasseBlaauwbroek** [comment]
You make a good point about the race condition. I hadn't considered that. Replacing the file descriptor is a nice trick. I'll have to remember that.

I agree in principle to use async io in Python. But unfortunately, Pycapnp doesn't have a very good interface between Pythons async and KJ's async: https://github.com/capnproto/pycapnp/issues/256 I'd love to get that fixed.

For making Ctrl+C work properly in Python, the most practical solution is probably just to remove the handler for SIGINT...

Thanks for the detailed response. Closing this for now.

**Comment by LasseBlaauwbroek** [comment]
It seems that your `setjmp` and `longjmp` solution is actually a common pattern in Cython: https://cysignals.readthedocs.io/en/latest/index.html I proposed that Pycapnp use this solution: https://github.com/capnproto/pycapnp/issues/298
