### ISSUE TITLE
Multi-stream Flow Control

### ISSUE THREAD

**Issue by lyz-2026** [capnproto/capnproto#1544]
I want to ask how to use **Multi-stream Flow Contro**l,please give a **sample**

**Comment by lyz-2026** [comment]
Capn0.8 gives the flow control method, but does not give the actual use cases, only gives the interface file, 0.8 has been released for a long time, hope to give an example of flow control, thank you

**Comment by kentonv** [comment]
There's really not much to it. A method declared with `-> stream` can be called like a normal method (that returns nothing), except that the `Promise` returned when you send the message will resolve when it's time to send the next message, rather than waiting for an actual response from the server. If a stream message actually ends up failing, then all non-stream calls made later on will also fail, to give you a chance to detect that an error occurred.

You can check out `byte-stream.capnp` and `byte-stream.c++` for an example, although it is admittedly a rather complicated example.

Sorry but I just don't have time to write up a doc on this. :/
