### ISSUE TITLE
Should `kj::StringPtr` allow implicit construction from `kj::String&&`?

### ISSUE THREAD

**Issue by vlovich** [capnproto/capnproto#1568]
This seems like a dangerous footgun:

```
inline StringPtr(String&& value KJ_LIFETIMEBOUND) : StringPtr(value) {}
```

I would argue that it should be `= delete` so that you are forced to bind to an lvalue reference explicitly first if you really are intending to only use it temporarily.

At a minimum maybe there should be an `explicit` here but I'm not sure if that might subtly break existing code if you have this:
```
kj::String concat(kj::StringPtr str1, kj::StringPtr str2) {
  return kj::str(str1, str2);
}
```
If you made it explicit would something like:
```
  concat(kj::StringPtr(kj::str("str1")), kj::StringPtr(kj::str("str2")))
```
or would the compiler now drop the lifetime of the string at the conclusion of the `StringPtr` construction? I vaguely recall that the compiler is only allowed to call the destructor at sequence points so it should be safe but something to confirm.

**Comment by vlovich** [comment]
Correction. Destructors for temporaries get called at the end of the full expression. So what is the end of the full expression for `concat(kj::StringPtr(kj::str("str1")), kj::StringPtr(kj::str("str2")));`. I would think it's the `;` but something to double-check.

Sequence points don't apply here since `,` would be a sequence point and there would be all sorts of code breakage for innocuous code.

**Comment by kentonv** [comment]
Consider the function:

    void print(kj::StringPtr text);

The function synchronously uses the input; it doesn't keep the pointer after returning.

I want to call it like:

    print(kj::str("Hello, ", name, "!"));

This is perfectly valid, because the temporary `String` is not destroyed until the end of the statement, i.e. after `print()` returns.

But if I couldn't construct `StringPtr` from `String&&`, then I couldn't use this syntax. I'd have to write this instead:

    auto message = kj::str("Hello, ", name, "!");
    print(message);

This pattern appears basically everywhere, and forcing this change would be painful.

However! You may notice the `KJ_LIFETIMEBOUND` annotation on the constructor input. This allows the compiler to detect and warn in obvious cases where the StringPtr outlives the input String. It does, in fact, allow the `print` example above while catching most problematic cases. For example, if I write this:

    kj::StringPtr message = kj::str("Hello, ", name, "!");

The compiler does, in fact, catch and flag this, giving me the error message:

> error: temporary whose address is used as value of local variable 'message' will be destroyed at the end of the full-expression

So this seems to cover the footguns implied by this constructor.

As it turns out, you were the one who added this `KJ_LIFETIMEBOUND` annotation, in #1246.

Have you found some specific case that the `KJ_LIFETIMEBOUND` annotation is not covering well?

**Comment by vlovich** [comment]
Hmm.... I forget now exactly where I came across this (I think in the KV bindings) but `KJ_LIFETIMEBOUND` did not warn me for whatever reason...
