### ISSUE TITLE
Any document on serialize/deserialize many messages for socket communication?

### ISSUE THREAD

**Issue by alex-lt-kong** [capnproto/capnproto#1611]
My current implementation basically follows the official site: https://capnproto.org/cxx.html, just making everything into a loop. It roughly looks like this:
```C++
kj::Array<capnp::word> serialize(person_struct& p) {
    capnp::MallocMessageBuilder msg_builder;
    Person::Builder person = msg_builder.initRoot<Person>();
    person.setId(p.id);
    person.setName(p.name);
    return messageToFlatArray(msg_builder);
}

for (int i = 0; i < 2147483647; ++i) {
    bytes = encodeStructToBytesCapnp(p[i]);
    socket.send(bytes.asChars().begin());
}

```
However, after searching on the Internet, I find [this post](https://stackoverflow.com/questions/61347404/protobuf-vs-flatbuffers-vs-capn-proto-which-is-faster) from @kentonv . Now it seems to me that what I did is anti-pattern. But I failed to find a proper way to correct the above, my confusions include:

1. My understanding is that using `getSegmentsForOutput()` means there is no extra copy, bytes get sent directly from Capnp's internal buffer to socket. But how exactly should this be used? Let's say my message is stored in three segments, should I call `socket.send()` three times? If yes, then how can recipients know if the message is completely received and is ready for deserialization?
2. The post said that "[t]o avoid memory allocation with each iteration, you should pass a scratch buffer to MallocMessageBuilder's constructor." How exactly should this be done?

Thanks

**Comment by kentonv** [comment]
If your socket is a standard network socket provided by the operating system (on a unix-like OS), you can `capnp::writeMessageToFd(socket, msg_builder);` to write the message to the socket with zero copies.

But since your code says `socket.send()`, I guess your `socket` is not a plain OS socket, but some sort of object. In that case what you probably want to do is implement a custom subclass of `kj::OutputStream` (defined in `kj/io.h`) which writes to your socket. Then, you can use `capnp::writeMessage(my_stream, msg_builder)` to write the message to that stream. Hint: `writeMessage()` always uses the overload of `OutputStream::write()` that takes an array-of-arrays as its argument, and it calls the method only once to write the whole message.

`MallocMessageBuilder`'s constructor can accept a scratch buffer as an argument. This is just an array of words. You can allocate it with `kj::heapArray<capnp::word>(size)`, then zero it with `memset(scratch.begin(), 0, scratch.asBytes().size())`. Then you can pass this array as a constructor parameter whenever you create a `MallocMessageBuilder`. Make sure to destroy the builder before using the same scratch array in a new builder.
