### ISSUE TITLE
Bug: error compiling for wasm: missing `byte-stream.capnp.h`

### ISSUE THREAD

**Issue by jon-chuang** [capnproto/capnproto#1637]
```
emcc -I../capnproto/c++/src wasm.cpp ../capnproto/c++/src/capnp/**/*.c++ --bind 
In file included from ../capnproto/c++/src/capnp/compat/byte-stream.c++:22:
../capnproto/c++/src/capnp/compat/byte-stream.h:25:10: fatal error: 'capnp/compat/byte-stream.capnp.h' file not found
#include <capnp/compat/byte-stream.capnp.h>
```

Why is this file excluded? Seems trivial to include it in the src.

Workaround: did not include relevant C++ files in compilation.

**Comment by kentonv** [comment]
This file is generated from `byte-stream.capnp` using `capnp compile`. We only check in generated code in cases where the `capnp` tool itself depends on the file, in order to break the cyclic dependency. `capnp` does not depend on this file, therefore the generated code does not need to be checked in.

We do not support nor recommend simply compiling `**/*.c++` as a build strategy. If you aren't using one of the supported build systems (autotools, cmake, or bazel) then you are on your own with issues like this.

**Comment by jon-chuang** [comment]
Thanks. emmake was able to help me circumvent these issues.
