### ISSUE TITLE
How to do streaming and use of "stream" designation in Capnp interface definition?

### ISSUE THREAD

**Issue by risa2000** [capnproto/capnproto#1646]
Recently, I have been trying to figure out how to implement streaming capability in Capnp framework. The "stream" is not a flow continuous information (as in e.g. a media stream), but rather a stream of discrete packets (sensor readings). The server is the source and clients subscribe and unsubscribe to the sensor data as they come and go.

There is a desire to not lose the readings once someone starts receiving them, but there is no "beginning" or "end" to the stream and the server does not need to know whether the client has received everything since there is no way to help it anyway. The clients should be able to detect dropped packets, but this is done on the application layer already.

What I found so far was a notion of `stream` type of call as describe here:
https://capnproto.org/news/2020-04-23-capnproto-0.8.html

The post also mentions that the interface _must_ (with an emphasis on it) implement another function called `done`:
```capnp
interface Callback {
    # NEW: This streaming call features flow control!
    sendChunk @0 (chunk :Data) -> stream;
    done @1 ();
  }
```
I am not sure however, how I should implement it and why? Is it something mandated by the underlying `stream` implementation, or is it merely a suggestion?
I am also a bit confused by the syntax, why is it not defined as:
```capnp
done @1 () -> ();
```

In my case (as described above), where I do not care about the clients on the server, the tests run fine without `done`, but this seems a bit too superficial to take as a proof.

**Comment by kentonv** [comment]
Hi @risa2000,

The `done()` method gives you a chance to detect errors. If the stream becomes disconnected or if the receiving end throws an exception, `sendChunk()` won't necessarily propagate this, because the promise returned by `sendChunk()` actually resolves long before the chunk has actually reached the recipient. The final `done()` call does a full round trip to the peer. If any previous `sendChunk()` calls actually failed, the exception will be thrown by `done()`.

If you truly don't care about this error handling, then you don't need a `done()` method. However, in my experience skipping error handling is dangerous, as it could lead actual bugs to go undetected. It's up to you, though.
