### ISSUE TITLE
KJ event loop advanced backward in time

### ISSUE THREAD

**Issue by fabiorossetto** [capnproto/capnproto#1693]
On an Intel Mac, we observed this very unusual issue. An exception is triggered from within `TimerImpl::advanceTo`:
```
12:22.18.264821 [fatal] expected newTime >= time [13170.242604s >= 13170.337457s]; can't advance backwards in time
libc++abi: terminating due to uncaught exception of type kj::ExceptionImpl: kj/timer.c++:113: failed: expected newTime >= time [13170.242604s >= 13170.337457s]; can't advance backwards in time
stack: 104d0fa65 104cefef4 104cf04bb 104ce2328 104ce2769 104c702bf 104c6f9ad 104c6f875 104c6fa60 104d4b168 104d4bc67 104d4bb5f 7ff80c5ab1d2 7ff80c5a6bd2
```
`advanceTo()` is always called with clock.now() as argument, which internally calls `clock_gettime(CLOCK_MONOTONIC)`.
So I don't see how this can possibly happen, other than `clock_gettime(CLOCK_MONOTONIC)` returning a timestamp smaller than a previous one.

As anyone ever encountered a similar issue?

**Comment by kentonv** [comment]
That is indeed strange and shouldn't be possible if `CLOCK_MONOTONIC` is working correctly.

I haven't ever observed this problem myself.

Have you seen this happen more than once?

**Comment by tonyp-zi** [comment]
I originally reported the issue to @fabiorossetto. It did occur on several occasions. Until recently only with our debug build, so we did not bother too much about it. The pattern so far has been burst-like: few occurrences in a row (like over a few hours) and then nothing for weeks.

**Comment by kentonv** [comment]
Is it always on one particular machine or is this across many machines? Wondering if the clock hardware could be broken or something.

If we need to work around this, it's pretty easy to clamp the value returned by CLOCK_MONOTONIC to be at least the previous value, but the OS really ought to be doing that already...

**Comment by kentonv** [comment]
Hmm. Well, admittedly I mostly stick to Linux, but we do have CI which runs on intel macs, and I've never seen this happen there.

I suppose I'm willing to accept a PR which, on mac only, changes `PosixMonotonicClock` so that it records the previous reading and clamps future readings to be at least that.

However, synchronization may be a little tricky. You don't really want to lock a mutex on every clock read but you also don't want concurrent clock reads on multiple threads to create an inconsistency here. You might need at atomic compare-and-swap when updating the value to ensure that it hasn't already been updated to a larger value by another thread? Alternatively you could use a thread_local I guess, and say it's OK for this clock inconsistency to occur between threads?

**Comment by tonyp-zi** [comment]
Thanks for your rapid answers @kentonv. 

We were wondering with @fabiorossetto if it would be simpler to disable the `KJ_REQUIRE(newTime >= time)` for Mac? Possibly also changing  `time = newTime` to `time = max(time, newTime)`. Or do you think that a non monotonic clock could have other undesirable consequences?

**Comment by kentonv** [comment]
Hmm. I suppose correcting for the problem inside `advanceTo()` makes sense since it sidesteps the synchronization issues.

It does mean that any other code relying directly on `kj::systemPreciseMonotonicClock()` may have its assumptions violated -- but I suppose that is generally true of all software relying on CLOCK_MONOTONIC already, on this machine. I can't think of any particular component of KJ or Cap'n Proto that would be affected.

In `TimerImpl::advanceTo()` I would definitely use `time = max(time, newTime)`, not just ignore the error -- otherwise I think stuff could actually be broken by the time going backwards. I'd prefer that this work-around apply only to the specific OS/architecture combinations where the problem was observed and we stick to the existing assertion everywhere else.

**Comment by tonyp-zi** [comment]
Sounds like a plan!

FYI, @tuxu was just mentioning that Rust has a similar workaround in place: https://github.com/rust-lang/rust/blob/10b7e468f3cc263b8df8ff0212d0911ed5a3c090/library/std/src/time.rs#L137

**Comment by germandiagogomez** [comment]
I can confirm it happens to me from time to time in Intel Mac as well.

```
terminating with uncaught exception of type kj::ExceptionImpl: kj/timer.c++:113: failed: expected newTime >= time [161468.95222s >= 161469.000629s]; can't advance backwards in time
stack: ...
```

**Comment by fabiorossetto** [comment]
Addressed in https://github.com/capnproto/capnproto/pull/1705
