### ISSUE TITLE
Please add a comment to the output file reflecting the SHA of the input

### ISSUE THREAD

**Issue by kyanha** [capnproto/capnproto#1914]
This is perhaps a bit stupid of a request, but in Veilid we're running into a problem caused by a juxtaposition of bad decisions across multiple tools (and possibly by our own repository manager):

1. git doesn't let you commit an unchanged file in order to update its timestamps.
2. The .capnp file (already in the repo) was updated to include more comments. Notably, none of the structures were changed.
3. The output file (also committed to the repo) doesn't get changed as a result of rerunning capnp based on the .capnp file time update.
4. Every new checkout of the Veilid repo now requires capnp to be installed and at the latest version in order to rebuild the output as a result.

Because relying on file modification timestamps is broken in a git environment, I humbly request that the output change, by including the SHA of the input file. This will force at least a few bytes to change, which will allow the regenerated output to be committed by git, which will bypass this entire problem.

However, it will also give a tool that developers can use to figure out where breakdowns in their build systems are occurring ("Why is this saying it was built from a sha that doesn't match anything that was ever committed?) and help locate potential supply-chain attacks, so I think it's something that you might wish to make available.

**Comment by kentonv** [comment]
This would break a different desirable property: Many build systems cache the results of build steps based on a hash of the inputs, so that they can avoid re-running steps when the inputs haven't changed. So, if comments change in a capnp schema file, but this results in no changes to the generated code, then the build system doesn't have to recompile the code (or relink binaries, rerun tests, etc.). But if the generated code contains a hash of the input, then this is defeated.

I am not sure it would solve your problem anyway. Git does not keep track of modification times on files. What it does do is, whenever a git command causes a file to _change_, git will update the file's timestamp to the current time. E.g. if you switch back and forth between checking out two branches, you'll see whichever files differ between the branches keep getting their timestamp updated to the current time; it doesn't set timestamps back to when the content was first generated. So let's say you check out a new commit that modifies both the `.capnp` file and the generated `.capnp.{h,c++}`. You are hoping that the build system will decide that the `.capnp.{h,c++}` are newer than the `.capnp` file and therefore it doesn't need to generate them. However, this will only be the case if git just happens to update the `.capnp` file first, before the generated files. I am not sure there is any guarantee of this.

Conversely, let's say you switch to a commit where the generated files have changed but the `.capnp` file has not -- perhaps because the committer regenerated the files with a newer version of capnp. Let's say that just before pulling this commit, you had made your own changes to the capnp file. Now you're in a weird position: The build system will ignore your changes to the capnp file because the generated files appear to be newer.

Basically, any time you check in the _output_ of a build rule -- when the build system uses timestamps to decide when to rebuild -- you are asking for trouble. I highly recommend avoiding this altogether. Instead, there are two ways you can do things:

1. Don't check in generated code. Require everyone to have the tools installed so they can build from true sources. This is generally what I recommend. You can perhaps have your build system automatically download the tools if they are missing.

2. Check in the generated code but do not define them as the output of a build rule. Instead, require developers to manually run a script (or a phony make target) to update generated code whenever they change the schema. You can also have a test or CI action that enforces that the generated code is consistent with the schema file. This is what the Cap'n Proto repo itself does, for generated code that is part of the compiler and would otherwise create a cyclic dependency.

FWIW, if you really want to forge forward with this idea of putting the hash in the output, you could pretty easily do this yourself by adding a line to the build rule like:

    echo "// $(sha256sum foo.capnp)" >> foo.capnp.h

But I don't think this is something we'll add as a built-in feature, sorry.
