### ISSUE TITLE
How to get Orphanage from Request?

### ISSUE THREAD

**Issue by Milek7** [capnproto/capnproto#1933]
`Orphanage::getForMessageContaining` accepts `Builder` by value, but while `Request` inherits from it, it also contains kj::Own so it cannot be copied.

**Comment by kentonv** [comment]
You could explicitly tell `getForMessageContaining()` to use the parent builder type:

    Orphanage::getForMessageContaining<MyType::Builder>(request)

The problem is that, if you don't specify the template param explicitly, then C++ decides to use `Request<...>`, which is not copyable as you note. Probably we should overload the template with a version that accepts an lvalue reference to handle this case.

**Comment by Milek7** [comment]
Thanks, that worked.
