### ISSUE TITLE
Inter Process Communication

### ISSUE THREAD

**Issue by sinainnet** [capnproto/capnproto#1983]
Hi,

I have a question, is the Inter-Process Communication based on shared memory implemented? If so, How can we use it.

**Comment by kentonv** [comment]
This is not implemented in Cap'n Proto at present but there are third-party implementations. To implement it in your own code -- without changing the Cap'n Proto library -- you would need to define custom subclasses of `capnp::MessageReader` and `capnp::MessageBuilder` which allocate segments in shared memory. [Flow-IPC](https://github.com/Flow-IPC) is a third-party project which (I'm told) already does this. In order to use shared memory for RPC, you also need to implement `capnp::VatNetwork`, which provides the transport layer for the RPC system. My understanding is that Flow-IPC doesn't do this yet (it has its own alternative RPC framework), but might do so in the future.
