### ISSUE TITLE
VOID is often #defined on Windows; work around it

### ISSUE THREAD

**Issue by kentonv** [capnproto/capnproto#284]
Unsure how best to deal with this:
- Just #undef it? May break code.
- #error explaining the problem to the user and suggesting options?
- Some sort of hack where we #undef it just for our purposes and then restore the define before getting back to application code?

**Comment by TyRoXx** [comment]
Fourth option: Stop using all caps, generic identifiers. Capnproto is begging for collisions by using  identifiers like ``STRUCT``, ``INTERFACE``, ``BYTE`` (!), ``POINTER`` or ``VOID`` in public headers. This is unusual and hard to read. Reserving all caps for macros is a good convention. Please consider following it. You are already doing so many things right.

**Comment by kentonv** [comment]
@TyRoXx All-caps is a widely-used style for constants. Even if we decide that it was a poor choice, we can't change it now without breaking source compatibility, which is not acceptable.

Arguably, people who #define macros without a namespace prefix are the ones asking for trouble, but unfortunately Windows seems to do a lot of this in its system headers, so we'll need a work-around.

**Comment by harrishancock** [comment]
Kenton, this issue seems like a good use case for `#pragma push_macro`. Consider:

```c++
// kj/some-header.h
#ifndef KJ_SOME_HEADER_
#define KJ_SOME_HEADER_

// various includes ...
#include <windows.h>  // uh-oh!

// After all includes, but before our code starts, save Windows' special little defines
#pragma push_macro("ERROR")
#undef ERROR
#pragma push_macro("VOID")
#undef VOID


namespace kj {
  // Meat of the header ...
  enum { ERROR = 1, VOID = 2 };  // no problems!
}  // kj


// After our code ends, restore Windows' special defines for the dubious benefit of user code
#pragma pop_macro("ERROR")
#pragma pop_macro("VOID")

#endif  // KJ_SOME_HEADER_
```

To keep things more maintainable, the `push_macro`, `undef` incantations can go inside a `kj/push-options.h` header, and the `pop_macro` incantations can go inside a `kj/pop-options.h` header. capnp, kj, and generated headers would have to remember to `#include <kj/push-options.h>` at the top and `#include <pop-options.h>` at the bottom.

Pros:
- User code can `#include <windows.h>` before our headers and it would work fine
- `push_macro` and `pop_macro` are supported in clang, gcc, and MSVC
- The `push-options.h` and `pop-options.h` headers would be a perfect place to emulate GCC's `system_header` pragma with the strategy described here: https://groups.google.com/forum/#!msg/capnproto/t5o1pmpHHB4/ATcpVaWzBQAJ
- `kj/windows-sanity.h` would be obviated

Cons:
- Two new lines of boilerplate for each header file
- Having to remember to include a header at the *bottom* of a file really sucks
- The list of macros that need to be pushed and popped would have to be maintained in two separate headers

**Comment by Leandros** [comment]
Is this still being worked on, or better yet, done?

**Comment by harrishancock** [comment]
Thanks for the ping on this! At the moment it is neither done nor worked on. :/ It's probably little more than a day's project, though -- I've just been squeezed for time.

**Comment by Leandros** [comment]
Ironically, your small snippet, which just redefines `VOID` & `ERROR` seems to work fine for me on Visual Studio 2017.
