### ISSUE TITLE
Can't use kj::Own for incomplete types

### ISSUE THREAD

**Issue by zombiezen** [capnproto/capnproto#397]
(This may be WAI and is a small detail, but it prevented me from using `kj::Own` in a certain place in my code.) Because `kj::Disposer` uses the `__is_polymorphic` trait test, `kj::Own` cannot be used with incomplete types.  These occur frequently when dealing with opaque pointers in C headers &mdash; in particular, I was trying to create a `kj::Own<lua_State>`.

**Comment by kentonv** [comment]
Yeah, this is tricky, because in some cases it's actually not possible for the code to call the disposer correctly without knowledge of the type. Specifically, if type C multiply-inherits from D and E, then an E* pointer pointing to an instance of C is actually numerically different from a C* (or D*) pointer to the same object. The disposer only takes a void* pointer, and it's important that that pointer point to the beginning of the object. To determine the offset, we have to consult the vtable, but only polymorphic types have vtables, so we have to know if it's polymorphic.

Not sure what we can do here unfortunately.

**Comment by zombiezen** [comment]
Makes sense. I'm fine if this is a "won't fix" issue: it's certainly an edge case.  Just figured I'd raise it as an issue so my observation doesn't disappear into the ether.

kj is good enough that it _almost_ makes me like writing C++. :)

**Comment by kentonv** [comment]
I'm going to poke at this a little bit before 0.6 but I suspect I'll end up closing it with no solution...

**Comment by kentonv** [comment]
AFAICT, the properties of `Own` are the same as the properties of `std::unique_ptr` here.

You can declare functions and methods that use `Own<IncompleteType>` as a parameter or return type.

You can default-construct an `Own<IncompleteType>`.

You cannot call `heap<IncompleteType>(...)` since the type's constructors are unknown.

You cannot destroy an `Own<IncompleteType>` because the type's destructor is unknown.

Is there a use case that works with `std::unique_ptr` but not with `kj::Own`?

**Comment by kentonv** [comment]
(Closing out this bug for now but if you have a use case where Own differs from unique_ptr please let me know.)

**Comment by zombiezen** [comment]
What I was trying to do:

```cpp
class LuaStateDisposer: public kj::Disposer {
public:
  static const LuaStateDisposer instance;

  void disposeImpl(void* pointer) const override {
    lua_close(reinterpret_cast<lua_State*>(pointer));
  }
};

kj::Own<lua_State> newLuaState() {
  lua_State* state = luaL_newstate();
  KJ_ASSERT_NONNULL(state);
  return kj::Own<lua_State>(state, LuaStateDisposer::instance);
}
```

versus what does compile with `std::unique_ptr`:

```cpp
std::unique_ptr<lua_State, void(*)(lua_State*)> newLuaState() {
  lua_State* state = luaL_newstate();
  KJ_ASSERT_NONNULL(state);
  return std::unique_ptr<lua_State, void(*)(lua_State*)>(state, [] (lua_State* pointer) {
    lua_close(reinterpret_cast<lua_State*>(pointer));
  });
}
```

**Comment by kentonv** [comment]
Interesting. So this seems to be a side-effect of how `std::unique_ptr` uses template polymorphism for disposal, whereas `kj::Own` uses dynamic polymorphism.

Unfortunately I don't think I can come up with a solution here, except to provide some other way that you can manually tell KJ "this incomplete type is not dynamic, I promise". There are various ways we could accomplish that but I'm not sure it's worth it... but I'd accept a PR.

**Comment by zombiezen** [comment]
Fair enough. Should we keep the issue open, then?
