### ISSUE TITLE
`capnp compile` is not sending EOF to plugins on Windows

### ISSUE THREAD

**Issue by Someguynamedpie** [capnproto/capnproto#488]
I'm trying to use capnp decode to decode the code request sent by the compiler, but it's blocking indefinitely after it successfully outputs the decoded content. I think it should be possible to tell the decoder to stop decoding after the first successful decoding (or set a timeout or similar).

**Comment by kentonv** [comment]
Hmm, it should stop when it sees EOF. Is the input not sending EOF? What type of handle is stdin in this case? (E.g. file, pipe, console, etc.)

Sorry for the slow reply.

**Comment by Someguynamedpie** [comment]
It's been a minute, but I don't think it's sending an EOF when the piped program exits, but I might be mistaken.
Actually, it's kind of a hack, in my script I run 'capnp decode schema.capnp CodeGeneratorRequest' (the script is a compile script thats executed in the bat file, which then has all input get forwarded to the script, which the script then runs the decoder, which receives the input directly from the compiler.) Convoluted, yes, but kind of ideal in my case.

**Comment by kentonv** [comment]
Hmm, I think the problem here may be that on Windows, where we have to use spawn() instead of fork()/exec(), we aren't correctly preventing the child from inheriting a copy of the pipe's write end, and hence the read end never produces EOF because the write end is still open (in the child).

It's unclear to me if we can fix this while still using spawn()... it looks like we have to get the underlying Win32 handle and change it to be non-inheritable? I'm not sure if the CRT will like that, though. If not, we may have to switch to using CreateProcess() and Win32 pipe handles rather than CRT's file descriptor emulation.

**Comment by Someguynamedpie** [comment]
Yeah the downside to doing that is the winapi for piping process... pipes is somewhat annoying to do but it might be necessary in this case.

**Comment by piscisaureus** [comment]
The way to do this is to write an empty (0-byte) buffer.
