### ISSUE TITLE
C# version dead?

### ISSUE THREAD

**Issue by emilm** [capnproto/capnproto#497]
Is there no longer a C# version that's maintained? Or is the C# version good enough? Thanks.

**Comment by kentonv** [comment]
The only C# library I'm aware of is the one linked from https://capnproto.org/otherlang.html -- my understanding is that the author no longer intends to maintain it, but is willing to let someone else take it over.

(Closing this issue since it's not an action item for this repository, but feel free to start a discussion in the [discussion group](https://groups.google.com/group/capnproto).)
