### ISSUE TITLE
vector<uint8_t> serialization

### ISSUE THREAD

**Issue by jiri** [capnproto/capnproto#500]
Hi,

I wrote a schema and compiled it, and now I want to create a value of that schema and convert it to `vector<uint8_t>`, or just to bytes in *any* way. However, I'm having great trouble achieving this and I find it hard to believe that it would be so hard or impossible.

What is the canonical way to serialize / deserialize messages to / from bytes?

**Comment by katreniak** [comment]
Did you search in `capnp/serialize.h`?

**Comment by jiri** [comment]
Yeah, the only thing I've found that was remotely similar to what I wanted is `messageToFlat`, which returns `kj::Array<word>` and is extremely cumbersome to work with.

Is there really not a way to just get an array of bytes? Am I missing something?

**Comment by katreniak** [comment]
You can cast `kj::array<word>`. `word` is raw data aligned to 8 bytes. Sorry, I don't have code examples.

**Comment by jiri** [comment]
I see! Thanks :)

Still, I think this is a massive issue with the API. Is there a reason for pushing custom types from `kj` instead of using standard containers and data types?

I think that getting a byte array from a binary serialization library is such a massive use case that making it hard and convoluted is an API design issue.

**Comment by kentonv** [comment]
Hi,

You can use `.asBytes()` or `.releaseAsBytes()` on any array to get an `Array<byte>`.

The reason we like to use `Array<word>` is to express the fact that the array is aligned on a word boundary, which is important for zero-copy usage since most architectures either require data to be aligned or are slower if it's not.

On another note, keep in mind that `messageToFlatArray()` does a copy, since the underlying message is not backed by a single contiguous array, so a new one must be allocated and filled with the message content. If you're using Cap'n Proto for zero-copy, this may defeat the purpose. Consider using `writeMessage()` instead and providing a stream implementation to write to (the `write()` calls made on this stream will receive direct pointers to the message data without copying). Or, use `message.getSegmentsForOutput()`, which returns an array of arrays of words that point directly into the backing memory of the message, hence avoid making a copy -- but in this case it's up to you to provide some way to keep track of the segment boundaries when you store / transmit them.

**Comment by jiri** [comment]
Thanks!
