### ISSUE TITLE
autotools build does not install cmake files?

### ISSUE THREAD

**Issue by thomaslee** [capnproto/capnproto#523]
Just raising this to be sure it's not an oversight:

While packaging up 0.6.1 I noticed that we've now got cmake config files upstream, which is great. I'm a bit confused by the way they're integrated into the build system, though: running a `./configure && make install` on Linux from a source distribution tarball will not lead to the cmake files under `cmake/` being installed. As far as I can tell we don't even try to generate CapnProtoConfigVersion.cmake from CapnProtoConfigVersion.cmake.in. Is this omission intentional?

If I run a cmake build, I can see that these files are correctly generated (and presumably installed, though I didn't try), but the docs on the web site still seem to point me toward the autotools configure script on Unix.

**Comment by thomaslee** [comment]
Perhaps the assumption is folks on \*nix can use `pkg_check_modules` & the pkg-config files instead of "native" cmake config? If so I've probably got to talk through the implications of ripping out the cmake config files on the Debian side -- I don't want to maintain entirely independent native cmake config if everybody on Linux is going to be using the pkg-config files anyways.

**Comment by harrishancock** [comment]
@thomaslee there was some prior discussion of this in #495, but it deserves its own issue -- thanks for raising it.

> As far as I can tell we don't even try to generate CapnProtoConfigVersion.cmake from CapnProtoConfigVersion.cmake.in. Is this omission intentional?

Yes, it is in intentional, though not desirable. Generating a CMake package config is a feature implemented by the CMake build of capnproto, but not (yet) by the autotools build. This has created an awkward situation: the autotools build is the canonical build system of capnproto, but CMake-based client projects have started depending on the CMake package config, which is not installed by the autotools build. Thus CMake-based client projects are locked into the CMake capnproto build.

A workaround might be to package the CMake build for unix OS package managers, which is what the OP of #495 did, I believe. This is potentially dangerous, as @kentonv pointed out in that PR, because the CMake build does not implement the same ABI stability policy (i.e., no ABI stability across versions) as the autotools build. It is possible to emulate this behavior in CMake ([here's how Roger Leigh did it for Xerces-C++](http://svn.apache.org/viewvc/xerces/c/trunk/src/CMakeLists.txt?revision=1800911&view=markup#l1269)), but it's ugly.

Ultimately, I believe the resolution will have to be to install the package config files from the autotools build. A minimal package config would be easy to whip up, but getting the details right (complete drop-in replacements for all `IMPORTED` targets generated by the CMake config, with all transitive compile options set correctly, etc) is a little daunting, and I worry it will become a maintenance burden. I don't think the cost of maintaining feature parity between the two build systems was fully appreciated when the package config feature was added to the CMake build. I certainly didn't realize it until #495.

**Comment by kentonv** [comment]
@thomaslee My current position is that the cmake build is unofficial (except on MSVC where it's necessary). Official packages should be based on the automake build, not on cmake.

I agree it would be nice to be able to install the cmake macros, but at present that's just not officially supported. Hopefully someone will contribute a solution at some point. I'm not sure if that solution should be improving the cmake build to feature-parity with automake or if it should involve extending automake to be able to install these files.

I personally don't know cmake, though, so I'll need some help here.

**Comment by Conan-Kudo** [comment]
> This is potentially dangerous, as @kentonv pointed out in that PR, because the CMake build does not implement the same ABI stability policy (i.e., no ABI stability across versions) as the autotools build.

This is not true. When you use `VERSION` instead of `SOVERSION`, it implements *exactly* that policy. As I said in #528, the usage of `VERSION` makes it so that CMake encodes the full version field into the binary image so that things that depend on it request the exact library.

**Comment by harrishancock** [comment]
@Conan-Kudo Thanks for the correction! Sorry to spread FUD.

**Comment by Conan-Kudo** [comment]
@harrishancock For what it's worth, this complexity is precisely the reason why a lot of projects are migrating from Autotools and CMake to the Meson build system (cc: @jpakkane). It might be worth considering dropping *both* to migrate to Meson to simplify and eliminate this whole mess.

Dual build systems are not fun at all. :(

**Comment by kentonv** [comment]
Cap'n Proto actually has three build systems: The system I prefer and use day-to-day ([Ekam](https://github.com/sandstorm-io/ekam)), and the systems that we support because other people demand them for compatibility (autotools and cmake).

Unfortunately, adding Meson would not allow us to remove any of these: I will continue to prefer Ekam, and we'll still need to support autotools and cmake because other people demand them for compatibility.

Also:

![](https://imgs.xkcd.com/comics/standards.png)

**Comment by ignatenkobrain** [comment]
@kentonv well, just because people depend on old stuff doesn't mean that you can't remove it. For example, GNOME projects and systemd (and probably something else) are going to remove autotools-buildsys from their projects after few releases. This is fine.

**Comment by kentonv** [comment]
@ignatenkobrain It's much easier for higher-level projects to do that. Cap'n Proto is a library, and it's the kind of library people may commonly want to integrate into their own builds (rather than depend on an installed copy), which makes things harder. Cap'n Proto also targets a more diverse set of platforms than systemd and GNOME do, and more mature build tools are less likely to be a problem for that.

Believe me, I would love to ditch autotools, but I think it would lead to trouble.

**Comment by thomaslee** [comment]
> Actually, I suspect ditching autotools might not be difficult. The main output of autotools builds are libraries and pkgconfig files.

Maybe Kenton is thinking of the "vendoring" use case as he says here:

> it's the kind of library people may commonly want to integrate into their own builds (rather than depend on an installed copy)

In this scenario having the "correct" build system actually helps a whole bunch.
