### ISSUE TITLE
Mac, capnpc -oc++ test.capnp, error

### ISSUE THREAD

**Issue by shanshanpt** [capnproto/capnproto#544]
when I exec: capnpc -oc++ test.capnp 

dyld: Library not loaded: /Users/kernel/myLib/lib/libcapnpc-0.6.1.dylib
  Referenced from: /Users/kernel/myLib/capnproto/bin/./capnpc
  Reason: image not found
Abort trap: 6

**Comment by kentonv** [comment]
Does `/Users/kernel/myLib/lib/libcapnpc-0.6.1.dylib` exist? It sounds like the file is missing, indicating an installation problem.

**Comment by shanshanpt** [comment]
Hmm.. I solved the problem. 
By the way, whether cap'n support zero copy, like protobuf ? 
The Scenes is that I have big bytes element, I dont want to copy it to the buffer, just give a pointer
to the memory is fine. Can capn do that? 
Thanks so much! :)

**Comment by kentonv** [comment]
In fact, Protobuf is *not* zero-copy. Cap'n Proto is. This was actually the main design goal of Cap'n Proto. :)

Protobuf's ZeroCopyOutputStream is misnamed. It should have been called OneCopyOutputStream. I'm the one who named it, and at the time I hadn't yet realized that serialization itself constituted a copy that could be eliminated.

In Cap'n Proto, you can call `MessageBuilder::getSegmentsForOutput()` to get direct pointers to the message data which you can write without making any copies. Alternatively, most of the read and write methods, like `writeMessageToFd()` and `StreamFdMessageReader`, perform minimal copies. When reading from disk, you can also use `mmap()`.

(Closing this issue since you say you solved the problem.)
