### ISSUE TITLE
Are asynchronous callbacks without request from the other side possible?

### ISSUE THREAD

**Issue by apriori** [capnproto/capnproto#591]
How would you implement e.g. a function that the client registers on the server side for it to be called e.g. periodically or otherwise independant of client requests? In the calculation example I see the case of the PowerFunction being transfered to the server, but it is only executed as a result of a client request, which is more equivalent to "polling".

**Comment by kentonv** [comment]
Hi @apriori,

It's true that in the calculator example, the callback object is only invoked while responding to a request from the client. However, this is not a requirement -- the server is free to hold on to the object handle and invoke it at any time. The client will receive the callback asynchronously (as long as the client is still connected, of course). There's nothing special needed here.

**Comment by apriori** [comment]
Thank you for your answer. Would you mind answering a different question in the same context? How would that object be used from another thread? I see that every thread needs to have its own eventloop, so if I understand this right one would need to have some other communication between both threads. 
Is there another way to implement this in capnproto?

**Comment by kentonv** [comment]
This is a complicated question.

Fundamentally, any time you want to have multiple threads sharing a single connection, some form of synchronization is necessary. Some systems use a thread-pooling model that allows for an n:m mapping between connections and threads, where multiple threads share a single event queue, but this can be very complicated to get right, and the synchronization costs can actually be pretty high. Cap'n Proto, inspired by the actor model, prefers to have a n:1 mapping, meaning each connection is owned by one thread.

There are two ways you could design your multithreaded program that makes asynchronous callbacks to the client:

1. Have the client make multiple connections, one to each server thread. This is actually great for performance because it avoids any need for cross-thread synchronization on the server side. If this approach is at all reasonable for your use case then I recommend it.

2. Have the client connect to one thread, and have that thread in turn connect to the other threads. Cap'n Proto makes it very easy to forward a capability (object reference) across multiple connection hops. So the first thread receives the capability from the client, and then sends it across local connections to the other threads. When one of the other threads calls the capability, the message travels first over the local connection to the main thread, and then is proxied back to the client. Cap'n Proto sets up this proxying implicitly when you pass a capability across multiple connections, so this is very easy code to write.

    Of course, by default this approach adds a lot of copies, because you'd be writing each message into a Unix socket just to have it come back out into your same memory space on the other side. You could optimize this by creating a custom transport (implementation of capnp::VatNetwork) that transmits message objects between threads without a copy. This is something the Cap'n Proto library is likely to offer in the future, but it's possible for applications to implement such a thing directly today without any changes to the core library.

**Comment by apriori** [comment]
Thanks for your reply again. I would be fine with the second approach as the first one would also publically export the "callback relay" which I would not prefer. 
Maybe to show more context on what is actually tried to achieve, consider the following two capnp files:

```
// callbackservice.capnp
@0x9bd580d70ca0afa9;

interface Callback
{
    call @0 (param: UInt32) -> ();
}

interface Service
{
    registerCallBack @0 (callback:Callback) -> ();
}
```

```
// callbackexecutor.capnp
@0xef16b623788085fa;

using Service = import "callbackservice.capnp";

interface Executor
{
    executeCallback @0 (status: UInt32, callback: Service.Callback) -> ();
}
```

This is the double-rpc approach. The service accepts a callback by its client which it might execute periodically or due to some event or whatever, but usually independant of the normal server program control flow. I e.g. got a target API used by the server in which you register ordinary function pointers as callbacks which will then be asynchronously executed in *some* other thread we got no control over.

The client implementation is straightforward.
```cpp
//client.cpp
#include "callbackservice.capnp.h"
#include <capnp/ez-rpc.h>
#include <kj/debug.h>
#include <math.h>
#include <iostream>

class CallBackfunction final: public Callback::Server {
public:
    virtual ::kj::Promise<void> call(CallContext context) override 
    {
        auto status = context.getParams().getParam();
        std::cout << "Status by server " << status << std::endl;
        return kj::READY_NOW;
    }
};

int main(int argc, const char* argv[]) {
    if (argc != 2) {
        std::cerr << "usage: " << argv[0] << " HOST[:PORT]" << std::endl;
        return 1;
    }

    capnp::EzRpcClient client(argv[1], 5923);
    auto& waitScope = client.getWaitScope();

    // Request the bootstrap capability from the server.
    Service::Client cap = client.getMain<Service>();

    auto req = cap.registerCallBackRequest();
    req.setCallback(kj::heap<CallBackfunction>());
    req.send().wait(waitScope);

    std::cout << "Set callback" << std::endl;

    kj::NEVER_DONE.wait(waitScope);

    return 0;
}
```

However, the server implementation is not. The callback is propagated to CallBackExecutorImpl::call, but the send call in this function shows that apparently the callback object lost its validity. Albeit, no exception is thrown, nor is the execution of the callback on the remote site actually triggered.

```server.cpp
#include "callbackexecutor.capnp.h"
#include "callbackservice.capnp.h"

#include <kj/debug.h>
#include <kj/async-io.h>
#include <capnp/ez-rpc.h>
#include <capnp/message.h>
#include <iostream>
#include <thread>
#include <mutex>
#include <chrono>

class CallBackExecutorImpl : public Executor::Server
{
    ::kj::Promise<void> executeCallback(ExecuteCallbackContext context) override 
    {
        auto callback = context.getParams().getCallback();
        auto status = context.getParams().getStatus();

        auto req = callback.callRequest();
        req.setParam(status);
        req.send();

        return kj::READY_NOW;
    }
};

class SomeExternalCaller
{
public:
    static SomeExternalCaller* m_instance;
    static SomeExternalCaller* getInstance()
    {
        if (!m_instance)
        {
            m_instance = new SomeExternalCaller();
        }
        return m_instance;
    }

    SomeExternalCaller()
    {
        m_thread = std::thread(&SomeExternalCaller::run, this);
    }

    ~SomeExternalCaller()
    {
        if (m_thread.joinable())
        {
            m_thread.join();
        }
    }

    void setCallback(Callback::Client callback)
    {
        std::lock_guard<std::mutex> lock(m_callbackMutex);

        std::cout << "Setting callback" << std::endl;
        m_callback = std::make_shared<Callback::Client>(callback);
    }

private:

    void callCallback(uint32_t status, Callback::Client callback, kj::WaitScope& scope)
    {
        auto req = m_executorClient->executeCallbackRequest();
        req.setCallback(kj::mv(callback));
        req.setStatus(status);
        req.send().wait(scope);
    }

    void run()
    {
        m_rpcClient = std::make_unique<capnp::EzRpcClient>("127.0.0.1:12345");
        m_executorClient = std::make_unique<Executor::Client>(m_rpcClient->getMain<Executor>());
        auto& scope = m_rpcClient->getWaitScope();

        std::cout << "Starting thread" << std::endl;

        while (true)
        {
            using namespace std::chrono_literals;

            std::lock_guard<std::mutex> lock(m_callbackMutex);

            if (m_callback.get())
            {
                callCallback(0, *m_callback, scope);
            }
            std::this_thread::sleep_for(1s);
        }
    }

    std::mutex m_callbackMutex;
    std::shared_ptr<Callback::Client> m_callback;

    std::unique_ptr<capnp::EzRpcClient> m_rpcClient;
    std::unique_ptr<Executor::Client> m_executorClient;
    std::thread m_thread;
};

SomeExternalCaller* SomeExternalCaller::m_instance = nullptr;

class ServiceImpl : public Service::Server
{
    ::kj::Promise<void> registerCallBack(RegisterCallBackContext context) override
    {
        std::cout << "Registering callback" << std::endl;

        // Yes, singletons are ugly. Yet we are forced to use 
        // one in the actual target project, because all we get
        // is some callback executed in *some* other thread
        // we got no control over.
        auto caller = SomeExternalCaller::getInstance();

        caller->setCallback(context.getParams().getCallback());

        return kj::READY_NOW;
    }
};

int main(int argc, const char* argv[]) {
    if (argc != 2) {
        std::cerr << "usage: " << argv[0] << " ADDRESS[:PORT]"
            << std::endl;
        return 1;
    }

    capnp::EzRpcServer server(kj::heap<ServiceImpl>(), argv[1], 5923);

    std::thread executorThread([]() {
        capnp::EzRpcServer callbackExecutorServer(kj::heap<CallBackExecutorImpl>(), "127.0.0.1", 12345);
        auto& waitScopeCallbacks = callbackExecutorServer.getWaitScope();
        kj::NEVER_DONE.wait(waitScopeCallbacks);
    });

    auto& waitScope = server.getWaitScope();
    kj::NEVER_DONE.wait(waitScope);

    if (executorThread.joinable())
    {
        executorThread.join();
    }
}
```

**Comment by kentonv** [comment]
Hi @apriori,

In your code, it looks like this is happening:

1. The main thread receives a `Callback` capability, and stores it into a mutex-protected variable.
2. The `SomeExternalCaller` thread loads the `Callback` capability out of the mutex-protected variable.
3. The `SomeExternalCaller` thread connects to the executor thread and passes the `Callback` capability to it over RPC.
4. The executor thread receives the capability and then attempts to call the callback.

Unfortunately, this won't work. The problem is that between step 1 and 2, you've transferred the capability across threads without using an RPC call. The capability received by the main thread can only be transferred to other threads via RPC. It cannot simply be stored to a variable and loaded in another thread.

In order to pass capabilities between threads, you're going to need to take one of two approaches:

1. Have all of your threads run Cap'n Proto RPC servers. You can't use a separate "executor" thread; it has to be the thread that actually expects to make the call. The KJ event loop has to be running for the thread to receive events. This may or may not fit with your programs design.
2. You could have each other thread create an EzRpcClient and connect back to the main thread only when an event occurs. So, you create the client, connect to the main thread, ask for the callback capability, call it, and then destroy the EzRpcClient, all in one shot. This way, you don't need the thread to be running a KJ event loop at all times, only when it needs to make a callback.

**Comment by apriori** [comment]
Hi @kentonv,

thank you very much for your further help. I now went with approach no. 2 which suits my problem in the best way, because the asynchronous are of the type "fire and forget".
Just poke me, if you want to have the source to maybe transform it into an official example.
