### ISSUE TITLE
Specify compiled file

### ISSUE THREAD

**Issue by serboctor** [capnproto/capnproto#598]
In `capnp compile` we can only specify the output directory, and the generated file by default has the same name as the capnp file. This is fine if you're compiling one capnp file. But in my case, I am compiling several files in the same run to resolve imports and dependency which makes it hard to predict the output file's name.
for example if run `capnp compile -olua  car.capnp backup.capnp store.capnp`, the output is generated at `backup_capnp.lua` and it will contain all the compiled schemas not just backup.capnp. It would be nice if we can specify the output file name.

**Comment by serboctor** [comment]
I've just realized that it generates more than one file, once the file reaches 17003 lines it generates a new one. Is there any way to make the generated output in just one file? with the current behaviour, it is very hard to predict the names of the generated files and which file will contain which objects.

**Comment by kentonv** [comment]
The problem is that most code generators generate a different output file for each input file. Some generators actually generate multiple files for each input -- for example, the C++ generator generates a `.h` file and a `.c++` file for each input `.capnp` file. So, how would you specify the names of each of these? This seems difficult to do on the command line.

I'm not familiar with the Lua generator and I'm surprised that it generates only one output file even for multiple inputs.

**Comment by serboctor** [comment]
Cool..thanks for the prompt reply.
