### ISSUE TITLE
::bind() error was flushed by tostring() on windows platform

### ISSUE THREAD

**Issue by nneesshh** [capnproto/capnproto#601]
kj/async-io-win32.c++ line 506
    "KJ_WINSOCK(::bind(sockfd, &addr.generic, addrlen), toString());"

if ::bind raise an error, but the toString call GetLastError first, so KJ_WINSOCK can't prompt the right error.
change code to 
"    kj::String s = toString();
     KJ_WINSOCK(::bind(sockfd, &addr.generic, addrlen), s.cStr());
"
can resolve the problem, though it is not so elegant.

**Comment by kentonv** [comment]
Hi @nneesshh,

What you describe is actually a bug in KJ_WINSOCK.

The parameters to the macro are not supposed to be evaluated unless an error occurs. So moving the `toString()` call to the previous line would be bad, because it would mean `toString()` is called even when there is no error, wasting CPU cycles.

But KJ_WINSOCK should be calling GetLastError() *before* it evaluates those parameters.

It appears that I've accidentally fixed this bug in #596, where I refactored the Windows call macros a bit. So as soon as that's merged, this should no longer be a problem.

**Comment by kentonv** [comment]
The fix for this has been merged.
