### ISSUE TITLE
Why does the Windows build have to be compatible with Wine, when there is also a Linux build?

### ISSUE THREAD

**Issue by G-glop** [capnproto/capnproto#640]

**Comment by kentonv** [comment]
Hi @G-glop,

Two reasons:

1. Since my workstation runs Linux, the easiest way for me to test that my changes to Cap'n Proto work in Windows is to run them under Wine. I can iterate on changes much faster in my familiar Linux development environment than I can in a Windows VM. For example, I developed async-io-win32.c++ and filesystem-disk-win32.c++ mostly on my Linux workstation.

2. If someone builds a program using Cap'n Proto and only releases a Windows version of that program, I want the program to have a chance of working under Wine.

BTW, the issue tracker is not the best place to ask questions. Things filed here should be actionable bugs. Try posting on the Cap'n Proto discussion group instead: https://groups.google.com/group/capnproto
