### ISSUE TITLE
Throwing destructors

### ISSUE THREAD

**Issue by zajo** [capnproto/capnproto#658]
From the documentation:

> When Cap’n Proto code might throw an exception from a destructor, it first checks std::uncaught_exception() to ensure that this is safe

This makes Cap'n Proto types incompatible with `std::make_shared`. Secondly, see [Sutter](http://www.gotw.ca/gotw/047.htm). Thirdly, I should be able to get rid of any object I no longer need, it's not a good idea to have it stick to my fingers like chewing gum. :)

**Comment by zajo** [comment]
Thank you for the detailed reply.

> If a panic occurs in destructor logic, then there in no other option except to throw from the destructor.

I don't know what "panic" means. Proper use of exceptions is to enforce postconditions, not to panic. Specifically, failure to write data to a file is not reason to panic...

> Saying "don't throw from destructors" is tantamount to saying "don't have bugs in destructors"

...nor it indicates a bug in the program. If you have detected a logic error (bug), the last thing you want is to start unwinding the stack and calling destructors.

> You are not expected to catch KJ exceptions

The only reason C++ exceptions are thrown is to allow the program to catch them and to recover from a failure.

Destructors should not be allowed to fail. Logically, if the user wants the object gone (which he does if the destructor is being executed), the object shouldn't be allowed to say "nuh-uh!" :) It should release everything it has acquired in the constructor and go away.

> Unfortunately, many standard library classes like shared_ptr bake in the idea that destructors shouldn't throw.

That the C++ standard "bakes" that idea should make you stop and think, I think. :)

**Comment by kentonv** [comment]
> I don't know what "panic" means.

"Panic" is used in many languages to mean what I described: A way to bail out of execution without aborting the whole process. Rust and Go, for example, provide a "panic" function that you would use instead of "abort()". Like exceptions, panics can be caught somewhere up the stack to allow for fault-tolerant recovery.

So, KJ uses exceptions in the way Rust and Go use panics. Note that neither Rust nor Go claim to support "exceptions", but their "panics" do stack-unwinding much like C++ exceptions do.

> If you have detected a logic error (bug), the last thing you want is to start unwinding the stack and calling destructors.

What is the alternative? If your alternative is aborting, then I **strongly** disagree. Aborting on logic errors is *not acceptable* for interactive servers that handle requests for multiple users at once. Aborting the process will unnecessarily fail out all other in-flight requests and make the server unavailable for some period of time, damaging your SLA. If a client can trigger such an abort reliably, then it may enable a DoS attack.

But it's even worse than that. If you tell programmers that their only recourse on logic errors is to abort, but that they need to minimize aborts because they will ruin your SLA, then inevitably programmers will do something far worse: They will resort to logging a message to stderr and then trying to continue without aborting, e.g. by returning some sort of a default value. This can lead to incorrect results, data corruption, and security problems.

On the other hand, if the programmer has an easy way to panic -- failing only the current request -- then they can freely panic whenever they detect any hint of confusion. Programmers will then tend to write many more checks, which is a great thing, as problems get caught much more quickly.

In fact, with a reliable, fault-tolerant "panic", it becomes perfectly acceptable to panic on invalid input, even when that input could come from a malicious client. This is fine since the panic only aborts the malicious client's request, and not any others. Making it easier for programmers to validate input means they are more likely to do so, which is a good thing.

> > You are not expected to catch KJ exceptions
>
> The only reason C++ exceptions are thrown is to allow the program to catch them and to recover from a failure.

You cut off the second part of my sentence: "unless you are specifically implementing some form of fault tolerance."

> Destructors should not be allowed to fail.

Again, you're saying that destructors should not be allowed to have bugs. It would be wonderful if destructors didn't have bugs, but it's an impossible ideal. If a critical logic error is detected in a destructor, it still needs to be reported. Silently ignoring errors leads to data corruption and security problems.

> That the C++ standard "bakes" that idea should make you stop and think, I think. :)

The C++ standard designed exceptions to be used as part of a program's logical API, in which exceptions are expected to be caught and handled even in situations where nothing went "wrong". KJ does not use them for that purpose. The C++ standard has no concept of a "panic". However, a "panic" construct is extremely valuable for writing reliable servers. Exceptions give us most of what we need, so we use them to implement panics. There are a few rough edges, which we live with.

To be clear, there is no chance that I will change my mind on this. Many years of experience across multiple companies (Google, Sandstorm, Cloudflare) handling large-scale server infrastructure has made me quite certain of this philosophy.

**Comment by zajo** [comment]
> Again, you're saying that destructors should not be allowed to have bugs.

No, I am saying that the correct postcondition for a destructor is that the object has been destroyed. I'm further saying that in a correctly written C++ program it sholud not be possible for a destructor to fail to establish that postcondition.

When you have logic errors all bets are off: not being able to destroy an object may be the least of your worries. You have no way of knowing, because if you've made a logic error, that may invalidate any other logic your program rests on. For example, continuing to handle user requests could lead to all of your user data being compromised.

> In fact, with a reliable, fault-tolerant "panic", it becomes perfectly acceptable to panic on invalid input, even when that input could come from a malicious client.

Something tells me we're not on the same page about what is a logic error. It is often a logic error to not throw on invalid input.

> Many years of experience across multiple companies (Google, Sandstorm, Cloudflare) handling large-scale server infrastructure has made me quite certain of this philosophy.

As opposed to Sutter, eh? :)

Your philosophy is generally correct, the disagreement is only over throwing exceptions in C++ destructors. I'll leave you with this:

```
foo::~foo() {
  ....
  if( error_detected && !std::uncaught_exception() )
    throw error();
}

bar::~bar() {
  try {
      foo x;
  } catch( error & ) {
    //Important error handling code here
  }
}
```

If `~bar()` is being executed due to exception stack unwinding, it will not see the error from `~foo()` even though it should. To quote Sutter, "`std::uncaught_exception` is deceptively close to being useful."

**Comment by kentonv** [comment]
> No, I am saying that the correct postcondition for a destructor is that the object has been destroyed.

I disagree. I think the postcondition of a destructor includes all postconditions of the object itself.

> When you have logic errors all bets are off: not being able to destroy an object may be the least of your worries. You have no way of knowing, because if you've made a logic error, that may invalidate any other logic your program rests on. For example, continuing to handle user requests could lead to all of your user data being compromised.

I disagree. In practice, the vast majority of server logic is not operating on globals. Hence, the vast majority of thrown exceptions occur outside of any global critical sections. Even if an exception occurs inside a critical section, the chance that it indicates global corruption is still small. Meanwhile, it's of course entirely possible for global corruption to happen *without* any error being thrown.

Therefore, in my opinion, saying "You can't handle more request after an exception because globals may have been corrupted." makes barely more sense than saying "You can't handle two requests with the same server because the first request may have silently corrupted globals.". The latter argument is perfectly valid, but impractical -- forking servers are too inefficient. The former argument is similarly impractical, because it argues that you simply can't recover gracefully from errors, which harms availability.

In practice, we have to accept some amount of risk in order to get something immensely valuable in return (performance and availability).

It's always possible to wrap your critical sections in a try/catch which aborts, if there's a real risk of corruption. (I do this in some places.)

Incidentally, in Rust, if you panic while holding a mutex lock, the mutex becomes "poisoned", and any further attempts to lock it will panic as well. This ostensibly protects against global inconsistent state, though it creates a new problem is that your server may be left inoperable until restarted. I have mixed feelings about it.

> Something tells me we're not on the same page about what is a logic error. It is often a logic error to not throw on invalid input.

I was specifically arguing for exceptions as an alternative to abort() -- i.e. "panic" in the Rust/Go sense. By "logic error" I think I mean something like "assertion failure", i.e. when you reach a state that "shouldn't be possible".

Clearly, abort()ing on invalid input is not a good idea. But panicking is arguably OK. So my argument is that using exceptions as a form of panic makes it safe to treat invalid input like an assertion failure.

The other common notion of exceptions is as "checked exceptions", where you explicitly declare what exceptions are throwable in your API contract. I think this notion is popular among language theorists, and is the notion C++ was written to, but fails badly in practical use.

It's not really clear to me what model of exceptions you're arguing for. What do you feel should happen when you detect a logic error in a destructor? I assumed you want to abort() because I'm not sure what else is possible.

> As opposed to Sutter, eh? :)

Yes, I trust my experience over others' authority. And anyway, does Sutter actually write servers? It's easy for people who stay stuck in the lower-level implementation details to lose touch with the higher-level impact of their design decisions.

>     [... example code ...]
>
> If ~bar() is being executed due to exception stack unwinding, it will not see the error from ~foo() even though it should. To quote Sutter, "std::uncaught_exception is deceptively close to being useful."

1. I don't think your example is realistic. Why would you have a try/catch in a destructor, with the catch block containing "important error handling code"? This does not look like a typical fault tolerance pattern. I've never written code that looks like that.
2. KJ uses `std::uncaught_exceptions()` (plural) instead of `std::uncaught_exception()` to avoid this problem. Even before C++17 standardized this function, KJ was implementing it via internal APIs of libstdc++.

**Comment by kentonv** [comment]
> You're not using terminology correctly. Objects don't have postconditions, functions do.

Objects do have postconditions. For example, a buffered file stream has the postcondition that the stream buffer has been flushed to disk. If the buffer cannot be flushed, this is a very serious error (data loss!). In this circumstance, it is *essential* that the overall task does not report success when such an error has occurred.

What do you propose should happen in this case?

> You can use assert to signal logic errors, but logic errors occur independently from asserts.

What I meant to say is that, conceptually, a logic error is "the kind of error you might assert-fail on" -- whether you explicitly do or not is beside the point. It's not practical to write explicit checks for every possible logic error. We focus on asserting where we perceive a risk of bugs. (Though for nullability in particular, I prefer to enforce this in the type system with `kj::Maybe`...)

> My only point is that it is always a bad design choice if destroying an object could possibly fail.

OK, but you still haven't said what should happen instead, if a serious error is detected in a destructor. Please explain what the alternative is.

**Comment by zajo** [comment]
> Objects do have postconditions. For example, a buffered file stream has the postcondition that the stream buffer has been flushed to disk.

Yes I got it, I'm just saying that postconditions are attributed to code (e.g. a function), not to objects. The proper terminology is that in your design, the destructor has the postcondition that it successfully wrote all data to disk (not merely that it sucessfully destroyed the object.)

> OK, but you still haven't said what should happen instead, if a serious error is detected in a destructor. Please explain what the alternative is.

Let's ignore exceptions for a moment and talk about `close` instead. In terms of postconditions, you want to know that no data got lost _or_ `close` reports an error. But remember, Linus doesn't care about you. :) This is an excerpt from the documentation of `close` on Linux (which I assume is also POSIX-compliant):

_"A successful close does not guarantee that the data has been successfully saved to disk, as the kernel defers writes. It is not common for a file system to flush the buffers when the stream is closed. If you need to be sure that the data is physically stored use fsync(2). (It will depend on the disk hardware at this point.) "_

Does this mean that you should always `fsync` before `close`? I wouldn't recommend that, for the following reasons:

1. It is slow.

2. A function that writes data to a file but lacks the FD of the file's directory is unable to ensure that we have a good file after `fsync` and `close`: _"Calling fsync() does not necessarily ensure that the entry in the directory containing the file has also reached disk. For that an explicit fsync() on a file descriptor for the directory is also needed."_

3. Fault tolerance is achieved by being tolerant to failures, including file system failures, including power failures, not by merely responding to a subset of the possible failures. As you know, this reaches way beyond software design alone.

To answer your question, the correct design reflects the fact that the only _meaningful_ postcondition of `close` is that the FD is closed, which is guaranteed regardless of the return value:

1. In the destructor, call `close`. Either ignore its return value or log failures. Ignore a failure to write to the log, because the writing of the data may fail after `close` has returned, in which case the log won't document the data loss anyway.

2. Except if the class that holds the FD implements buffering, provide access to the FD so that the user can use any relevant function (e.g. `fsync`) from any API (not all FDs are files).

**Comment by kentonv** [comment]
OK, it seems my using of flushing disk buffers as an example has distracted from my argument by leading to a discussion of fsync semantics. More on that below.

But it seems the general answer you are proposing is: "Problems detected in destructors should be ignored or logged, but need not be reported to the caller and should not prevent the task from completing and reporting success. If the problems really are critical, the caller needs to call a separate method to check for problems before destroying the object."

I don't accept this, because I don't believe it's practical to design APIs that anticipate how the implementation might fail. An abstract interface may be designed without any expectation that an implementation would be backed by a file, and therefore may not have any `commit()` method.

Or put more generally, what I've been saying all along: Destructors contain code. Code can fail. I do not believe it's possible to broadly guarantee that code in destructors will only have failure modes that are safe to ignore. I will agree that they should avoid failing if possible, that they are probably less likely to fail than other code, and that their API contract should assume no failures. But, I don't think it makes sense to say they won't ever fail, and I don't think either "ignore" or "abort" are acceptable answers for all cases where they do fail.

I also see no fundamental reason why destructors need to be prevented from throwing, except for the C++ language standard's mistake in the way it handles secondary faults. It should merge the errors, but instead it aborts. I don't understand why the C++ standard has decided to push in an impossible direction (insisting that destructors never fail) instead of simply remedying this mistake, which would be easy.

--------

_Aside regarding fsync:_

_Yes, I'm aware that the OS doesn't fsync() on close(). It does, however, guarantee that other applications running on the same system can see the data that was written, and the only way data will be lost is in the case of a system-wide failure. This is an important guarantee, because it means that other local processing can proceed under the assumption that the data was written -- because any such system-wide failure would stop all those other processes as well. Even a human user is likely to notice if their machine crashes in the next 30 seconds, and therefore writes may have been lost. It's only before responding to a remote machine over a network that we really need to think about whether data has reached physical disk._

_Accepting this model and skipping fsync() is very different from ignoring errors like ENOSPC or EACCESS or EBADF. The former is acceptable, the latter is not._

**Comment by zajo** [comment]
> Destructors contain code. Code can fail. I do not believe it's possible to broadly guarantee that code in destructors will only have failure modes that are safe to ignore.

It's more subtle than this. I think you're treating this as an argument over whether or not destructors should ignore failures. I agree that it is a bad idea to ignore failures. I don't know another programmer who cares about error handling more than I do.

The subtlety stems from the fact that error conditions depend on context. The correct postcondition for a `file_open` function is that the file was opened successfully. It should throw if it fails to establish that postcondition, but it is not true that a failure reported by `file_open` shoul be considered a failure in all contexts that call it, because the file might be optional.

When is it correct to wrap the call to `file_open` in a `try...catch(...)`? When in that context, the failure to open the file does not prevent the function from doing its job or, more formally, from establishing its postconditions.

So, my argument is not that it's okay to ignore failures in destructors, but that 1) the job of any destructor is to destroy the object -- nothing more, nothing less -- and 2) it is not possible for a destructor to fail in doing its job, because releasing resources _should_ be always possible -- and generally it _is_ always possible, except when one encounters bad designs like throwing destructors. :)

> it seems my using of flushing disk buffers as an example has distracted from my argument by leading to a discussion of fsync semantics

I suppose this means that you're granting me that I'm right in this particular instance, but my experience is that this is typical. The reasons why `fsync`/`close` have such complicated semantics are surprisingly universal.

>I also see no fundamental reason why destructors need to be prevented from throwing, except for the C++ language standard's mistake in the way it handles secondary faults

Even if I agreed with your assessment (I don't), that part of the C++ standard will not change because such core language changes will break a lot of code. The reality is that even if you were right, you're creating issues for your users, for no good reason at all.

>ENOSPC or EACCESS or EBADF

`EBADF` should be an `assert`, helping the programmer detect logic errors is a good thing. `ENOSPC` or `EACCESS` could reasonably occur after a successful call to `close`.

**Comment by kentonv** [comment]
@katreniak Are you suggesting a flag that removes the `noexcept(false)` declaration from destructors, or are you suggesting a flag that actually prevents destructors from throwing? The former is easy, the latter seems impossible -- KJ never _intentionally_ throws from a destructor, but there's no feasible way to guarantee that code called in a destructor won't throw except to wrap every destructor in a try/catch.

**Comment by katreniak** [comment]
I was thinking that the compilation flag shall do both
- removes `noexcept(false)`
- prevents destructors from throwing

Yes, the code in destructors would need to be wrapped inside `try/catch` blocks hidden behind some macros. Exceptions from KJ_ASSERT would abort, exceptions from KJ_REQUIRE would be logged and swallowed. The assert / require flag could be carried e.g. in `kj::Exception`. Most destructors are empty, so it may not be too invasive in number of changed lines. 

Kind regards
 Brano
