### ISSUE TITLE
cmake: Changing libraries prefix for cross compiling

### ISSUE THREAD

**Issue by ytmhub** [capnproto/capnproto#664]
I wish to cross compile a project that uses capnproto (via Yocto), and I need to configure it in a way that uses the native capnp tool and the target specific libraries.

I built both native and target specific packages for [capnproto](http://cgit.openembedded.org/meta-openembedded/tree/meta-oe/recipes-devtools/capnproto/capnproto_0.6.1.bb?h=master) , the only problem is changing the libraries path from the native recipe's sysroot to the target sepcific one when compiling a project that uses it.

**Comment by kentonv** [comment]
Hi, sorry, I'm not sure what you're asking for here. Cap'n Proto is built with autotools, which has extensive options for cross-compiling. Additionally, we've added the configure option `--with-external-capnp` for use when cross-compiling, which instructs the build to use the system-installed `capnp` tool rather than the one that is produced by the build itself.

What is it you need exactly?

**Comment by ytmhub** [comment]
Sorry if I was unclear. I wanted to know if this can be done via cmake, which is what the upstream Yocto recipe for capnproto on meta-openembedded uses.
If the option for cross compiling is already implemented as you say when building with autotools, I'll simply write a new recipe that uses it instead of cmake
Thanks.

**Comment by kentonv** [comment]
Oh sorry, I missed "cmake" in the title. Unfortunately I don't know how the cmake build works.

**Comment by kentonv** [comment]
And yeah, the autotools build is the official build, and is the one that should be used by packagers. The cmake build was added by contributors for the purpose of more easily integrating with dependent projects that use cmake, and for supporting MSVC. Other than those two cases, people should probably stick to the autotools build.
