### ISSUE TITLE
Why async-io always returns ok on windows?

### ISSUE THREAD

**Issue by lcy03406** [capnproto/capnproto#667]
I'm reading async-io-win32.c++. There are lots of code such as
`      if (error != ERROR_IO_PENDING) {
        KJ_FAIL_WIN32("ConnectEx()", error) { break; }
        return kj::READY_NOW;
}`
or
`      if (error != ERROR_IO_PENDING) {
        KJ_FAIL_WIN32("AcceptEx()", error) { break; }
        return Own<AsyncIoStream>(kj::mv(result));  // dummy, won't be used
}`
Why don't they just throw?
How should I check the status and make sure not use the returned dummy?

**Comment by kentonv** [comment]
Short answer: They will throw. The code you're looking at doesn't do what you think it does, but it's implementation details that you don't need to worry about. Keep in mind that `connect()` and `accept()` usually fail asynchronously -- that is, they return Promises that eventually fail. You need to wait on the promise to get the exception.

Longer answer: KJ is designed to work even if you compile it with C++ exceptions disabled. When exceptions are enabled, KJ_FAIL_WIN32 will throw an exception. In this case, you can ignore everything after KJ_FAIL_WIN32 because none of that will run.

However, if exceptions are _disabled_ (using a compiler flag), then things get more complicated. In this case, instead of throwing, KJ falls back to the "recovery block" -- the block appearing immediately after the exception macro. In this case, the block is `{ break; }`. If there were no recovery block provided, or if the recovery block were empty, then the process would abort. Obviously, we don't want to abort the process on connection failures, hence a recovery block is provided. The block `{ break; }` causes execution to continue on the next line after the block. In this case, that line is `return kj::READY_NOW;`. It may look like this is returning success -- but it isn't! The reason is that KJ did another thing when the error occurred -- it recorded, in the background, that it tried to throw an exception but that it couldn't because exceptions are disabled. Once control returns from the event handler back to the Promise framework, KJ looks and notices that an exception was thrown. In this case, it ignores what was returned by the event handler and instead marks the Promise as failed. So, the `kj::READY_NOW` is ignored here and instead the promise fails with an exception. This is an asynchronous exception, of course, so you'll only see it if you wait on the promise or call `.catch_()` to register an exception handler. But, again, none of this applies if you have exceptions enabled.

I strongly recommend enabling exceptions when using KJ.
