### ISSUE TITLE
Is it possible to load a binary schema file?

### ISSUE THREAD

**Issue by lcy03406** [capnproto/capnproto#673]
I want to use capnproto with some lua binding and don't want to statically generate c++ code into my main program. But I don't want to expose human readable .capnp files in my app package. Can I generate a binary form of schema and load it in runtime? And can I use a separate tool to generate the schema binary so my main program which load the schema does not need libcapnpc?

**Comment by kentonv** [comment]
Yes, a compiled Cap'n Proto schema can be represented using `schema.capnp`:

https://github.com/capnproto/capnproto/blob/master/c++/src/capnp/schema.capnp

You can generate this format using the `capnp` tool, like:

    capnp -o/bin/cat myprotocol.capnp > bundle.bin

This creates a file `bundle.bin` which is of type `CodeGeneratorRequest`, as defined in `schema.capnp`. You could create further tools that pick this apart into whatever pieces you actually need at runtime.

I don't know much about the Lua bindings so I don't know if they support loading from the binary format at runtime. If not, you'll have to talk to the lua-capnp developers about supporting that.

**Comment by jtbandes** [comment]
Hi,
Just wanted to ask whether `CodeGeneratorRequest` is still the recommended format for working with binary schemas in 2023 (possibly including a set of imports as well)? Is schema.capnp stable enough that the format produced by `capnp -o/bin/cat X.capnp` can be relied upon to be parsed by future versions of capnp parsers? (Context is that we are looking to add capnp struct and schema encodings to the list of encodings here: https://mcap.dev/specification/appendix.html)

**Comment by jon-chuang** [comment]
Oops:
```
> capnp compile -o/bin/cat schema.capnp > out.bin
> capnp convert binary:json schema.capnp Node < out.bin 
{ "id": "0",
  "displayName": "",
  "displayNamePrefixLength": 0,
  "scopeId": "0",
  "nestedNodes": [{"name": "schema.capnp", "id": "12195682960037147353"}],
  "annotations": [],
  "isGeneric": false,
  "file": null }
*** ERROR CONVERTING PREVIOUS MESSAGE ***
The following error occurred while converting the message above.
This probably means the input data is invalid/corrupted.
Exception description: expected ref->listRef.elementSize() == ElementSize::BYTE [(can't stringify) == (can't stringify)]; Schema mismatch: Message contains list pointer of non-bytes where text was expected.
Code location: capnp/layout.c++:2468
*** END ERROR ***
```

**Comment by jon-chuang** [comment]
Seems to work at least:
```
> capnp compile -o/bin/cat schema.capnp > out.bin
> capnp convert binary:text schema.capnp CodeGeneratorRequest < out.bin 
( nodes = [
    ( id = 12195682960037147353,
      displayName = "schema.capnp",
      displayNamePrefixLength = 7,
      scopeId = 0,
      nestedNodes = [
        ( name = "Node",
          id = 16610026722781537303 ),
        ( name = "Field",
          id = 11145653318641710175 ),
        ( name = "Enumerant",
          id = 10919677598968879693 ),
        ( name = "Superclass",
          id = 12220001500510083064 ),
        ( name = "Method",
          id = 10736806783679155584 ),
        ( name = "Type",
          id = 15020482145304562784 ),
        ( name = "Brand",
          id = 10391024731148337707 ),
        ( name = "Value",
          id = 14853958794117909659 ),
        ( name = "Annotation",
          id = 17422339044421236034 ),
        ( name = "ElementSize",
          id = 15102134695616452902 ),
        ( name = "CapnpVersion",
          id = 15590670654532458851 ),
        ( name = "CodeGeneratorRequest",
          id = 13818529054586492878 ) ],
      annotations = [
        ( id = 13386661402618388268,
          value = (text = "capnp::schema"),
          brand = () ) ],
      file = void,
      isGeneric = false )
```

**Comment by jon-chuang** [comment]
Also inlines all dependencies from multiple files. Perfect.

```
capnp compile --src-prefix="compat" -o/bin/cat compat/json-rpc.capnp > out.bin
capnp convert binary:text schema.capnp CodeGeneratorRequest < out.bin > out.txt
...
    ( id = 11815888814287216003,
      displayName = "json.capnp:Value",
      displayNamePrefixLength = 11,
      scopeId = 10302426802579725876,
      nestedNodes = [
        ( name = "Field",
          id = 16361620220719570399 ),
        ( name = "Call",
          id = 11590566612201717064 ) ],
      struct = (
        dataWordCount = 2,
        pointerCount = 1,
        preferredListEncoding = inlineComposite,
        isGroup = false,
        discriminantCount = 8,
        discriminantOffset = 0,
        fields = [
          ( name = "null",
            codeOrder = 0,
            discriminantValue = 0,
            slot = (
              offset = 0,
              type = (void = void),
              defaultValue = (void = void),
              hadExplicitDefault = false ),
            ordinal = (explicit = 0) ),
          ( name = "boolean",
...
```

**Comment by kentonv** [comment]
> Just wanted to ask whether CodeGeneratorRequest is still the recommended format for working with binary schemas in 2023 (possibly including a set of imports as well)?

Yes. This is unlikely to change.

> Is schema.capnp stable enough that the format produced by capnp -o/bin/cat X.capnp can be relied upon to be parsed by future versions of capnp parsers?

Yes. All changes made to schema.capnp since it was originally introduced (nearly 10 years ago!) have been designed to be forwards/backwards-compatible, and future changes will be as well.

**Comment by jtbandes** [comment]
I see that the docs mention this `displayName` is not guaranteed to be unique. What are the circumstances where a collision could arise (i.e. two identical displayNames within one CodeGeneratorRequest)? Is there a field/value that is both human-readable and guaranteed to be unique?

> `displayName = "json.capnp:Value",`

https://github.com/capnproto/capnproto/blob/f40441796d72c84b4e4adc6f830b7cc03b110796/c%2B%2B/src/capnp/schema.capnp#L33-L37

**Comment by kentonv** [comment]
There is explicitly no human-readable value that is guaranteed unique. Uniquely identifying types is the purpose of type IDs, which are 64-bit numbers. If a type doesn't declare a type ID explicitly, then its ID is based on a hash of the parent scope's ID plus the type name. The file scope must always have an explicit type ID.

This design was based on the observation that whenever you have a human-readable name for a thing, there is a chance you'll want to rename it at some point. But if Cap'n Proto schemas used human-readable names as canonical identifiers in order to decide whether two schemas refer to versions of the same protocol, then any such renames would introduce backwards-incompatibility. Inevitably, people would introduce renames anyway without realizing that it leads to a breakage, or they'd be stuck forever with names they no longer like.

Hopefully, developers do not have to use type IDs explicitly, because in any particular context, they have an alternative. For example, within the context of a particular build, imports can be resolved based on the local source tree, without needing to know the imported file's ID. But it's quite common that when copying a schema file into some other project's build, the import paths have to be adjusted, so these are not suitable as global identifiers.

The display name is intended to be useful for displaying messages to the user, where hopefully the user is able to figure out from their context what the file name means. But, it's not uncommon for two different builds of the same protocol (at different versions, or in different source trees) to have different display names for the same type. You must use the type ID to know if it's really the same type.
