### ISSUE TITLE
capnp kj issue Message did not contain a root pointer. maybe caused when handling byte orders

### ISSUE THREAD

**Issue by bwlee** [capnproto/capnproto#705]
Hi all, 
some strange issue I guess it maybe caused by network/host byte orders.

I have pack/unpack a struct correctly inside a function,  but when send packed message through NNG pub/sub protocol (using ipc method), when receiver got message, and unpack with same function, I got error message as below:  

terminate called after throwing an instance of 'kj::ExceptionImpl'
  what():  capnp/message.c++:99: failed: expected segment != nullptr && segment->checkObject(segment->getStartPtr(), ONE * WORDS); Message did not contain a root pointer.
stack: 0x7ffff7ad7978 0x7ffff7ad5cb7 0x7ffff7aaacb8 0x7ffff7a98d58 0x7ffff7a9005f 0x7ffff7aa911d 0x7ffff7aa8fbd 0x7ffff7aa8cc6 0x7ffff761557f 0x7ffff686a6ba 0x7ffff707d41d

the code I pack:

  ```
kj::Array<::capnp::word> words = ::capnp::messageToFlatArray(message);

  return words;
```
and send through nng pub socket

when message bytes received by nng sub socket, 
the code I unpack 

```

 int word_size = size / sizeof(capnp::word);  

  auto buf = kj::ArrayPtr<capnp::word>(reinterpret_cast<capnp::word *>(data), word_size);
  ::capnp::FlatArrayMessageReader message(buf);

```

Does the byte orders affected?   How can I change it ?

**Comment by kentonv** [comment]
Hi Bowen,

Cap'n Proto handles byte order for you. That is not the problem.

Most likely the bytes are being changed somehow it transit. This could be due to a bug in your code, or a problem with the transport layer. Since we can't see your code, it's hard to tell what the bug might be. I recommend that you write code that prints the exact bytes (e.g. as hex) on the sending and receiving end to verify that they are the same.
