### ISSUE TITLE
MallocMessageBuilder first segment zero-init problem

### ISSUE THREAD

**Issue by haelix888** [capnproto/capnproto#710]
(apologies is not the right place to ask Qs, can do stackoverflow instead)

I'm trying to use Capnp to serialise object into buffer that I fully own, and found the MallocMessageBuilder(kj::ArrayPtr<word> firstSegment) c-tor. I will make sure to never require more than the first segment so don't need any memory management. But I see destructor of this builder will zero the segment memory, which doesn't work in my design - in my design I'm invoked to serialise object and leave it there, i.e. the memory outlives the Builder. How can I achieve this? Do you recommend writing another Builder? On a related aspect - does the Builder tell me how many bytes it actually wrote to the segment? Thanks!

**Comment by kentonv** [comment]
Hi @haelix888,

For questions that aren't bug reports, generally it's best to ask on [the mailing list](https://groups.google.com/group/capnproto). Stack Overflow also works though you may want to explicitly ping me to make sure I see it (I think Stack Overflow has a built-in way to do this?).

> Do you recommend writing another Builder? 

Yes, you could do that, and it should be very easy.

Personally, my approach is usually to keep the MessageBuilder alive until I'm done with the message, but it's really up to you.

> does the Builder tell me how many bytes it actually wrote to the segment?

Yes, the `getSegmentsForOutput()` method returns an array of segment slices, each sized according to the amount of data actually written. When there's only one segment, it won't do any allocation.

**Comment by haelix888** [comment]
Thanks vm, makes sense. Small follow up Qs if I may:

1) it seems I'd implement something like FlatMessageBuilder, can I use that?
2) does writing my own builder to existing buffer (or using the Flat builder) avoid the requirement for the buffer to be zero initialised? I'm trying to understand where that requirement comes from, so as to ensure that I'm using the library properly. Thanks!

**Comment by kentonv** [comment]
> it seems I'd implement something like FlatMessageBuilder, can I use that?

Yeah, I guess you could. It will throw an exception if the message grows too large. Also note that the input array is expected to be zero'd in advance.

> does writing my own builder to existing buffer (or using the Flat builder) avoid the requirement for the buffer to be zero initialised?

No. Cap'n Proto needs the buffer to be pre-zero'd because otherwise it would just have to zero each object on allocation anyway. Since many memory allocators can efficiently provide already-zero'd memory, the implementation was designed to expect this in order to save time. (Also, if the buffer weren't zero'd in its entirety upfront, there'd be a pretty big risk of implementation bugs failing to zero out some part of the buffer and then leaking uninitialized data when the message is sent -- a big security problem!)
