### ISSUE TITLE
writeMessageToFd and writePackedMessageToFd should return bytes written like ::write()

### ISSUE THREAD

**Issue by thomasj02** [capnproto/capnproto#713]
I would like to write messages to a file using writeMessageToFd as described in the documentation so I can later mmap() the file. I would also like to periodically rotate the file (e.g., when it reaches a certain maximum size). Is there any way to tell how many bytes `writeMessageToFd` wrote to the file descriptor? It seems like that easiest way to expose this would be to return the bytes written the same way that write() does.

**Comment by kentonv** [comment]
Hi Thomas,

You can use `capnp::computeSerializedSizeInWords(messageBuilder) * sizeof(capnp::word)` to determine the number of bytes written. If `writeMessageToFd()` did not throw, it will always have written this amount.

Alternatively, you could also use `stat()` or `lseek(fd, 0, SEEK_CUR)` on your file descriptor to read back how large the file is. This might lead to simpler code since you won't have to keep a running count of the total size.
