### ISSUE TITLE
Improve `capnp -o` heuristics around colons in path name on Windows.

### ISSUE THREAD

**Issue by joonazan** [capnproto/capnproto#722]
`capnp compile -o C:/asd/fasd/plugin schemafile.capnp` is interpreted as language C and output directory `/asd/fasd/plugin`.

**Comment by kentonv** [comment]
Is this with 0.6.x or master? I think this is fixed at master, and 0.7 should be released... soonish.

**Comment by joonazan** [comment]
I looked into the source code and it seems that I have to use a second colon for it to work correctly. It would have been helpful if the error message would have been about something else than the output directory, which I did not intend to set.

A good solution could be to not accept paths starting with a slash on Windows, as they are rarely used. Why would you want a path that is absolute, except that it does not specify a drive?

**Comment by kentonv** [comment]
Ah hah, indeed...

https://github.com/capnproto/capnproto/blob/1ccd2dcb42ef883f4aebf60d90c803659200d6da/c++/src/capnp/compiler/capnp.c++#L388-L418

Hmm, what you propose would of course require guarding with `#ifdef _WIN32` since it would be the wrong thing on Unix.

Technically on Windows, a path starting with `\` is supposed to assume "the current drive". Then again, technically on Windows, every drive has a "current directory", such that specifying `X:foo` means "the file `foo` inside drive `X`'s current directory"... which we obviously don't support because it's nuts.

OK, I guess your suggestion sounds reasonable.
