### ISSUE TITLE
Json.flatten(prefix) should apply on union discriminator values not field name

### ISSUE THREAD

**Issue by RReverser** [capnproto/capnproto#737]
If you have a union with bunch of variants, then having both `$Json.flattten(prefix = "prefix.") $Json.discriminator(name = "name")` on the same structure should output `{"name":"prefix.foo"}`, `{"name":"prefix.bar"}`, etc. instead of `{"prefix.name":"foo"}`, `{"prefix.name":"bar"}`.

If someone wants to prefix discriminant itself, it's pretty easy to do so inline as part of discriminant name, while other way around prefix has to be currently repeated as `$Json.name` on each field.

**Comment by kentonv** [comment]
Hmm, I see the argument that the prefix should not apply to the discriminator name... but I don't see why it should apply to the value. What's the use case for prefixing the discriminator value when all possible values are going to have the same prefix? Seems redundant?

**Comment by kentonv** [comment]
Actually I'm not sure it's right to drop the prefix from the discriminator name, either. Consider:

    struct Foo {
      bar @0 :Bar $Json.flatten(prefix = "pfx.");
    }

    struct Bar $Json.discriminator(name = "type") {
      union {
        baz @0 :Baz;
        qux @1 :Qux;
      }
    }

In this case, it's clear that the discriminator is conceptually a member of Bar, and that all members of Bar must be prefixed when flattening into Foo.

Now, consider the inline union case:

    struct Foo {
      bar :union $Json.flatten(prefix = "pfx.") $Json.discriminator(name = "type") {
        baz @0 :Baz;
        qux @1 :Qux;
      }
    }

In this case, yes, you can argue that the discriminator shouldn't get prefixed, because if the developer really wants a prefix on the discriminator, they can just as easily modify the discriminator name directly. However, you can *also* argue the other way: if the developer only wants the prefix on the field names, they can reasonably easy add `$Json.name` on each field in order to set the prefix on each one, and remove it from the `$Json.flatten`. Admittedly, this is somewhat more tedious. However, since the separate struct case (first example above) clearly requires that the prefix be applied to the discriminator, I think we need to be consistent in the inline-union case.

**Comment by RReverser** [comment]
> Seems redundant?

Not if you have that union as part of another union, and so essentially have namespaces ending up with messages like `{"name":"NamespaceA.name1",...}`, `{"name":"NamespaceA.name2",...}`, `{"name":"NamespaceB.name1",...}`, ...

**Comment by RReverser** [comment]
> However, you can also argue the other way: if the developer only wants the prefix on the field names, they can reasonably easy add $Json.name on each field in order to set the prefix on each one, and remove it from the $Json.flatten. Admittedly, this is somewhat more tedious. 

Indeed, both ways have their arguments for and against. From my point of view, it's more important to allow the easiest way to prefix items for each particular case individually rather than try to make struct and union cases consistent. But I can see consistency as a valid target too, so if you have stronger preference towards it, feel free to close the issue.

**Comment by kentonv** [comment]
I do see your argument, but I think consistency is more important here -- plus, doing it the other way would significantly complicate the implementation, since the inline union case is actually transformed into the separate-struct case by the capnp compiler, and so JsonCodec doesn't see the two cases as different...
