### ISSUE TITLE
Loading schema at runtime

### ISSUE THREAD

**Issue by SirWindfield** [capnproto/capnproto#740]
I am currently in the need of some kind of server-client architecture similar to Google's Xi-Editor. Each plugin there communicates over RPC with the main application. My application has similar needs and I was hoping that I could use CapnProto for the RPC part. 
As written on the website, CapnProto uses shared memory access, so getting the information from the server to the clients should be incredibly fast. And since CapnProto has a Rust plugin I was curious on how it would work out. But I faced some problems:

Having plugins add new messages to standard JSON RPC is quite easy. But in the case of CapnProto it is a little bit harder to do. Plugins actually need to know the generated code from the library before they can even interact as simply listening to events like 'on.mouse.moved' won't work because they are in binary.
And having plugins add their own protocols is hard too, because the server actually needs a reference to the code before it knows how to decode the binary data it gets.  So I was wondering if it is possible to somehow convert the plugin's schema to a binary format, make the server ahve a method like `registerNewSchema` and send that schema file to the server over RPC. Then the server would load the schema during runtime. It should by then know how to decode the data. 

How to execute the data is another problem I'm still thinking about.

P.S.: Level 2 mentions that three way comm isn't implemented. Are multiple clients talking to one server three ways? Or would three way only happen if a client tries to communicate to another client (which is almost certain to happen within a plugin ecosystem that is based around passing messages to a lot of components)?

**Comment by kentonv** [comment]
Hi Sven,

Sorry for the delay in replying -- email overload.

There is indeed a binary format for schemas: https://github.com/capnproto/capnproto/blob/master/c++/src/capnp/schema.capnp

Many capnp code generators actually embed schemas in this format directly into the generated code, so that they are readily available in your program to be transmitted to peers. In C++ we have the `schema.h`, `schema-loader.h`, and `dynamic.h` APIs which are useful for manipulating types based on schemas received at runtime (not compiled in). I think the Rust implementation has similar APIs though I haven't checked.

However! With all that said, I'm not sure the situation you describe actually needs any of that. Because, in fact, it is *not* strictly necessary to know the complete schema of a message in order to do things with it. If a server is merely acting as proxy or router between other components, it need not know the full schema of the types it is transmitting. Cap'n Proto is designed such that if you receive a message and then copy parts of it into another message, the copy doesn't lose any information -- even if the message contains data for which you don't have the schema. For example, the message can contain new fields from a future version of the protocol (which you don't know about), or the message could contain `AnyPointer` fields containing arbitrary types you don't know about. These will be correctly copied without losing data.

It's only the *endpoints* of the communication that really need to know the schema, as they need to produce and consume the messages. These endpoints are almost certainly going to compile in the generated code, because it doesn't make sense to write code that produces or consumes a message without knowing what the message type is when the code is written.

The only place where the dynamic / schema APIs are really needed is if you need to perform some sort of generic translation between Cap'n Proto format and some other format (e.g. JSON). That's a case where you can write code that really is designed to handle arbitrary yet-to-be-defined messages.

> Level 2 mentions that three way comm isn't implemented. Are multiple clients talking to one server three ways? Or would three way only happen if a client tries to communicate to another client (which is almost certain to happen within a plugin ecosystem that is based around passing messages to a lot of components)?

3-way communication means specifically that the server can introduce two clients to each other in such a way that the clients form a direct connection, and can then communicate without involving the server. If you are OK with proxying communications through the server, then there's no need for 3-party handoff. (Indeed, the reason 3ph hasn't been implemented is because every use case we've seen so far was just fine with proxying.)

**Comment by kentonv** [comment]
Closing because this doesn't appear to be an actionable issue, but feel free to continue the conversation on the mailing list: https://groups.google.com/group/capnproto
