### ISSUE TITLE
capnproto - serialize a xml file 

### ISSUE THREAD

**Issue by ronen-yacobi** [capnproto/capnproto#764]
I am feeling really comfortable with using canproto. I'm an using it to distribute configuration on different architectures. The problem is that the configuration  have now quite small data to serialize but in the future the data will grow and need to be prepared "offline" as a xml file. Is there a way for me to serialize this xml using somehow the capnp scheme file? I was thinking of writing a python to descent on xml and insert the elements one by one using the builder.

**Comment by kentonv** [comment]
Hi @ronen-yacobi,

There's no built-in support for XML, but you can of course write code that iterates over all fields. If you wanted to go all-out, you could do something like we've done for JSON, where you define special annotations that can be applied to a Cap'n Proto schema in order to control what the JSON output looks like. Here's how that's implemented (in C++):

https://github.com/capnproto/capnproto/blob/master/c++/src/capnp/compat/json.capnp
https://github.com/capnproto/capnproto/blob/master/c++/src/capnp/compat/json.h
https://github.com/capnproto/capnproto/blob/master/c++/src/capnp/compat/json.c++

And you can look at the tests for some example usage:

https://github.com/capnproto/capnproto/blob/master/c++/src/capnp/compat/json-test.capnp
https://github.com/capnproto/capnproto/blob/master/c++/src/capnp/compat/json-test.c++

I believe you can do similar things in Python but I don't know very much about the pycapnp implementation. Note that pycapnp has not had a maintainer for a while, unfortunately.

I'm closing this issue because it is not actionable for the Cap'n Proto project (sorry, I'm not planning to write any XML codec), but if you'd like to discuss this further I recommend starting a thread on the mailing list: https://groups.google.com/group/capnproto
