### ISSUE TITLE
rpc with client verificaiton

### ISSUE THREAD

**Issue by sdjamali** [capnproto/capnproto#766]
unix domain socket let server knows client pid. and based on pid of clients we can verify clients in local linux machine. and datagram port implementation inside kj lib (c++ implementation of capnp) is what I tried to use as a backbone for a new two party rpc in linux system. that let us to verify our clients in a local machine  but I failed because I'm fairly new to capnp.

It will be so good if there exist a more detail documentations about the implementations. or some two party RPC related patches that enable server to access pid of clients in local machines.

**Comment by kentonv** [comment]
Hi @sdjamali,

You can accomplish this by constructing the socket yourself and using SCM_CREDENTIALS before you hand the socket over to Cap'n Proto. Create your socket using the raw sockets API as if you weren't using capnp at all. Once you've performed the handshake, then you can do something like:

    // Early initialization.
    auto io = kj::setupAsyncIo();
    capnp::TwoPartyServer server(...);

    // ...

    // After accepting a socket and finishing handshake.
    server.accept(io.lowLevelProvider->wrapSocketFd(socketFd))

You can then pass the stream to TwoPartyServer::accept().

With that said, I personally am not a big fan of SCM_CREDENTIALS as a way of authenticating clients. I would suggest instead setting permissions on the unix socket inode (or a parent directory) so that it can only be accessed by approved users. The filesystem approach is generally much easier to understand and audit and composes better with other security mechanisms (e.g. containers).

**Comment by kentonv** [comment]
Closing this issue as I don't plan to add built-in support for SCM_CREDENTIALS.

**Comment by sdjamali** [comment]
thank you Mr Kentonv for your quick and helpefull response
