### ISSUE TITLE
Weird bug with latest version when using makefile

### ISSUE THREAD

**Issue by Vaelatern** [capnproto/capnproto#772]
```
capnp compile log.capnp -oc:capnp
*** Uncaught exception ***
kj/filesystem.c++:315: failed: expected parts.size() > 0; can't use ".." to break out of starting directory
stack: 7fc5f136d17b 7fc5f136f49a 5583e897a940 7fc5f14fda7d 7fc5f14fdab2 7fc5f14d8eaa 7fc5f14db191 7fc5f14f5571 7fc5f14fd223 7fc5f14fd28e 7fc5f14d9d7a 7fc5f14d99b0 7fc5f14da711 7fc5f14dfffc 7fc5f14e7e8a 7fc5f14e8d02 7fc5f14f9585 7fc5f14fb065 7fc5f14feea6 7fc5f14ff373 5583e8983781 5583e8983ad0 7fc5f1389467 7fc5f138a7a4
make: *** [Makefile:220: capnp/log.capnp.c] Error 1
```

The capnp file is: https://gitlab.com/dxpb/dxpb/blob/master/src/log.capnp and includes the line: `using C = import "../capnproto/compiler/c.capnp";`

This has worked when on 0.6.1, but not as of 0.7. I have issues making the layout work unless I put capnproto in the root of the project, and build into a subdirectory. What is the recommended way to drive capnp with Make?

**Comment by kentonv** [comment]
Hi Toyam,

`capnp` is complaining here because it think you're importing a file from outside your source tree, and it doesn't know how to generate an appropriate `#include` corresponding to this import.

Indeed, the `log.capnp.h` you generated previously appears to be invalid. 
[Your generated code](https://gitlab.com/dxpb/dxpb/blob/master/src/capnp/log.capnp.h#L18) appears to have this line:

    #include "../capnproto/compiler/c.capnp.h"

But there's no such file relative to this header.

It looks like your build only works by accident: You have `-I../include` in your `CFLAGS`, which means the above `#include` is interpreted as `../include/../capnproto/compiler/c.capnp.h`.

What I think you should do instead is use `-I` to set an import path.

    capnp compile -I.. log.capnp -oc:capnp

Then, change the import line in `log.capnp` to:

    import "/capnproto/compiler/c.capnp"

The generated include will then olok like:

    #include <capnproto/compiler/c.capnp.h>

You should then be able to pass a similar `-I` flag to your compiler command-line.

This is a little ugly as-is, since now you can do `#include "include/dxpb.h"` which obviously isn't what you intended. So you might want to move or symlink `capnproto` into some location where it stands alone, then add that to the import path. That's all up to you, of course.

**Comment by Vaelatern** [comment]
It helps that the header is only built when the CWD is indeed relative to the correct path.

The problem is when I do similar work to what you describe, I get a new error:

```
capnp compile -I.. log.capnp -oc:capnp
failed to open src/log.capnp.h: No such file or directory
c: plugin failed: exit code 2
```

Which is correct: `src/log.capnp.h` doesn't exist, the command builds it into `capnp/log.capnp.h` instead. I imagine this should be filed with the c plugin provider instead, so please do let me know.

I also tried more includes (in the two possible orderings):
```
capnp compile -I. -I.. log.capnp -oc:capnp
failed to open src/log.capnp.h: No such file or directory
c: plugin failed: exit code 2
```

If I put `-oc` instead of `-oc:capnp`, Make's implicit rules bite me, as they find a circular dependency between `log.capnp.c` and `log.capnp` (since in Make's default ruleset, `%: %.c`).

Thank you for your help!

**Comment by kentonv** [comment]
Now that seems buggy... it looks like it decided that `..` is the source root, but that's not what `-I` is supposed to do.

Maybe you could try this:

    capnp compile --src-prefix=. -I.. log.capnp -oc:capnp

Otherwise, I recommend setting up some symlinks or something, like:

    # in top-level of repository
    mkdir deps
    ln -s ../capnproto deps/capnproto

Then use `-I../deps`... `capnp` shouldn't get confused then.

**Comment by Vaelatern** [comment]
That invocation (with `--src-prefix`) works great! Thank you!
