### ISSUE TITLE
Using `null` as a parametric struct field's default crashes the compiler

### ISSUE THREAD

**Issue by popham** [capnproto/capnproto#779]
The following schema dumps `error: Internal compiler bug: Bootstrap schema failed to load: ...`:

```
struct K(A) {
  k @0 :A = null;
}
```

I noticed https://github.com/capnproto/capnproto/issues/363 as context relevant to the bust.

I'm writing a plugin for Flow annotated JavaScript (I think some minor tweaking will generate TypeScript too) with `disownSomeText(): null | Orphan<Text>` and `getText(): null | Text`. An explicit `someText` default generates `defaultSomeText(): Text`. If explicit `null` defaults were admitted, then I would just not bother generating the `defaultSomeText` method in those cases, but I would be annoyed by the quirk. I only mention it because I thought it might be relevant to `Maybe` in the c++ implementation.

**Comment by kentonv** [comment]
It looks like the reason the compiler is crashing has nothing to do with the word `null` -- any other word or expression produces the same effect. The problem is that it tries to parse a value of type `A`, but `A` is a generic type parameter, so it doesn't know how to parse it. The error message is definitely buggy, but the fix is to generate a better error message. The compiler still won't be able to parse a value when it doesn't know the type.

The compiler doesn't currently recognize `null` as a special identifier, except in the case of a default value for a parameter to an RPC method, which was special-cased to address #363.

Cap'n Proto's type system is actually intended to have no concept of `null`. A null pointer on the wire is supposed to be treated identically to its default value. However, in practice, nullable pointers are super-useful for many applications, and so the abstraction was allowed to leak. I would like to formalize this at some point by introducing a `Maybe(T)` type into the language itself. Schemas would have to be updated to use `Maybe(T)` in cases where null is intended to be special, and we'd stop allowing nullness to be observed for non-Maybes.

`Maybe(T)` will have the odd quirk that it cannot take any default value other than `null`, because Cap'n Proto serialization very much bakes in the idea that a default-initialized struct is all-zero.
