### ISSUE TITLE
Separator for multiple packed messages

### ISSUE THREAD

**Issue by tujian** [capnproto/capnproto#780]
If we want to concatenate multiple packed messages and write them back into a single file, which separator could we choose? 

`msg1` `separator` `msg2`  `separator` `msg3`  `separator`

Is '\n' fine? (Or is it guaranteed that '\n' will not appear in a single packed messages?)

During read phrase, I would like to count the separator for fast message retrieving and indexing.

**Comment by kentonv** [comment]
Hi @tujian,

Any byte may appear in a binary message (whether packed or not), including `'\n'`. There is no byte you can use as a separator.

You will need to either:
1. Store the length of each message as a prefix. This way you know exactly how many bytes to skip to find the next message.
2. Use a 16-byte (or larger) separator generated using a cryptographic random number generator. In this case the probability that the separator will appear in the data by accident is so tiny that you can safely assume it won't happen. You should generate a new separator for each file, so that embedding one file inside another doesn't cause problems.

(I'm closing this because this is not an actionable issue for Cap'n Proto.)

**Comment by tujian** [comment]
@kentonv Got it. Thank you.
