### ISSUE TITLE
Make capnproto work for Arduino-scale targets

### ISSUE THREAD

**Issue by KubaO** [capnproto/capnproto#844]
The protocol is beautiful and it'd be useful to make it work on very small targets, further dogfooding its memory efficiency. This issue aims to get the runtime library to compile for Arduino, and the C++ code generator to generate code that the Arduino target could use. The Arduino targets have very little resources - single kilobytes of data space and tens of kilobytes of code space. Since there may be additional constraints on such generated code that don't apply to most typical applications, I'd propose to initially have "small embedded" be a feature enabled by a compile-time option for the runtime, on top of the lite mode, and a matching command line option for the C++ code generator. This should be achieved with no changes to the encoding.

Integrating the build with the Arduino IDE is out of scope of this issue. The runtime library and the generated library should compile when included into an Arduino project, but the IDE won't know what to do with `.capnp` files. Any such IDE support is a separate matter.

**Comment by kentonv** [comment]
I'm concerned that this could lead to so many `#ifdef`s that the code becomes unmaintainable. It might make more sense to maintain a whole separate implementation for such targets. But maybe it's doable, and if it is, it would certainly be nice to have a consistent API across platforms.

Here's what I think we'd want to remove for embedded targets:

* Start with lite mode -- no schemas, no reflection, no RPC.
* Remove everything that requires allocation.
    * No MallocMessageBuilder: The only MessageBuilder implementation would be one that starts with a pre-allocated buffer which is required to be "big enough". (This also means you can get rid of far pointer logic, at least for builders.)
    * kj::String, kj::Own, kj::Array go away (though StringPtr and ArrayPtr stay).
* Obviously C++ exceptions are a no-go.
    * All recoverable assert failures are ignored.
    * All fatal assert failures are hard stops.
* No I/O streams. We can parse from a buffer, and write to a buffer, that's it.
* No threads nor mutexes.
* layout.c++ needs to be trimmed down.
    * KJ_ALWAYS_INLINE should be ignored for this target.
    * Probably we can get rid of the copy algorithm.
        * This implies no support for implicitly initializing a pointer builder as a copy of a default value. We can require that you use initFoo() to initialize; getFoo() only allowed on non-null pointers.
    * Get rid of orphans?
    * As mentioned above, far pointers can be removed from builders. Maybe we can remove them from readers too, by saying that we only support parsing single-segment messages. This would mean that the peer (if it is not also an arduino) would need to check before sending a message to see if it is multiple segments and, if so, copy it into a single-segment message before sending. This seems reasonable.

**Comment by KubaO** [comment]
I hate ifdefs. I'd much rather have a traits-like class that gives specifics for an implementation of a certain kind, and then just a bunch of `using`-s that map unparametrized generic types to implementation-specific ones. E.g. a `Foo::Builder` would really be `Foo::Builder<capnp::super_lite>` or somesuch. I don't know yet how to structure it so that it'd be neat and maintainable, but I'd favor an approach that uses the language proper rather than preprocessor (on the rude assumption that preprocessor use is evil and improper :).

**Comment by kentonv** [comment]
> I don't think that orphans add much cost:

The point was more to reduce the library's code footprint. There's a fair amount of code to handle Orphans specifically and it's not used super-often.

> if the user has some buffer space to waste, let them? 

Not sure what Orphans have to do with wasting buffers space. To be clear, I'm talking about the `Orphan<T>` class, whose main purpose is to allow you to allocate an object before you've decided where it goes in the tree. When you later decide the parent object, you call `parent.adoptFoo(kj::mv(orphanFoo))`.

> Presumably they'd link their project so that unused functions are removed, and that would just remove these methods.

Maybe. If dead code elimination can do the job that would be great. But often you have cases where two different functions are implemented in terms of the same third function, passing different flags, and then down the call stack somewhere there are branches based on flags. Dead code elimination can't really help you in that case.

But certainly, if we can structure things so that dead code elimination does the job, that's highly preferable over ifdefs.

> Since segments aren't supported, a message would begin with a root struct pointer, right?

We could do it that way -- this is sometimes called "flat" encoding. Or, we could say that you still need the segment table although it always has only one segment. Using "flat" encoding might be confusing due to having some different properties from standard encoding, e.g. it is not self-delimiting. OTOH it would avoid confusion from people writing code that doesn't carefully ensure a single segment, but seems to work in tests because the tests don't use sufficiently large messages, and then it fails in prod. I'm not sure what the right answer is here.

> I hate ifdefs. I'd much rather have a traits-like class that gives specifics for an implementation of a certain kind, and then just a bunch of using-s that map unparametrized generic types to implementation-specific ones. E.g. a Foo::Builder would really be Foo::Builder<capnp::implementation>, and then capnp::implementation is an alias to the implementation traits that the user chose, with a default template parameter somewhere so that existing users wouldn't break.

So, first, this will break existing code. Even with a default template parameter, you still now have to write `Foo::Builder<>` instead of `Foo::Builder`. So it's a non-starter.

Even if that part worked, doing this with template parameters essentially requires that all classes become templates, which in turn means they must all be defined 100% in headers and recompiled in every translation unit. That just doesn't work out in practice.

I also think the result would be a lot harder to read and maintain than ifdefs, to be honest. Preprocessor is not a beautiful programming language but it's definitely the correct tool for the job here.

> The hack I used to slim the messages to fit into the tiny embedded RAM is to have 3-byte wordsize/pointer size,

That's very interesting! 3-byte words is certainly rather exotic... I guess you end up with no alignment guarantees then?

FWIW if you don't need to support copying or otherwise traversing data without a schema, then you might be able to drop more type information from pointers. Though I guess assuming you still need backwards-compatibility, it's tough to drop a struct's segment sizes. Maybe the device could make it the server's problem to deal with compat by advertising its schema (or schema version) upfront? That makes device-to-device communications hard, but I don't have a good concept of how often that's needed compared to device-to-server. If you could get the server to deal with all versioning then you could probably get away with 2-byte pointers (for messages under 128k).

I don't think you want this to be a property of the schema -- schemas should be independent of encoding, and the same schema should be allowed to be encoded different ways. E.g. it's not uncommon to encode a Cap'n Proto (or Protobuf) schema in JSON in certain contexts, while using the binary encoding in others.

But I think it's going to be really hard to make the implementation support dynamic word sizes, especially without hurting performance for the standard case. I think the best you can do here is probably ifdefs, or a fork.

**Comment by KubaO** [comment]
I really like that the pointers allow schemaless traversal: largely unfettered protocol evolution is the primary reason I like capnp so much. I will flesh out the unpacker though, and perhaps it could be offered as an optional feature in the runtime: it unpacks the message into a safe, bounds-checked, directly-accessible-from-C (using implementation-defined packing) format where no accessors are needed for reading, and all pointers are resolved. A fully transcoding unpacker is code-generated, but allows arbitrary type transformations, e.g. limiting tags to 1 byte, shrinking floats from 64 to 32 bits, verifying pointer types, etc. I have lots of holes in the implementation still, though.

I indeed thought of orphans as a post-hoc result of reallocating lists. I haven't had a chance to use the orphan-before-adoption approach yet.

I'll probably close this issue since I'm not putting much work into it before the new codegens and runtime ports I'm working on are done.

**Comment by KubaO** [comment]
#634 is the blocker for this, since any "tiny-target"-specific changes will depend on the lite mode being decent to start with. I'm closing, but will reopen whenever #634 is considered done, iff there are still Arduino-specific changes that may be necessary
