### ISSUE TITLE
C++ codegen attempts to shadow MethodParams and MethodResults.

### ISSUE THREAD

**Issue by KubaO** [capnproto/capnproto#849]
In the below schema, the generated C++ code has double declarations of `Foo::MethodParams` and `Foo::MethodResults` types. Thus the generated code fails to compile. Whenever implementation-detail types are added to a scope, their names should not clash with existing type names within the schema. This impacts all implementation types injected into scopes.

```
interface Foo {
  method @0 (a: Void) -> (b :Void);
  struct MethodParams {}
  struct MethodResults {}
}
```

Since the autogenerated `Params` and `Results` types are an implementation detail, they should be in a `detail`-style namespace, or named with some disambiguating suffix (or prefix). Precedence must be given to the types explicitly declared by the user. But also see #848 for another approach that would contribute to a fix for this specific case.

**Comment by kentonv** [comment]
I consider this more of a feature than a bug. Sometimes you have a method like:

    foo @0 (...params...) -> (...results...)

And later on you decide you really want to move the params or results list out into its own struct...

    foo @0 (...params...) -> FooResults;
    struct FooResults { ... }

This change will not require changing any C++ code, as long as the new `FooResults` has all the same-named fields.

This is useful e.g. if you decide you need a union, which cannot be declared as part of a parameter/results list.

In general, there are many ways to cause the code generator to generate code that does not compile. Most of them involve symbol name collisions. I do not consider these to be bugs, because, frankly, I've never seen this cause a real problem in practice. In practice, people have to go out of their way to choose names that happen to collide with a generated name.

That said, if somehow this did happen, there is still a solution: `/capnp/c++.capnp` declares an annotation `$name` which can be used to rename a declaration specifically for C++ code generation purposes. So you can do:

```
using Cxx = import "/capnp/c++.capnp";
interface Foo {
  method @0 (a: Void) -> (b :Void);
  struct MethodParams $Cxx.name("MyMethodParams") {}
  struct MethodResults $Cxx.name("MyMethodResults") {}
}
```
