### ISSUE TITLE
Allow asynchronous disconnected exceptions on regular (non-promise) capabilities.

### ISSUE THREAD

**Issue by KubaO** [capnproto/capnproto#859]
Sandstorm has this workaround: `Handle.ping()`. Shouldn't the RPC protocol allow sending `Resolve` with an exception when the Server (the C++ object) backing a capability gets destroyed or is otherwise marked as disconnected?

This does smell like a subscription to a state, so maybe the a way to implement this in an application-specific way is for a resource provider to accept a `HandleNotifier` capability from the user, with a `handleWasInvalidated(Handle)` method to be used to send the disconnect notification. The problem, then, is that the resource user will unnecessarily send a `Release` on the handle - never mind the `Return`. A workaround the for the provider to send a `Call` together with a `Finish`, so there'd be no roundtrip incurred. This paragraph doesn't pertain to capnp nor Sandstorm code, but to generic "capnp user" code.

There's no way to bypass the unnecessary `Release` and `Return`/`Finish` unless this functionality is implemented in the RPC protocol itself. Should this be an optional but desirable feature, a `Monitor` message type can be added, with a `List(ImportId)` field that would inform the receiver that the sender is interested in getting end-of-life DISCONNECTED exceptions via `Resolve` messages for these imported capabilities. The client code would record the disconnection and throw (or otherwise report an error) at any attempt to use the known-to-be-disconnected capability, and can provide a callback registration to inform about a capability disconnection. There would be no `Return` for a `Monitor` message, except if there was an exception thrown due to invalid `ImportId` in the list.

Should any of this be desirable, I'd gladly finish the implementation. I've implemented the `Monitor` message (in C++ only), and it works for what I need.

**Comment by KubaO** [comment]
I just noticed the `shortenPath()`'s usability as a "hack" for this. Is it really desirable to overload promises that way?

**Comment by kentonv** [comment]
Using `shortenPath()` for this is not a hack. It effectively produces exactly the behavior you're looking for and does so in the most efficient way reasonably possible. In retrospect, perhaps all capabilities should always have been treated as "promises" allowing them to be resolved to something else later, but as it stands, an application can choose to get such semantics today by implementing `shortenPath()`.

You cannot eliminate the `Release` message without creating race conditions. Calls referring to the import may already be in-flight. The server cannot reuse the table entry until it knows that all in-flight messages from the client have been received; it can only know this by receiving a `Release` from the client. The `Release` message is asynchronous, not blocking anything else the application might be doing, so the overhead incurred by it is minimal. I suppose as an optimization, we could consider delaying `Release` (and `Finish`) messages in order to coalesce them with the next message sent, to avoid an unnecessary IP packet.

**Comment by KubaO** [comment]
If the idea is that all capabilities should be promises, then this is definitely the way to go. Perhaps that `shortenPath` method could be called something else? Perhaps even the default RPC behavior should be changed to this, so that it wouldn't be a special case?

`Release` messages are indeed a much saner way to deal with this one than what I had in mind (a temporary lockout).
