### ISSUE TITLE
target_compile_features in kj forces all downstream dependencies to be C++14

### ISSUE THREAD

**Issue by vlovich** [capnproto/capnproto#867]
target_compile_features in kj is specified as having a PUBLIC dependency on cxx_generic_lambda. However this forces downstream dependencies (libraries using capnproto) to have a dependency on C++14 even if they want to use C++17/C++1a. Moreover on older CMake version (e.g. 3.6 that ships with Android NDK by default), it's impossible to override this further.  At most kj & capnp should perhaps do this as a PRIVATE target_compile_feature?

**Comment by pqu** [comment]
Downstream targets can override the C++ version with the `CXX_STANDARD` property:

    set_target_properties(target PROPERTIES CXX_STANDARD 17)

CMake shouldn't "downgrade" the target to C++14 as `CMAKE_CXX_COMPILE_FEATURES` will contain `cxx_generic_lambdas`. (I tested this on 3.14; I'm not sure about older versions.)

**Comment by vlovich** [comment]
This is pre-supposing that CMake recognizes 17 for CXX_STANDARD. As I mentioned in the description, CMake 3.6.4 (which is the default Android cmake) doesn't "know" about C++17 so the feature selection that kj is making as part of it's public interface overrides the manual -std=c++17 I'm supplying on the command-line. There's no reason for this to be PUBLIC - it works just fine if the feature is PRIVATE on target_compile_features for kj/capnp & fixes the issue with Android's default CMake.

**Comment by kentonv** [comment]
Hi @vlovich,

Sorry, but this is working as intended. We need a way to tell cmake to enforce that downstream dependents use at least C++14. If we don't do that, a lot of downstream projects will break -- especially as we originally required only C++11 and changed the requirement to C++14 relatively recently. In the future we may similarly need to upgrade to C++17. If we were to remove this directive, many dependents of Cap'n Proto would break.

The way we are doing this is the intended and correct way to do this with cmake. It sounds like it is your project that is using an incompatible non-idiomatic approach. It sounds like you are doing this because you are using a very very old version of cmake that doesn't know about C++17.

Sorry, but you're going to need to upgrade cmake. If you are going to use modern C++ versions, you also need to use modern cmake versions. If you insist on using a strange combination of new and old tools, then the problems that result are your problems; you cannot ask the rest of the world to work around them for you.

Alternatively, you can always maintain a fork of Cap'n Proto that adjusts the build files to your liking.

**Comment by harrishancock** [comment]
@vlovich, a hacky workaround on the dependent project side could be to set the `CapnProto::kj` target's `INTERFACE_COMPILE_FEATURES` property to the empty string. Something like this:

```cmake
# Get the full list of compile features known by this version of CMake.
# (You might consider using the CMAKE_CXX_COMPILE_FEATURES property instead.)
get_property(known_features GLOBAL PROPERTY CMAKE_CXX_KNOWN_FEATURES)

if("cxx_std_17" IN_LIST known_features)
  # Yay, this CMake supports C++17!
  target_compile_features(my-target PRIVATE cxx_std_17)
else()
  # We're on an ancient version of CMake. Do our best.
  message(WARNING "Falling back to target_compile_options() to enable C++17; please upgrade your CMake")
  # Need to lightly hack the kj target to work around https://gitlab.kitware.com/cmake/cmake/issues/16608
  set_property(TARGET CapnProto::kj PROPERTY INTERFACE_COMPILE_FEATURES "")
  target_compile_options(my-target PRIVATE -std=c++17)
endif()
```

That will work when compiling against a CMake-built installation of Cap'n Proto, but won't work out of the box when compiling against the autotools-built version of Cap'n Proto -- that version's CMake integration sets the `INTERFACE_COMPILE_FEATURES` property on all Cap'n Proto targets, so you'd need to duplicate the `set_property()` line for all targets you link with.

It's not great -- but the real problem is in the Android NDK.

**Comment by vlovich** [comment]
Hmm... @harrishancock I'm 75% sure I tried clearing INTERFACE_COMPILE_FEATURES & it didn't work (maybe it's a bug in 3.6 or I didn't actually do it after all - thanks for the tip).

@kentonv I agree. In theory I should be able to use 3.10 for Android's CMake but I can't figure out how to adjust the gradle file to have it select the newer CMake even though I have it installed in my NDK.

In general Android Studio is pretty laggardly in terms of the CMake version they support unfortunately. Given that Cap'N'Proto isn't at the bleeding edge it's possible you won't notice these kinds of incompatibilities (& yes - I am maintaining a fork where I made these changes). It's just ironic that the intention is to make the minimum version C++14 but it's preventing my C++17 code from building :).

**Comment by jclee** [comment]
@vlovich Not sure if this helps, but you could try the gradle.build tweaks mentioned in this StackOverflow answer, or the ones in the offical docs that it links to:

https://stackoverflow.com/questions/51471908/upgrade-cmake-version-installed-with-android-studio-ubuntu-18-04
