### ISSUE TITLE
Allow finding a substring in kj's string

### ISSUE THREAD

**Issue by xtuc** [capnproto/capnproto#868]
Based on
https://github.com/capnproto/capnproto/blob/2ec719865adb64792b07c88ad8298dacf4567c72/c%2B%2B/src/kj/string.h#L129-L130

You can only find a char in a string, however, I would like to find a substring. It would be handy to extend the API.

**Comment by jclee** [comment]
As far as implementation goes... would it be preferable to just overload the existing character functions to search for substrings? e.g.:
```
inline Maybe<size_t> findFirst(StringPtr s) const;
```
Or is it better to use a different name for substring searching?  FWIW, `std::string` overloads "find" and "rfind" to find substrings or individual characters ("substrings of length 1"); on the other hand, it overloads "find_first_of"/"find_last_of" to find sets of characters or individual characters ("sets of size 1").

**Comment by kentonv** [comment]
The best algorithm to find a character is trivial, but the best algorithm to find a substring is somewhat more complicated. Ideally you want it to be O(len(haystack)) but the naive implementation is O(len(haystack)*len(needle)). I think the optimal-throughput algorithm involves a little bit of upfront setup, but that setup may not be worth it when the needle or haystack is short.

Every time I think about adding this I get stuck on being uncertain about how it should be done.

But I guess we should just call `memmem()`? I'd accept a PR that implements these based on `memmem()`.

**Comment by xtuc** [comment]
I would overload. I don't really have a preference on the implementation, but if you are not comfortable having it in kj, we can leave it in our codebase.

**Comment by jclee** [comment]
Sure, memmem() works.  I was just thinking strnstr(), since that's approximately what most kj substring searching is already doing, but yeah, would be nice to handle inline nulls.

**Comment by kentonv** [comment]
Yes it should be an overload.

Yeah, `memmem()` is more correct that `strstr()` since KJ strings are technically allowed to contain NULs. Also, it seems likely that a good implementation of `memmem()` would take advantage of knowing the lengths upfront, which `strstr()` can only discover by scanning. I have no idea if glibc's `memmem()` is good though.

**Comment by jclee** [comment]
Hmm...  Per a discussion I found ( https://sourceware.org/bugzilla/show_bug.cgi?id=5514 ), it looks like since 2008 glibc has been using the "two-way" algorithm for strstr() and memmem() -- an O(n) time, O(1) space algorithm.  This is apparently necessary for applications that don't allow malloc(), which precludes algorithms like KMP and Boyer-Moore.  There is also mention of an assembly optimized version.  I haven't looked at the glibc source itself yet, so I don't know if it's currently using this algorithm.

One potential snag: memmem() is a GNU extension, so it's not broadly available, particularly on MSVC.  (Not sure what MSVC uses for strstr()...)  Also, there is no reverse version, so there would be no equivalent findLast() implementation.  Is it OK to fill in these deficiencies with naive implementations and/or leave them missing?  Or would it be better to do a from-scratch implementation of the two-way algorithm?

Also, the Linux manpage implies a "_GNU_SOURCE" macro definition is needed to expose memmem(), which may complicate or preclude inline use in headers.  I see kj is already using this macro in a number of .c++ files but not headers, presumably for this reason.

Alternately, it looks like C++17 introduces some rudimentary search algorithms to the standard library that might be applicable, including a naive O(mn) searcher and a couple Boyer-Moore variants:

https://en.cppreference.com/w/cpp/algorithm/search

**Comment by ashvardanian** [comment]
@jclee, one may still use Boyer-Moore and Horspool algorithms without heap allocations, building shift tables on the stack, they are fairly small. Still, you are right that `memmem` isn’t universally available, and may not be sufficiently fast for CapnProto. On Graviton 3 its throughput is only around 2 GB/s/core on common benchmarks. I have a 3x faster alternative in StringZilla, in case you are looking for portable performance 🤗

PS: `std::search` is a very bad solution - the performance is extremely inconsistent, and depends on inputs a lot.

**Comment by kentonv** [comment]
In practice I don't think we ever use this for scanning huge strings, just relatively small ones and often in situations where performance is not a concern anyway. I think the current solution in #1835 is fine, so I'm closing this.
