### ISSUE TITLE
What is the equivalent of writePackedMessageFd and PackedFdMessageReader under Windows?

### ISSUE THREAD

**Issue by sharpe5** [capnproto/capnproto#877]
Hi,

In the [sample code](https://capnproto.org/cxx.html) it has the following:

```
void writeAddressBook(int fd) {
  ::capnp::MallocMessageBuilder message;
  ...
  writePackedMessageToFd(fd, message);
}
```

Followed by:

```
void printAddressBook(int fd) {
  ::capnp::PackedFdMessageReader message(fd);
  ...
}
```

After much trial and error under MSVC 2017 I worked out that `Fd` stands for `FileDescriptor`, and it does not appear to work on Windows. It generates a debug assert error, followed by a  `memory access violation`:

```
Unhandled exception at 0x00007FFE4707A388 in capnpx.exe: Microsoft C++ exception: kj::ExceptionImpl at memory location 0x0000009A04AFCFF0.
```

Same behavior in v0.7.0 and v0.8.0 (master).

I'm wondering if there is equivalent code that is cross-platform, and uses a method to write to a file that will work on Windows, Linux and Mac?

**Comment by jclee** [comment]
As I understand it, file descriptors are a POSIX concept.  While MSVC's C standard library doesn't fully implement POSIX, it looks like it does have a partial POSIX compatibility layer...  The Windows-specific `_fileno()` function, for instance, can convert from stdio.h's `FILE*` values to file-descriptor-like values: https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fileno?view=vs-2019

Note that `_fileno()` can return negative values to indicate no equivalent POSIX stream exists for the Windows process, which can apparently happen if the program is not built and run as a Windows console application -- perhaps that is related to your errors?

But from the docs, I'm guessing that more general Windows code would probably substitute something like `_fileno(stdin)` instead of the standard POSIX input file descriptor value 0 and `_fileno(stdout)` instead of 1, in the sample's `main()` function, being careful to check for negative return values to avoid errors.

**Comment by kentonv** [comment]
Yeah, file descriptors do in fact work on Windows (via the emulation layer in the C runtime library).

It looks like your code is throwing a KJ exception. You should try catching that exception and logging it to see what it says. (It's too bad MSVC's runtime doesn't call the exception's `.what()` by default to show you the error... libstdc++ and libc++ both do.)

One common problem on Windows is that you need to make sure to open the file descriptor in "binary" mode, by passing `_O_BINARY` to `_open()`.

With all that said, on Windows, it may make a lot of sense to use HANDLEs instead of file descriptors. You can do that by using `kj::HandleInputStream` and `kj::HandleOutputStream`, found in `kj/io.h`, together with `capnp::InputStreamMessageReader` and `capnp::writeMessage()` from `capnp/serialize.h`, which accept arbitrary KJ input/output streams. (You can also write custom subclasses of `kj::InputStream` and `kj::OutputStream` if you want.)

**Comment by sharpe5** [comment]
Thank you both for your help. Although I have decades of experience in C
and C#, I am still at the start of the learning curve that we all must
follow to learn a useful subset of modern C++.

Out of interest, if I create some sample code that works under both Windows
and Linux, would you consider a pull request to your documentation or the
"samples" directory?

**Comment by sharpe5** [comment]
This sample code should work just fine under Windows:
https://github.com/thekvs/cpp-serializers

Capnproto is ranked right at the of the list. If one takes into account the
fact that deserialising is virtually instant after serialising, it becomes
clear that you guys have written some incredibly performant code.

I like Capnproto better than Flatbuffers because the size of each message
is constant, which allows accurate indexing into a large file. This means a
binary search over a terabyte sized file on a SSD is easy, and adding
multiple indexes to access different views of said file is also relatively
easy. Kind of like a cut-down version of MSSQL but several orders of
magnitude faster for simple use cases at the base of the data stack.

**Comment by sharpe5** [comment]
For the record, the simplest possible cross-platform Capnp sample, the
equivalent of "Hello, world!" (not "Hello, arbitrarily nested address book
data structure!"):
https://www.phoiyb.online/gatkinso/capnsamples
