### ISSUE TITLE
CodeGeneratorRequest's filename doesn't handle absolute paths well

### ISSUE THREAD

**Issue by antocuni** [capnproto/capnproto#881]
Consider this example:
```
$ cat /tmp/foo.capnp 
@0xf1a344489fb7179b;

$ capnp compile /tmp/foo.capnp -o - | capnp decode /path/to/schema.capnp CodeGeneratorRequest
( nodes = [
    ( id = 17411835663052380059,
      displayName = "tmp/foo.capnp",
      displayNamePrefixLength = 8,
      scopeId = 0,
      nestedNodes = [],
      file = void,
      isGeneric = false ) ],
  requestedFiles = [
    ( id = 17411835663052380059,
      filename = "tmp/foo.capnp",
      imports = [] ) ],
  capnpVersion = (major = 0, minor = 7, micro = 0) )
```

With capnp 0.7.0, `filename` is `tmp/foo.capnp` instead of `/tmp/foo.capnp`. With capnp 0.6.1, `filename` reported the correct absolute path.

I ran `git bisect` and found that the culprit commit is probably this: e2a9467b

**Comment by kentonv** [comment]
This is working as intended. It's incorrect to pass an absolute path to a code generator, because code generators are expected to output to a specified directory, and many code generators come up with path names for generated code by modifying the input file name (e.g. C++ adds `.h` and `.c++` to the filename). So, the path must be relative, otherwise the output files end up next to the input file even if the caller asked that they be placed elsewhere. This was a bug prior to the commit you reference.

You can control how `capnp` converts absolute paths into relative ones using the `--src-prefix` flag, which specifies a prefix of input file paths that should be stripped off. So if your goal really is to input `/tmp/foo.capnp` and output it back to `/tmp/foo.capnp.{h,c++}`, you could do:

    capnp --src-prefix=/tmp -oc++:/tmp /tmp/foo.capnp

This way you're saying very explicitly "For the purpose of this invocation, `/tmp` is the root of my source tree, _and_ is also the place where I wish to generate my output."

**Comment by antocuni** [comment]
thank you for the exhaustive explanation!
