### ISSUE TITLE
rpc server accepting connections and handling requests

### ISSUE THREAD

**Issue by 13272438611** [capnproto/capnproto#900]
Hi, is there any other way to run the server except "kj::NEVER_DONE.wait(waitScope);", for me, i want to accept connections and handle requests for myself, not just run forever, is there any example on it?

**Comment by jclee** [comment]
Per https://github.com/capnproto/capnproto/blob/master/c%2B%2B/src/capnp/ez-rpc.h#L77 :

"Only one `kj::EventLoop` can exist per thread, so you cannot use these interfaces if you wish to set up your own event loop."

I guess the best solution would be either to use the kj facilities to implement your server (so that you can use kj's event loop) or to implement your server in another thread, so that each thread can have its own event loop.  It's possible there may be another solution involving poll()ing the kj event loop from inside another event loop, but I suspect it will not perform well.

**Comment by kentonv** [comment]
@13272438611 Sure, you can use the KJ APIs to accept connections individually and do work with them. You can call `.wait()` on any `Promise<T>` in order to run the event loop until that promise resolves. You don't have to wait on `NEVER_DONE` specifically.

However, if you want to do blocking operations or use some non-KJ event loop, then you probably have to do it in a separate thread. This is a classic problem with C++: there is no standard event loop, and you inherently can't have two event loops on the same thread.

It is actually technically possible to make the KJ event loop run on top of some other event loop, but you need to write a bunch of code to integrate them. For example, node-capnp adapts the KJ event loop to run on top of libuv. See the code for that at the beginning of this file:

https://github.com/capnproto/node-capnp/blob/node10/src/node-capnp/capnp.cc

(I'm closing this issue because it isn't actionable for the capnp project. FWIW, it's usually better to ask questions like this on [the mailing list](https://groups.google.com/group/capnproto).)

**Comment by 13272438611** [comment]
Thank you for your replyl! It is mentioned that "Requests and responses can go in any direction." at FAQ , I would like to know is there any example of the server start  requests to the client?

**Comment by kentonv** [comment]
(Closing this since it's not an actionable issue, and the follow-up question was moved to the mailing list.)
