### ISSUE TITLE
Question about request pipelining overhead

### ISSUE THREAD

**Issue by tabokie** [capnproto/capnproto#918]
I am reading the great calculator sample trying to figure out the request pipelining thing, and I notice the pipelining is achieved by explicitly calling requests on an user-defined proxy type, `Value` in this case:
https://github.com/capnproto/capnproto/blob/22c0fdf616909078e7ab478f816fab86373cfc0d/c%2B%2B/samples/calculator-server.c%2B%2B#L35

This approach is quite out of my expectation, (I was imagining the kj::future can be derived into a `DistributedFuture` that handles these things on its own).
My concern is mainly about the performance of pipelining. The first question here is, will the `readRequest` onto local object be reduced into a memory access? or an actual network call is involved? Also, is there an auto batching system to better handle throughput trouble incurred by sending bulks of requests at the same time?

Thanks~

**Comment by kentonv** [comment]
Hi @tabokie,

I'm not sure I understand your question.

There isn't any "kj::future". Did you mean `kj::Promise`?

The line of code you reference doesn't actually do any pipelining. Let's quote the whole statement instead of one line to make it clearer:

https://github.com/capnproto/capnproto/blob/22c0fdf616909078e7ab478f816fab86373cfc0d/c%2B%2B/samples/calculator-server.c%2B%2B#L35-L38

`value.readRequest().send()` is invoking the `read()` method of `value`. On the next line, `.then([](...) { ... })` registers a callback to call when `read()` completes. This is how regular RPC calls in Cap'n Proto are expressed. The use of `.then()` means that we aren't doing pipelining; we are sending the call and waiting for the response like normal.

A pipelined request would look more like:

    auto promise = someCap.fooRequest().send();
    Bar::Client bar = promise.getBar();
    auto promise2 = bar.bazRequest().send();

Here, we are essentially calling `someCap.foo().bar()`, but we didn't wait for `foo()` to complete before starting the call to `bar()`. (Pipelining always involves more than one call in sequence.)

> The first question here is, will the readRequest onto local object be reduced into a memory access? or an actual network call is involved?

If `value` happens to point to a local object, then nothing will actually be sent over the network here. The destination object will execute on the same event loop, and the request and response messages are delivered without copying.

> Also, is there an auto batching system to better handle throughput trouble incurred by sending bunks of requests at the same time?

When requests do cross the network, all requests to the same destination use the same TCP connection. The OS can therefore coalesce messages as normal. I am currently working on some optimizations such that Cap'n Proto can give better hints to the OS about which messages should be sent immediately (because they are latency-sensitive) vs. which messages are OK to leave in the buffer temporarily in order to coalesce with later messages.

**Comment by tabokie** [comment]
@kentonv Thanks for the quick response! It really explains a lot.
As for the `kj::Promise` part, I was suggesting that user might not have to manually write logic for things like `Value` or the `Bar` that actually implements a promise interface on rpc level. It would be much cleaner if I can pass around unfulfilled promise that is **on another server** just like normal value.
Again, current interface is good enough and avoids any unnecessary tangling. Just a first thought opinion.

**Comment by kentonv** [comment]
Hi @tabokie,

On re-reading your original question I think I might understand batter what you're getting at.

In Cap'n Proto, a capability client (e.g. `Calculator::Client`) can transparently represent a promise. In fact, you can literally construct any `T::Client` directly from `kj::Promise<T::Client>`:

    auto paf = kj::newPromiseAndFulfiller<Calculator::Client>();
    Promise<Calculator::Client> promise = kj::mv(paf.promise);
    Capability::Client `promiseClient` = kj::mv(promise);

Any method call on `promiseClient` will first wait for the promise to complete, and then will forward the call to the promise's result (or will propagate the error if the promise rejected).

This is possible to do completely transparently because all methods of a client are already asynchronous (return a promise).

But also note that a pipelined capability is not just a promise capability. If you make a call to a remote object, and then you pipeline a second call on the result of the first, the second call will be sent over the network before the first call completed. It's on the receiving end that the call blocks waiting for the first call's promise to complete.

Now, I think your original question was this: What happens if you make a pipelined call sequences like `foo().bar()`, but it turns out the capability returned by `foo()` actually points back to an object on the calling machine? In this case, the call to `bar()` never needed to cross the network. However, at the time that the call was made, this wasn't know yet, because `foo()` hadn't returned yet.

What happens in this case is that the `bar()` call does indeed cross the network, and then is reflected back to the caller. So the request actually transits the network twice, once in each direction. However, when it gets reflected back, it is annotated to say "hey, this was a call you made in the first place, so you don't need to send the response back to me; you can use it to resolve this other outstanding call you made". So the result of the `bar()` call, at least, does not transit the network. Here's the relevant part of the RPC protocol:

https://github.com/capnproto/capnproto/blob/77f20b4652e51b5a7ebda414e979e059a6c7c27c/c++/src/capnp/rpc.capnp#L428-L464

But yes, it's still unfortunate that the parameters had to be sent back and forth. If an application specifically knows that a pipelined capability is likely to end up resolving back to a local capability, then the application can call the client's `whenResolved()` method to wait for the final resolution before making any method calls. If the `bar()` call is made after the promise has resolved, then it will go directly to the local object without traversing the network.

Incidentally, there's a tricky ordering snag here: What if you make a call on a pipelined capability, and then the capability turns out to resolve to a local object, and then you make a second call on it before the first call has completed? Is it possible that the first call is still bouncing around the network, and ends up being delivered _after_ the second call? Fortunately, the RPC system handles this. We guarantee that calls will be delivered in the order in which they were made. When a capability with outstanding calls on it resolves to a local object, the RPC system places an "embargo" on the capability until all the remote calls have reflected back as expected. Local calls are blocked until the embargo clears. Here's the gory details:

https://github.com/capnproto/capnproto/blob/77f20b4652e51b5a7ebda414e979e059a6c7c27c/c++/src/capnp/rpc.capnp#L643-L709

Did I manage to answer your question this time?

**Comment by tabokie** [comment]
@kentonv Fascinating! I think this is more than enough to solve my question. Though I actually haven't paid much thought to the ordering problem, but it's very interesting indeed, I'll find some time to probe around later.
Thanks again for the walking through!
