### ISSUE TITLE
API question: ordering constraints between calling initRoot and getOrphanage ?

### ISSUE THREAD

**Issue by niekbouman** [capnproto/capnproto#942]
Dear @kentonv ,

I am trying to use the Orphans mechanism for zero-copy purposes.

I am wondering if `getOrphanage()` may be called on a [Malloc]MessageBuilder *only after* having called `initRoot<T>()`, or also prior to it?

best regards,
Niek

**Comment by kentonv** [comment]
Hi Niek,

No, there is no ordering requirement. You can allocate other objects in a message before you've allocated the root object. In fact, `MessageBuilder` has an `adoptRoot()` method which can be used to adopt an existing orphan as the root object -- which of course implies you would have had to create an `Orphanage` before that in order to create the orphan. :)
