### ISSUE TITLE
Orphan usage: design question

### ISSUE THREAD

**Issue by niekbouman** [capnproto/capnproto#943]
Dear @kentonv ,

I have two design questions on the use of the orphans mechanism.

My use case is sending a multi-part message, where I create parts as orphans constructed from the builder's Orphanage (apriori it is unknown how many parts there will be), and then periodically create the top-level message and adopt all orphans into it, and serialise it.

My schema is like this:
```capnp
struct MessagePart {
  // several 
  // fields ...
}

struct ProxyStruct {
    content    @0 :MessagePart;
}

struct MultiPartMessage {
    parts      @0 :List(ProxyStruct);
}
```

First question is on the `ProxyStruct`; I have added it in the schema upon reading in the Cap'n Proto documentation that adopting orphans into a list will trigger a shallow copy, so if I understand correctly the `MessagePart` will be properly adopted without copy (?). Could you comment on the "sanity" of this ProxyStruct solution, or are there reasons for not doing it like this?

Second question:
The way how I intend to use orphans is to have a MallocMessageBuilder as a (persistent) member of my class.
After sending the multipart message, I "refresh" the builder by manually calling its destructor and then doing a "placement new". Is that a safe way of using MallocMessageBuilder?
```cpp
#include <new>

class MultiPart{
MallocMessageBuilder builder_;
MultiPartMessage::Builder root_;

void refresh()
{
  builder_.~MallocMessageBuilder();
  new (&builder_) capnp::MallocMessageBuilder;
  root_ = builder_.initRoot<MultiPartMessage>();
}
};
```
Bonus: I know you worked hard in Cap'n Proto to avoid having to include system headers; 
if the above is indeed safe/good practice, how would I rewrite `refresh()` with kj's PlacementNew machinery?

best,
Niek

**Comment by kentonv** [comment]
Hi Niek,

For questions (not bugs), it's usually better to post on the [mailing list](https://groups.google.com/group/capnproto) -- we like to reserve the issue tracker for actionable changes needed in the Cap'n Proto code. I'm closing this issue since it's not actionable, but I'll answer your question here anyway.

> Could you comment on the "sanity" of this ProxyStruct solution, or are there reasons for not doing it like this?

Well, it's kind of unfortunate, but yeah, if you really need to use an orphanage to allocate `MessagePart`s in advance and then stick them into a list later, I guess this is what you need to do.

> After sending the multipart message, I "refresh" the builder by manually calling its destructor and then doing a "placement new". Is that a safe way of using MallocMessageBuilder?

Well, the biggest problem with this is that it's not exception-safe. If either the constructor or destructor threw an exception, you'd be left in a state where the object is not initialized, but you have no way to track that, so you'd end up trying to destroy it again later. That said, as it turns out, MallocMessageBuilder's constructor is very simple (just initializes some fields), and the destructor only deletes other objects. They "should" never throw, so you should be fine. But personally, I try to write code under the assumption that exceptions can happen anywhere.

The other thing is, if you're trying to avoid a heap allocation, you may also also want to consider pre-allocating buffer space that can be reused by each MallocMessageBuilder instance. Check out MallocMesasgeBuilder's second constructor, where you can pass it an existing buffer to use for for the first segment. You can reuse the same buffer between messages to avoid allocation.

> if the above is indeed safe/good practice, how would I rewrite refresh() with kj's PlacementNew machinery?

Some ideas:

1. Use `kj::ctor()` and `kj::dtor()`, which directly invoke the constructor/destructor:

        dtor(builder_);
        ctor(builder_);

    This has the same exception-safety issue as above, though.

2. Use `kj::SpaceFor<capnp::MallocMessageBuilder>`:

        // first-time setup
        kj::SpaceFor<capnp::MallocMessageBuilder> builderSpace_;
        kj::Own<capnp::MallocMessageBuilder> builder_ = builderSpace_.construct();

        // to reset
        builder_ = nullptr;  // destroy old builder
        builder_ = builderSpace_.construct();

    This version avoids the exception-safety problem, because `kj::Own` is carefully written to be exception-safe. If an exception is thrown, `builder_` will be left null, so it least it won't be double-destroyed. (Of course, if you catch the exception and then try to keep using your `MultiPart` class, you'll segfault on the null pointer access later. But, usually, when an exception is thrown, you're probably going to destroy everything.)

3. Use `kj::Maybe<capnp::MallocMessageBuilder>`:

        kj::Maybe<capnp::MallocMessageBuilder> builder_;

        // to initialize / reset:
        capnp::MallocMessageBuilder& builderRef = builder_.emplace();

        // to use without resetting:
        capnp::MallocMessageBuilder& builderRef = KJ_ASSERT_NONNULL(builder_);

    The problem with this approach is that you need the ugly assert every time you access the builder if you aren't reconstructing it. However, this approach is exception-safe and even avoids segfaulting on a null pointer (throws an exception instead).
