### ISSUE TITLE
Send  message as flat array

### ISSUE THREAD

**Issue by sunnlok** [capnproto/capnproto#970]
I have been trying to build and send messages with as little allocations as possible but i have encountered an issue when trying to serialize a message as a flat array.

I have been building my messages with a malloc message builder and passing it a preallocated stack or heap array depending on predicted message size.

The function to turn a builder into an output array looks like this
```cpp
auto segments = builder.getSegmentsForOutput();
			if (segments.size() > 1)
			{
				auto outputPayload = capnp::messageToFlatArray(builder);
				auto outputBytes = outputPayload.asBytes();

				return sender(target, gsl::make_span(outputBytes.begin(), outputBytes.size()), reg);
			}
			else if (segments.size() == 1)
			{
				auto outputBytes = segments.begin()->asBytes();
				return sender(target, gsl::make_span(outputBytes.begin(), outputBytes.size()), reg);
			}
			else
				return 0;
```
So basically by trying to be "smart" and avoid the heap allocation with messageToFlatArray the resulting output wont be readable.
Is there some header word that needs to be added for the message to be readable?
messageToFlatArray seems to always write one word more.

Looking at messageToFlatArray, it seems to be writing this via an endianess wrapper so that might also cause issues in other cases. Is there a way to do this in place?

**Comment by zenhack** [comment]
If you want to write out the header yourself, have a look at:

https://capnproto.org/encoding.html#serialization-over-a-stream

**Comment by kentonv** [comment]
Hi @sunnlok,

Instead of trying to write the header yourself, you could try writing a custom implementation of `kj::OutputStream`, and then write the message to it using `capnp::writeMessage()`. The message will always be written using a single call to `write(ArrayPtr<const ArrayPtr<const byte>>)`, passing the header and all segments at once as an array-of-arrays. The header will be allocated on the stack, so this will avoid any heap allocation.
