### ISSUE TITLE
streaming - '/capnp/stream.capnp' is not found

### ISSUE THREAD

**Issue by vitaliy-ostapchuk93** [capnproto/capnproto#993]
Currently testing capnproto for a potential candidate for our new API. Find it a very clean and fast solution, but I got stuck on some problem testing the streams which have been announced in the v.0.8 news. 

Was successful to BUILD and INSTALL (this needed admin permission, maybe document this somewhere) on both master and 0.8 release on a windows machine. After adding the PATH variable to the installed directory I could use the tool to generate c++ & .h files and use them in the project, so far with success. 

One of the last steps I was testing is streams and here I get an error:
![image](https://user-images.githubusercontent.com/45189311/80584820-9578fc80-8a12-11ea-9cf3-460a65a09cde.png)

Double checked the installation, but the include folder seems to have the stream files:
![image](https://user-images.githubusercontent.com/45189311/80585002-dffa7900-8a12-11ea-880e-73ba74568a66.png)

Can someone provide a fix or a quick workaround for this?

**Comment by kentonv** [comment]
Hi Vitaliy

On Windows, you will generally have to pass a `-I` flag to `capnp compile` in order to tell it where the installation's include directory is, so that it can find these schema files. Something like:

    capnp compile "-IC:\Program Files (x86)\Cap'n Proto\include" -oc++ scene.capnp

(On Unix, `capnp` knows to look in `/usr/include` and `/usr/loca/include`, but on Windows the installation could be anywhere...)

**Comment by vitaliy-ostapchuk93** [comment]
Hey, it worked, thank you very much!
