### ISSUE TITLE
cannot create generics without pointers and there is no documentation for specifieng pointers

### ISSUE THREAD

**Issue by NikosEfthias** [capnproto/capnproto#999]
I have following struct which fails to compile saying I need to pass CardState pointer to KV however I couldnt find any documentation showing the pointer syntax.
So far I tried `KV(UInt8,&CardState)` and `KV(UInt7,*CardState)` and both are apparently  syntax-wise invalid
```
struct CardStateMap {
	contents @0:List(KV(UInt8,CardState));
	struct CardState{
		r1 @0:UInt8;
		r2 @1:UInt8;
		r3 @2:UInt8;
	}
}

struct KV(K,V){
	k @0:K;
	v @1:V;
}
```

**Comment by jclee** [comment]
I think your problem is that generic parameters need to be "pointer" types, and `UInt8` is not:
> "Only pointer types (structs, lists, blobs, and interfaces) can be used as generic parameters, much like in Java."
https://capnproto.org/language.html#generic-types

`CardState` is a struct, so it is already pointer type and should be fine as-is; it doesn't need any additional notation.  If you change `UInt8` to a struct with a UInt8 field, you can observe it compiling successfully.  I suspect that doing so will have a higher storage overhead than using a non-generic type, though.

**Comment by kentonv** [comment]
Looks like this was answered in a mailing list thread: https://groups.google.com/d/msg/capnproto/jfB3SoPivrc/dfTnyIQpAgAJ

**Comment by NikosEfthias** [comment]
yes thanks
